### ISSUE TITLE
b109 - Registration window is missing PBDT CSJ Path tooltip

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#101]
preq: no signing keys
1: register signing keys
2. observe Registration window PBDT CSJ Path tooltip

Currently we see missing tooltip
![issue101](https://f.cloud.github.com/assets/4265822/485022/a8b7062e-b8e7-11e2-94f5-b40858ec2e8a.png)

**Comment by dbrgss** [comment]
This screen is no longer available in current version.

Recommend closure.

**Comment by AndrewKnox** [comment]
Issue no longer relevant to current version - closed.
