### ISSUE TITLE
b109 - changing passwords for device targets to incorrect password then correct one prevents user from adding debug token

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#105]
found on win8-64

set device target for device
add debug token
close visual studio
open visual studio
set device target password to "password"
close visual studio
open visual studio
set correct device target password
attempt to renew debug token
Debut Token window fails to add debut token information.

workaround seems to be uninstall and reinstall the plugin

**Comment by hkopparru** [comment]
As per the latest plugin 3.0 this issue looks as not reproducing, closing this issue now.
