### ISSUE TITLE
b106 - user is able to spam Renew button in Debug Tokens window

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#111]
ver 1.0.0050

preq:
have a device that contains a debug token

From the debug token window 
Blackberry>DebugTokens
Spam Renew button

Current behaviour:
Each click will renew the debug token on the device

Expected:
Wait for debug token process to resolve before button is clickable again

**Comment by guarnold** [comment]
I think this issue was already fixed. Could you verify if it is still reproducible?

**Comment by srinivas4912** [comment]
It is fixed and verified in build 2.0.0018 on Win8.1 and Win7 (64&32)bit.
