### ISSUE TITLE
b101 - registering keys that have been already registered gives the user incorrect notifications

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#124]
preq: have keys that already have been registered
1. unregister current keys form the Code Signing Properties Window 
2. attempt to register with keys already registered in the Registration Window
Note: user is warned that keys have been used
3. Cancel the Registration window

Current Behaviour:
Registered: False turns to True
and it looks like the user has keys registered but not really.

Workaround: 
register keys that haven't been registered yet.

**Comment by PamC** [comment]
Release note:
Registering keys that have already been registered causes incorrect notifications to the user.
Workaround: Use keys that have not been registered yet.

**Comment by guarnold** [comment]
This issue is not reproducible anymore, after updating the signing methodology.

Before, we were using the plugin to browse files to register. Now we cannot do that. A webpage opens and downloads automatically the file that is needed in the registration process.
