### ISSUE TITLE
b101 - user is able to build project while in debug session

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#125]
1. start a debug session.
2. make changes to project source
3. build project

Current behaviour:
it builds

Expected behaviour:
debug session stops builds and attempts to deploy

Workaround:
Stop debug session then build debug

**Comment by PamC** [comment]
Release note:
Able to build a project while in a debug session.
Workaround: Stop the debug session, build the project, and start a new debug session.

**Comment by guarnold** [comment]
The user is able to make changes but he cannot build while debugging a program. If the user tries to build, a message window will ask him if he wants to cancel the current debugging session or not.
Verified in VS2013, win7 64 bits. Please, verify in other configurations.

**Comment by srinivas4912** [comment]
It is verified in VS2013 plugin from 2.0.0018 on Win8.1 and also verified in VS2012 plugin from 2.0.0018 on Win7 64 bit. 
It is working fine and verification successful as per the above comments.
