### ISSUE TITLE
b113 - copying win32 configuration to a blackberry configuration removes windows related configurations

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#13]
When converting win32 projects user would want to keep project related settings and configurations but not have to manually remove Windows related configuration.

Note: Creating an empty configuration doesn't seem to include any Windows related settings

**Comment by dbrgss** [comment]
We need to discuss this some more with Russell.   I am unsure whether the suggestion is a good idea taking into account what we are trying to do.

**Comment by mattcostanzo** [comment]
Discussed with Product, decided not to do it
