### ISSUE TITLE
App fails to launch in debug mode when MSBuild project build output verbosity is set to diagnostic

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#131]
1. Have a working project and correct target settings ready
2. Ensure MSBuild verbosity is set to diagnostic (Tools-Options-Projects and Solutions-
   MSBuild project build output verbosity-Diagnostic)
3. Clean project
4. Build project
5. Set some breakpoints
6. Initiate debug session

Expected:
Execution to halt and hit breakpoints

Actual:
App deploys but doesn't launch. It hangs on loading screen.

Redoing the steps with verbosity set to Detailed allows for normal debugging.

VS Plugin: 1.0.0010
NDK/Sim: 1673

**Comment by mattcostanzo** [comment]
rcaracaleanu commented 2 months ago 
also observed in bundle 83, version 28

**Comment by dbrgss** [comment]
Estimate: 0.5 Days

**Comment by srinivas4912** [comment]
Passed verification using plugin VS2013 from v2.0.0022 on Win8.1 uisng Astro device with OS 10.2.1.1925 and found as fixed.
