### ISSUE TITLE
b99 - Setting MSBuild project build output verbosity to Minimal/Quiet requires use to build twice

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#132]
preq: have a blackberry project and a device for development

1.Navigate to Build Run From Tools > Options > Projects and Solutions > Build and Run
2.Set MSBuild project build output verbosity to Minimal/Quiet
3.Clean the project
4.Attempt to deploy a project for debugging to device

Behaviour:
it builds first but doesn't launch
launching for deploy again will launch to device

Workaround: 
Set build output to Normal/Detailed

Not recommended to set to diagnostic
#131

**Comment by guarnold** [comment]
Fixed

**Comment by PamC** [comment]
Release note:
Setting MSBuild project build output verbosity to Minimal/Quiet requires you to build twice.
Workaround: Set the build output to Normal/Detailed.

**Comment by dbrgss** [comment]
Please verify...

**Comment by zadmarbella** [comment]
1.01.0046 -
Win 8 64 - VS2012 
Quiet verbosity looks to fail to launch project completely and does not debug
Minimal verbosity looks to work

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by guarnold** [comment]
Minimal verbosity works as expected.

However, Quiet verbosity does not launch the debugger, only the app. A message box is presented to instruct the user to change the verbosity to any other one.

**Comment by guarnold** [comment]
This fix inquires GDB to get the process ID, instead of getting it from the output window.

As a consequence, it requires the GDBParser.dll to be stored together with the package.dll.

I changed the scripts for VS 2012 and 2013.

I tried modifying the PATH variable, but it didn't work. I believe it uses the absolute path, instead of the relative one.

The installer has to be updated.

**Comment by pvallabhaneni** [comment]
Verified the issue on VS2012 and VS2013 using 2.0.0022 plugin and found as fixed. Project is built and deployed correctly after cleaning.
