### ISSUE TITLE
b99 - debug token window does not handle if the user switches devices

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#133]
1. plug -in a device(1) for development
2. setup ip and password
3. access the debug token window
4. add a debug token to that device
5. unplug the device(1)
6. plug in a device(2) also setup for development
7. attempt to add a debug token to that device(2)

Behaviour:
it looks to be working but is not.
If the device(1) and device(2) have different passwords it will attempt and fail to add debug tokens
an error is provided once the user closes the debug token window.

Expected:
user is notified that this action is not supported

Workaround:
Don't add multiple debug tokens in the debug token window. Close the window
setup the device with the correct ip and password and add again.
Don't know what will happen if the passwords are the same.

**Comment by dbrgss** [comment]
Will be fixed:
User Story #229 
Task #490

**Comment by hkopparru** [comment]
tested with 3.0.0001 plugin and reproducing this issue

when you connect the device(2) then try to upload the debug tokens then its showing the error "Debug token is not created against this device, recreate it adding connected device's PIN to list of target devices"
Same debug token will not able to upload to the device(2).
So here we need to create debug tokens for each device separately.

**Comment by phofman** [comment]
From the error message you just posted it clearly looks you did it wrong. When creating or renewing the debug-token you MUST specify PINs of all your devices you are going to upload the debug-token, now and in the future. You just specified single one, so no matter what you do (using this plugin or raw QNX tools) it won't be possible to use it on any other device as this is how the debug-token works.

From the plugin perspective it is possible to create debug-token with multiple PINs defined and then upload it to all defined devices.

**Comment by hkopparru** [comment]
yes you are right,
Now i am able to create debug token for multiple devices using PINs and i can upload the same debug token to that devices at a time. its a wonderful feature in this plugin.

We need to make a document for this feature.

Note: The user before switching the devices first he need to create the debug token for the list of chosen switching devices (with that PINs) then he can upload this debug token anytime.

Thanks for your time

**Comment by hkopparru** [comment]
can i close this issue, please suggest

**Comment by dbrgss** [comment]
Yes... you can close..

**Comment by hkopparru** [comment]
thanks and closing this
