### ISSUE TITLE
b99 - checking permissions in bar-descriptor editor jumps the selection to the top of the list

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#135]
1. Check an item in the permissions list in bar descriptor that is not the first item

Behaviour:
Check fades in and list selection jumps to the top of the list.

Expected:
Check appears and list selection stays in the same spot.

**Comment by dbrgss** [comment]
Fixed:

**Comment by zadmarbella** [comment]
[2.0.0001] verified fixed
