### ISSUE TITLE
b97 - unable to access png image while in debug mode

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#138]
1. launch a project for debugging
2. click on a png

current behaviour:
Error:
The system cannot open the device file specified. (Exception from HRESULT: 0x8007006E)
User wont be able to open the image.

Workaround:
close visual studio and open it again

**Comment by dbrgss** [comment]
Estimate: 0.5 Days

**Comment by hkopparru** [comment]
Tested with [3.0.0015] VS 2013 and this issue is not reproducible, while debugging user is able to open the image. closing this issue now.
