### ISSUE TITLE
b96 - "Backup" should not exist as an option when no keys are registered

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#139]
1. Ensure no keys are registered
2. Open Signing menu

Expected:
Backup button to be disabled since there is nothing to backup

Actual:
Backup button is enabled. Clicking it opnes up the save zip file dialog. Clicking OK on the dialog throws error "Could not find the file \author.p12

**Comment by dbrgss** [comment]
Estimate: 0.5 Days

**Comment by guarnold** [comment]
This issue was fixed before.

**Comment by pvallabhaneni** [comment]
Verified using v2.0.0018 plugin on win7 32bit / 64bit and win8.1 using VS2012/2013 and found as fixed.
