### ISSUE TITLE
MOVED - b113 - unable to deploy to device (failing Tracking command)

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#14]
We are seeing device deploy fail on certain environments.
OS win 7 
It is unclear the cause. There is no workaround.

Error message is below:
1>Done executing task "Message". (TaskId:13)
1>Using "BBNativePackager" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\VSNDK.Tasks.dll".
1>Task "BBNativePackager" (TaskId:14)
1> Tracking command: (TaskId:14)
1> c:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools\Tracker.exe /d C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll /i C:\workspace\FallingBlocks_001\Device-Debug /r "C:\WORKSPACE\FALLINGBLOCKS_001\BAR-DESCRIPTOR.XML|C:\WORKSPACE\FALLINGBLOCKS_001\BAR-DESCRIPTOR.XML|C:\WORKSPACE\FALLINGBLOCKS_001\ICON.PNG|C:\WORKSPACE\FALLINGBLOCKS_001\ICON.PNG|C:\WORKSPACE\FALLINGBLOCKS_001\LICENSE|C:\WORKSPACE\FALLINGBLOCKS_001\LICENSE|C:\WORKSPACE\FALLINGBLOCKS_001\NOTICE|C:\WORKSPACE\FALLINGBLOCKS_001\NOTICE" /b MSBuildConsole_CancelEventbdce0e94eb8549ee9a1967acfa21811a /c C:/bbndk_10.1.0.1020/host_10_1_0_212/win32/x86\usr\bin\blackberry-nativepackager.bat -target bar-debug -devMode "Device-Debug\FallingBlocks_001.bar" "bar-descriptor.xml" "icon.png" -e "Device-Debug/FallingBlocks_001" "FallingBlocks_001" -target bar-debug -devMode "Device-Debug\FallingBlocks_001.bar" "bar-descriptor.xml" "icon.png" -e "Device-Debug/FallingBlocks_001" "FallingBlocks_001" (TaskId:14)
1> The system cannot execute the specified program. (TaskId:14)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.Packager.targets(110,5): error MSB6006: "blackberry-nativepackager.bat" exited with code 1.
1>Done executing task "BBNativePackager" -- FAILED. (TaskId:14)
1>Done building target "BuildBar" in project "FallingBlocks_001.vcxproj" -- FAILED.: (TargetId:6)
1>Done executing task "CallTarget" -- FAILED. (TaskId:8)
1>Done building target "Deploy" in project "FallingBlocks_001.vcxproj" -- FAILED.: (TargetId:3)

**Comment by zadmarbella** [comment]
duplicate already moved
