### ISSUE TITLE
b84 - building to release without a device attached throws deploy to device errors

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#142]
Workaround: is to plug in a device so that the build to release process has a device to launch to.

1.Set a project for build configuration Release BlackBerry
2.Have no device attached
Note: having no IP address to device causes this error
#446

3.Have an IP address to the disconnected device

4.Attempt to Deploy (right-click project > Deploy) or click the Play button to build for Release

Current Behaviour:
Project builds for release and a project bar file is created.

The error produced is expected when user doesn't have a device plugged in when trying to deploy.
However, it looks like something went wrong with the build to release but really something went wrong with deploying to device.

Then user receives error that the device not accessible:
2>BBDEPLOY : error : Cannot connect: Network is unreachable: connect. Please check IP address settings for the target. Try to ping the target.

Expected:
Building to release doesn't require user to have a setup and device plugged in.

**Comment by dbrgss** [comment]
Estimate: 0.5 Days

**Comment by hkopparru** [comment]
Tested with [3.0.0.0015] VS 2013, where attempt to deploy for disconnected device we are getting the expected error as "BBDeploy : error : Cannot connect: Connect to /169.254.0.1:443 timed out. Please check IP address settings for the target. You may have to reboot the target".

while building we are not getting any error. 

so closing this issue now.
