### ISSUE TITLE
b67 - Debugging Multi-Thread application shows an Extra Location that is [External Code] in Thread Window

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#146]
Win 7 64 bit
bbndk 10.0.10.261
b 1.0.0014

1.Launch launch multi-threaded application
2.Hit a breakpoint in a thread

Behaviour:
an Extra [Extrenal Code] Location appears in thread window
(it is believed that it is the GDB thread)

**Comment by mattcostanzo** [comment]
guarnold commented 3 months ago 
The VS behavior for Threads window presents all of the running threads that are related to the program and not only the created ones. In such case, the extra thread (GDB debugger) is presented correctly.

**Comment by AndrewKnox** [comment]
Not an issue - closed.
