### ISSUE TITLE
Able to install the Visual Studio plug-in without requiring the Momentics installer.

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#148]
Summary 
As a developer I want to be able to install the Visual Studio plug-in without requiring the Momentics installer.

Description
The Visual Studio Plug-in will be able to install without a dependency on the Momentics installer

Parent Category: #4  Visual Studio Installation

**Comment by mattcostanzo** [comment]
allee commented 25 days ago 
Work with Elena to figure out if we can remove the dependencies and just use the targets?

Otherwise how can we reduce them? or get the pieces on the download server so we can download it at start.

Rough estimate: 1 day once dependencies are resolved.

**Comment by dbrgss** [comment]
This has been accomplished via the Update Manager user story #65.
