### ISSUE TITLE
b113 - unable to access signing window

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#15]
version 1.01.0006
occurs on win7/8

Error is in the screen shot below

![83179c50-adaa-11e2-9726-a426e24e14fa](https://f.cloud.github.com/assets/4265822/445518/93fb5bfc-b1be-11e2-9ede-ddb6c230a0ed.png)

**Comment by zadmarbella** [comment]
user is able to access signing dialog on b116 on win7 new issue found #189
