### ISSUE TITLE
Add new EULA to build.

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#164]
No description given.

**Comment by allee** [comment]
Alisha to follow up with Legal for a new BB EULA

**Comment by guarnold** [comment]
You can check the EULA (End User License Agreement) during the plug-in installation.

**Comment by guarnold** [comment]
Available in build 2.0.0018 (bundle195).

**Comment by pvallabhaneni** [comment]
Verified EULA (End User License Agreement) implementation for VS2012 / VS2013 on Win 7 32bit / 64 bit and Win 8.1 systems using 2.0.0018 plugin and found as implemented correctly.
