### ISSUE TITLE
Update some methods to add the ability to edit values in the Locals and Watch Windows

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#178]
While cleaning the code for open-source, I've found out that the following methods from AD7Property.cs might be related with the ability to edit variable values in locals and watch windows:
- ConstructDebugPropertyInfo() (specifically in “propertyInfo.dwAttrib = (enum_DBG_ATTRIB_FLAGS)DBG_ATTRIB_FLAGS.DBG_ATTRIB_VALUE_READONLY;”),
- SetValueAsReference()
- and SetValueAsString()

**Comment by mattcostanzo** [comment]
1 day

**Comment by guarnold** [comment]
Done.
