### ISSUE TITLE
Update install scripts.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#180]
Windows Registry must include the following data to enable creating port suppliers to Attach to Process UI (#26):
- in HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\10.0\AD7Metrics\Engine{E5A37609-2F43-4830-AA85-D94CFA035DD2}
  add PortSupplier = {BDC2218C-D50C-4A5A-A2F6-66BDC94FF8D6}
  PortSupplierOLD = {BDC2218C-D50C-4A5A-A2F6-66BDC94FF8D6}
  ProgramProvider = {AD06FD46-C790-4D5C-A274-8815DF9511B8}
- create a new key: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\10.0\AD7Metrics\PortSupplier{92A2B753-00BD-40FF-9964-6AB64A1D6C9F} 
  and add: (Default) = Visual Studio Plug-in for BlackBerry
  CLSID = {BDC2218C-D50C-4A5A-A2F6-66BDC94FF8D6}
  DisallowUserEnteredPorts = 0 (hexadecimal)
  Name = BlackBerry
  PortPickerCLSID = {3FAA02D6-72D8-4F69-A1E6-BB05ECB4E37A}
- create a new key:
  HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\10.0\CLSID{AD06FD46-C790-4D5C-A274-8815DF9511B8}
  and add:
  Assembly = VSNDK.DebugEngine
  Class = VSNDK.DebugEngine.AD7ProgramProvider
  CodeBase = C:\Program Files (x86)\BlackBerry\VSPlugin-NDK\VSNDK.DebugEngine.dll
  InprocServer32 = c:\windows\system32\mscoree.dll
- Create a new key:
  HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\10.0\CLSID{BDC2218C-D50C-4A5A-A2F6-66BDC94FF8D6}
  and add:
  (Default) = BlackBerrySupplier
  Assembly = VSNDK.DebugEngine
  Class = VSNDK.DebugEngine.AD7PortSupplier
  CodeBase = C:\Program Files (x86)\BlackBerry\VSPlugin-NDK\VSNDK.DebugEngine.dll
  InprocServer32 = c:\windows\system32\mscoree.dll
  ThreadingModel = Free

Repeat the same for the following keys:

HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0_Config

HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0Exp_Config

**Comment by zadmarbella** [comment]
All looks the same and located on b119 - 1.01.0014
HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0Exp_Config < don't have this on win8 64
