### ISSUE TITLE
Issues in build 1.01.0010

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#183]
Fixed the following issues in build 1.01.0010:
- updated ProcessesPaths.txt file with the correct project path name;
- handled function breakpoints with wrong names;
- allowed projects that does not have "Excluded directories";
- let the user know if the attached app does not have an associated executable file with symbols.

**Comment by zadmarbella** [comment]
verified 1.01.0013 version 10.x device 10.x sdk
    - updated ProcessesPaths.txt file with the correct project path name; user is unable to debug
    - handled function breakpoints with wrong names; user is able to hit on specified breakpoint
    - allowed projects that does not have "Excluded directories"; user is able to build project

last one requires attach to process which is not in the 1.01.0013 build

**Comment by zadmarbella** [comment]
moved the blocking issue to another issue https://github.com/blackberry/VSPlugin/issues/220
closing this one
