### ISSUE TITLE
b115 - restoring signing keys provides user with false registered message

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#185]
1. From the Code Signing Properties dialog back up signing keys
2. restore signing keys

Behaviour:
Signing keys properties Registered:False
Expected:
Restoring Backup keys provides user with correct message.

**Comment by guarnold** [comment]
Fixed. Please verify this issue.

**Comment by zadmarbella** [comment]
Verified 1.01.0013 - user is able to restore signing keys and be notified that their keys are registered true
