### ISSUE TITLE
2 issues with Port Supplier (related to Attach to Process)

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#186]
Port Supplier initializes the transport and the qualifier (port) only when VS starts. It should be able to update those information whenever the user updates the BlackBerry settings (device and simulator). The workaround now is to close and reopen VS so the changes will make effect.

The second issue happens when starting VS without any data in the BlackBerry settings (device and simulator). It presents a message "Missing Device Password". It should not present any message.

Related to #26

**Comment by mattcostanzo** [comment]
Est 1 day

**Comment by guarnold** [comment]
Fixed the first issue. Could not reproduce the second one.
Please verify this issue.

**Comment by zadmarbella** [comment]
Blocked see https://github.com/blackberry/VSPlugin/issues/190#issuecomment-18933585

**Comment by zadmarbella** [comment]
verified 1.01.0017
Able to modify Setting information and have it reflect on attach to process 
Able to view message if there is no blackberry transport information available from the Settings
