### ISSUE TITLE
b116 - user is unable to register signing keys

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#189]
1. from main menu navigate Blackberry>Signing
2. Locate the CSJ files and input signing key information
3. Click Register button

Expected Result:
3. The csj files should be registered successfully.

Actual Result:
3.It prompted an error "RDK CSJ files are required".

**Comment by mattcostanzo** [comment]
Est 1 day

**Comment by guarnold** [comment]
Fixed. Please verify.

**Comment by zadmarbella** [comment]
Verified fixed on 1.01.0013 - user is able to register signing keys
