### ISSUE TITLE
Test Multi Process Compilation

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#191]

**Comment by mattcostanzo** [comment]
Est .5 day

**Comment by mattcostanzo** [comment]
Issue #25

**Comment by zadmarbella** [comment]
verified 1.01.0014 - Building projects uses multiple cores by default.
Note: there is no way to turn it on and off.
See https://github.com/blackberry/VSPlugin/issues/93

**Comment by zadmarbella** [comment]
#93 is still missing on build 1.0.1.0015

**Comment by zadmarbella** [comment]
#93 verified build 1.01.0017 

flag appears in project properties Configuration Properties > C/C++ > Multi-Processor Compilation
default is blank which is No (do not use multi-process)
No (do no use multi-process)
Yes (-j)
