### ISSUE TITLE
GDB not inserting breakpoint in Playbook.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#197]
14:23:07 - 6-break-insert --thread-group i1 -f C:\FALLIN~1\FALLIN~1\src\main.c:472
14:23:07 - &"No source file named C.\n"
14:23:07 - 6^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="C:\FALLIN~1\FALLIN~1\src\main.c:472",times="0",original-location="C:\FALLIN~1\FALLIN~1\src\main.c:472"}
(gdb) 

The cause of that was the full path for the given file. 

That issue was happening only in Playbook. To fix that, it can be sent 2 commands to GDB. First one with the full path. if it does not work, a second command with only the file name is sent.

**Comment by zadmarbella** [comment]
verified on 1.01.014 - able to deploy on playbook and hit breakpoints
