### ISSUE TITLE
b118 - user is unable to access attach to process drop down

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#199]
build 118 ver 1.0.1.0013 is missing attach to process drop down for BlackBerry

**Comment by mattcostanzo** [comment]
Est .5-1 day

**Comment by guarnold** [comment]
Some entries in the registry had spaces at the end. Those spaces were removed in the installer and the attach to process feature is supposed to work in the next build.

**Comment by zadmarbella** [comment]
verified win7 1.01.0017
Attach to Process 
Transport drop down selection includes Blackberry option
