### ISSUE TITLE
Auto-generation of bar-descriptor.xml does not allow user to manually target a different location other than the default.

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#20]
When you create a new BlackBerry configuration we automatically generate a bar-descriptor.xml for the user co-located to the project file. We do not give the user the ability to choose where they want to save the bar-descriptor.xml. In a normal case this is fine but in the case where a user might have more than one project file saved in the same folder this scenario breaks as the bar-descriptor.xml for one project over writes the other.

**Comment by mattcostanzo** [comment]
Possible Solution:

The easy solution would be to disable the auto-generation of the bar-descriptor.xml when we create a new BlackBerry configuration. It would then be up to the user to manually create a bar-descriptor for their project and locate it wherever they wish.

**Comment by mattcostanzo** [comment]
Possible Solution:

The harder solution would be to prompt the user for a target for the bar-descriptor.xml when you create a new BlackBerry configuration. The user would pick where they want the file to be saved and we would auto-generate the file where they stated.

**Comment by mattcostanzo** [comment]
Possible Solution:

Just thought of another solution that might be a good compromise. I could have it so that we only auto-generate a bar-descriptor.xml file if it's not already added to the project. In this case, if the user wanted to add their own bar-descriptor.xml file to a different location. They could add it BEFORE they add the blackberry configuration. When they do add the configuration.. we would detect the already added file and skip the auto-create.

Thoughts??

**Comment by mattcostanzo** [comment]
Est. 3 days

**Comment by guarnold** [comment]
Fixed. The bar-descriptor.xml file is now created in the folder "projectDirectory + '_barDescriptor' ". That means that each project will have its own bar descriptor folder.

To convert the current projects, please:
1) open current project
2) copy the contents of the bar-descriptor.xml file
3) remove the bar-descriptor file from VS
4) another bar-descriptor file will be generated automatically after the removal, in the correct bar descriptor folder.
5) open the bar-descriptor.xml file and copy the contents that were saved in step 2.
6) save it.

**Comment by zadmarbella** [comment]
This fails in the cocos2d project and no bar-descriptor files are created.

**Comment by mattcostanzo** [comment]
Est .5-1day

**Comment by guarnold** [comment]
The next build has will have a fix for issue #200. This fix is also supposed to solve this issue.

**Comment by zadmarbella** [comment]
Blocked by https://github.com/blackberry/VSPlugin/issues/216 . User now loses folder structure.

**Comment by guarnold** [comment]
The folder structure is not changed by the VS plug-in. It was changed in the new version of Cocos2d that is available for download (2.1.4).

**Comment by zadmarbella** [comment]
verified 1.01.0018
cocos2d creates bar-descriptor for each project solution
