### ISSUE TITLE
Enable the creation of bar-descriptor files for projects located under folders.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#200]
The V8 project (#113) has only one of its 15 projects under "Solution". The other ones are located under subfolders. 

The plug-in should be able to generate bar-descriptor files for all the projects and not for the ones under "Solution" only.

**Comment by guarnold** [comment]
Fixed

**Comment by zadmarbella** [comment]
verified 1.01.0018 - 
Bullet project now creates folders with the prefix BlackBerry-<ProjectName> that contains bar-descriptor 
BlackBerry-AppUnitTest. Projects in Solution contains bar-descriptor.xml that has Application Name.
