### ISSUE TITLE
Improve debug-token capabilities like Momentics IDE

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#214]
- Add support for creating multiple debug-tokens;
- Add support for deleting debug-tokens;
- Add support for importing debug-tokens;
- Add support for editing debut-tokens, so we can have multiple pins;
- Add support for looking details of a specific debug-token;

Problems found when importing an app from a game partner (Sean Paul Taylor).

**Comment by mattcostanzo** [comment]
This epic is not being done based on the new signing methodology.
