### ISSUE TITLE
Visual Studio 2012 - Modify MSBuild process to work with new IDE

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#218]
Related to Issue #298

**Comment by allee** [comment]
Moving to Sprint #52 as there are still issues before this can be marked complete.

**Comment by dbrgss** [comment]
Hi Alisha. I have moved the task to the next sprint and closed the sprint. That task is just waiting on a build from me which I am generating as we speak.

Dave

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Alisha Lee
Sent: Tuesday, July 9, 2013 9:25 AM
To: blackberry/VSPlugin
Reply To: blackberry/VSPlugin
Cc: Dave Burgess
Subject: Re: [VSPlugin] Visual Studio 2012 - Modify MSBuild process to work with new IDE (#218)

Moving to Sprint #52https://github.com/blackberry/VSPlugin/issues/52 as there are still issues before this can be marked complete.

—
Reply to this email directly or view it on GitHubhttps://github.com/blackberry/VSPlugin/issues/218#issuecomment-20673436.

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by dbrgss** [comment]
Have this working in a hard coded format.   Need to add a task to re-write property pages using new VS2012 methodology.
