### ISSUE TITLE
Create the bar-descriptor file in the location specified by the "Application Descriptor" property

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#223]
Currently, the bar-descriptor file is created automatically by the plug-in (VSNDK.AddIn) in the "BlackBerry-projectName" folder, even if there is a location set in the "Application Descriptor" property.

It should be created in the location specified by that property, if it exists.

**Comment by guarnold** [comment]
Related to #215

**Comment by allee** [comment]
This property no longer exists no longer applicable.
