### ISSUE TITLE
Implement New Signing Methodology

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#228]
Summary: As a user we need to be able to make use of the new signing methodology using the BlackBerry ID as the authentication method.   

Description: A new method of attaining signing keys has been implemented by the NDK team.  The visual studio plugin needs to be modified to work with this new paradigm..

Epic: #217

**Comment by guarnold** [comment]
To allow this new signing methodology for the VS plug-in, we have to implement the following four tasks:

• Update the UI (#230).
• Open web browser and get the downloaded bbidtoken file. (#231).
• Authenticate to the Signing Authority servers (#233).
