### ISSUE TITLE
b108 - blank lines added instead of icons when adding in bar-descriptor editor

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#23]
Using Box2D.
Tried to get it to build and it fails 
We are unable to add icons via bar-descriptor editor.
it adds a blank line

It is unclear how to get it to this state user is unable to delete it on the fallingblocks project from http://github.rim.net/evillaricomarbella/Converted_VS_projects_from_Momentics 
but able to delete on a project like Bullet.
![5626dfae-9c97-11e2-9c80-fd3f19379897](https://f.cloud.github.com/assets/4265822/445595/9cf709b6-b1c0-11e2-8bf4-330a16e09729.png)

**Comment by mattcostanzo** [comment]
dburgess commented a month ago 

So the bug affects both the Splash Screen and Icon lists.

You can now add images to both the Splash Screen and Icon lists. At first I wasn't going to automatically add the necessary Asset entry but to get the lists to work correctly I ended up having to do this. So what you will see is the following.

1) You can add an image to either Splash Screen or Icon list from anywhere on your system.
2) The item will be added to the project of the bar-descriptor being edited.
3) An asset entry will be added to the bar-descriptor.xml in the All Configurations section.
4) Removing the icon or splashscreen does NOT remove the item from the project or the associated asset. This needs to be done manually by the user if they desire. (It's possible that they might not want to use an icon but still want the image to be in the project so we don't want to assume this and auto remove.)

Dave

**Comment by mattcostanzo** [comment]
evillaricomarbella commented 25 days ago 

png icon information doesn't appear. also we cannot build to device (attempted using fallingblocks)

**Comment by mattcostanzo** [comment]
evillaricomarbella referenced this issue

Issue #644: b108 - handle input value application descriptor file bar-descriptor.xml in project property page

**Comment by mattcostanzo** [comment]
evillaricomarbella commented 22 days ago 

@dburgess Did we ever get a workaround? This issue might impact our project conversion tasks.

**Comment by dbrgss** [comment]
Fixed 1.01.0030

**Comment by zadmarbella** [comment]
verified 1.01.0041 looks to add entry in bar-descriptor 
seeing odd behaviour with projects see #457
