### ISSUE TITLE
Open web browser and get the downloaded bbidtoken file.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#231]
Open the web browser and save the downloaded file in the right location.

User Story #228.

**Comment by guarnold** [comment]
Done.
It opens the default browser.
The user register and then he must follow the instructions in the browser to create and download the bbidtoken.csk file.
The file is downloaded to the default "Downloads" folder.
Then the file is moved to the correct location.

**Comment by dbrgss** [comment]
Completed

v1.01.0022
