### ISSUE TITLE
Need the ability to edit values in the Locals and Watch Windows

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#24]
Summary: As a user we need the ability to edit values in the locals and watch windows.

Description: Need to be able to double click on the values in the locals and watch windows and edit the values and have it reflect in the debugger.

Acceptance Criteria
TBD

Parent Category #1

**Comment by mattcostanzo** [comment]
dburgess referenced this issue 2 months ago

Issue #396: unable to edit value in locals window while debugging (Closed)

**Comment by mattcostanzo** [comment]
evillaricomarbella referenced this issue a month ago

Issue #136: Modification of Variables in Locals Window (Closed)

**Comment by mattcostanzo** [comment]
allee commented 12 days ago 

Rough Estimate 1 week

**Comment by guarnold** [comment]
While cleaning the code for open-source, I've found out that the following methods from AD7Property.cs might be related with the ability to edit variable values in locals and watch windows:
- ConstructDebugPropertyInfo() (specifically in “propertyInfo.dwAttrib = (enum_DBG_ATTRIB_FLAGS)DBG_ATTRIB_FLAGS.DBG_ATTRIB_VALUE_READONLY;”), 
- SetValueAsReference() 
- and SetValueAsString()

**Comment by guarnold** [comment]
Task #178 (Update some methods to add the ability to edit values in the Locals and Watch Windows)

**Comment by PamC** [comment]
Release note:
Unable to edit value in locals and watch window while debugging.
Workaround: Use immediate window for this task.
