### ISSUE TITLE
GDB is being terminated after receiving more than one Ctrl-C signal

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#241]
Issue #236 is related to an internal GDB issue that was causing GDB to hang after sending a -exec-interrupt command. To fix that, more than 1 Ctrl-C signal was being sent to GDB to force it to be interrupted. 

However, this fix does not work anymore because GDB was fixed. So, sending more than 1 Ctrl-C signal is causing GDB to be terminated.

**Comment by guarnold** [comment]
Fixed. Now, only 1 Ctrl-C signal is sent and GDB is not being terminated anymore.

**Comment by guarnold** [comment]
To be able to verify this issue, the debugging session must be interrupted many times, by hitting the pause/play buttons or by inserting/deleting breakpoints while running the program.

**Comment by zadmarbella** [comment]
verified fixed build 123 ver 1.0.1.0018 Simulator 10.2.0.435
