### ISSUE TITLE
Assertion Exception, after fixing issue #241

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#242]
After fixing issue #241, VS can crash after being interrupted many times due to an assertion exception: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

Before applying this fix, verify if this issue is reproducible. I could see this issue a few times while debugging the plug-in. Maybe, this issue is not reproducible.

**Comment by guarnold** [comment]
To fix that, the following VS option must be unchecked:

Tools menu -> Options -> Debugging -> General -> "Suppress JIT optimization on module load"

Reference: http://social.msdn.microsoft.com/Forums/en-US/8789ea67-fbc5-4a7b-a4eb-d4a8a050d5c1/attempt-to-read-or-write-protected-memory-this-is-often-an-indicating-that-other-memory-is-corrupt

**Comment by guarnold** [comment]
To be able to verify this issue, the debugging session must be interrupted many times, by hitting the pause/play buttons or by inserting/deleting breakpoints while running the program.

**Comment by zadmarbella** [comment]
verified fixed build 123 ver 1.0.1.0018 Simulator 10.2.0.435 
didn't have to use Suppress JIT optimization.
