### ISSUE TITLE
Verify if "No Source Available" window is presented after hitting a breakpoint for the first time.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#244]
I could see this window a few times, but I was unable to reproduce it anymore.

Steps to reproduce:
1 - open a multi-thread app;
2 - start debugging it without any breakpoint set.
3 - while running the program, insert a breakpoint in one of the threads, except the main one.

The "No Source Available" could be presented. If that happens, it is not the expected behavior, since the breakpoint was hit and the source code related to the thread must be presented, with the yellow arrow indicating that it stopped in the expected instruction.

Marked as P3 because I cannot reproduce it anymore.

**Comment by zadmarbella** [comment]
verified fixed build 123 ver 1.0.1.0018 Simulator 10.2.0.435
