### ISSUE TITLE
b123 - refreshing attach to process Available Processes causes dialog to intermittently vanish

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#249]
build 123 ver 1.0.1.0018 Q5 10.2.0.435

Prerequisite: Device/Simulator correct information in Blackberry VS Plugin Settings upload project to device ie. FallingBlocks
1. Debug > Attach To Process
2. Select Transport BlackBerry
3. Select Qualifier Device/Simulator: <IP Address>
4. Open device/simulator uploaded project to run a process on device
5. Click Refresh Available Processes
6. Close Application
7. Click Refresh Available Processes

Current Behaviour:
The Attach to process dialog will intermittently flicker and vanish.

Workaround:
Clicking on VS Window makes it reappear.

Expected:
Dialog not to intermittently vanish. 

Note:
Looks to happen when the application is attempting to close 
and Available Processes is refreshed.
Show process from all users checkbox looks to trigger it also.

**Comment by srinivas4912** [comment]
It is verified using VS2013/12 plugin from 2.0.0022 on Win8.1 and found as fixed. when refreshing Attach to Process available process shows correctly with out any errors.
