### ISSUE TITLE
Support Multi Process Compilation

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#25]
Summary
As a developer we need to be able to optimize the build time by making maximum use of the processors on the machine.

Description
Make sure the build process is using the maximum number of processors supported by the machine being used.

Acceptance Criteria
Not Testable

Parent Category #2

**Comment by mattcostanzo** [comment]
allee commented 12 days ago 

Rough Estimate: 1-2 weeks

**Comment by allee** [comment]
@dbrgss Dave to break this up and complete next week.
