### ISSUE TITLE
b123 - able to view plugin related message when incorrect qualifier is inputted 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#250]
build 123 ver 1.0.1.0018 Q5 10.2.0.435

Prerequisite: Device/Simulator correct information in Blackberry VS Plugin Settings
1. Debug > Attach To Process
2. Select Transport Blackberry
3. Input Incorrect Qualifier Device: <IP Address from Settings>

Current Error
![image](https://f.cloud.github.com/assets/1478549/848833/a66e0224-f469-11e2-8397-6fdd6f413229.png)

Expected
user is warned about incorrect blackberry device qualifier is not set correctly 
in BlackBerry VS Plugin Settings.

Note: Editing Qualifier to be the correct device/simulator IP doesn't connect the device consider preventing users to edit this dropdown.

Default transport Qualifier manual editing gives user Remote Debugging Error prompt

**Comment by allee** [comment]
est. 1 day/

**Comment by guarnold** [comment]
The qualifier field is editable. 

If the user types a string that is similar to one of the available BlackBerry qualifiers (device and/or simulator, depending on the BlackBerry settings), the similar one is selected. If none of them are similar, a default value is selected. 

In case there is no device/simulator set in BlackBerry settings, nothing is presented and the typed text is removed.

**Comment by srinivas4912** [comment]
It is verified using VS2013/12 plugin from 2.0.0018 on win 8.1 and Win7 64 bit and It is working fine as per the above comments.
