### ISSUE TITLE
b123 - unable to attach to process on simulator

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#251]
build 123 ver 1.0.1.0018 Simulator 10.2.0.435 

Prerequisite: Simulator correct information in Blackberry VS Plugin Settings
upload project to device ie. FallingBlocks for debugging
1. Debug > Attach To Process
2. Select Transport BlackBerry
3. Open attached project to run that process on device/simulator
4. Select Qualifier Device/Simulator: <IP Address>
5. Select opened attached project process
6. Click Attach

Current Behaviour:
Unable to attach to simulator process

Expected:
able to debug the attached process 
Note: we can see processes to attach to

**Comment by zadmarbella** [comment]
@guarnold please confirm which build version this issue has been included in.

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
@guarnold Please confirm what version of the simulator do we support Attach to process on?

**Comment by guarnold** [comment]
Used the latest one, that is BB10_2_0X.1155.

**Comment by zadmarbella** [comment]
verified on simulator 10.2.0x.1155
v1.01.0026
user is able to view and attach to simulator process
