### ISSUE TITLE
b123 - able to spam Refresh attach to process application processes

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#253]
Prerequisite: Device/Simulator correct information in Blackberry VS Plugin Settings
upload project to device ie. FallingBlocks for debugging
1. Debug > Attach To Process
2. Select Transport BlackBerry
3. Open attached project to run that process on device/simulator
4. Select Qualifier Device/Simulator: <IP Address>
5. Spam Application Processes Refresh list

Behaviour:
VS can stop responding as requests get resolved.

Expected:
unable to spam the button. 

Note:
Looks to be easier to reproduce if device is unplugged and plugged back in while in Attach to Process dialog

**Comment by guarnold** [comment]
VS works the same way for Win32 processes. Use the Default transport to verify that.

**Comment by allee** [comment]
Zad can you reverify this

**Comment by zadmarbella** [comment]
[2.0.0001] VS2012 win 8 - spamming the default transport doesn't doesn't make visual studio stop responding. going to Blackberry Transport and doing the same thing does.

**Comment by srinivas4912** [comment]
Verified using VS2013/12 plugin from build 2.0.0022 on Win8.1 and Win7 64 bit and found as fixed.
able to Refresh attach to process list.
