### ISSUE TITLE
Auto-detect and download the device target files 

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#255]
-Download the target files from the device, if not connected to the internet
-Match momentics

The auto-detect functionality occurs when the user clicks the play button.  There are several scenarios than can occur at this time:

1) **BlackBerry Configuration - Device NOT Attached:** You will notice a delay on clicking play as Visual Studio attempts to connect to the non-existent device.  It will then build the application but will return an error in the output window stating that the connection timed out and to check your IP Address settings for the target.

2) **BlackBerry Configuration - Device Attached - OS Version = API Level Downloaded:** Visual Studio will build, deploy and debug the application.

3) **BlackBerry Configuration - Device Attached - OS Version != API Level Downloaded:** Visual Studio will build, deploy and attempt to debug the application.  Error message generated in the output screen.

4) **BlackBerry Configuration - Device Attached - OS Version = API Level NOT Downloaded:** Visual Studio will prompt the user to download the appropriate API Level.

5) **BlackBerry Configuration - Device Attached - OS Version = API Level Downloaded but Runtime NOT Downloaded:**
Visual Studio will prompt the use to download the appropriate Runtime.

6) **BlackBerry Configuration - Device Attached - OS Version = API Level NOT Downloaded AND Runtime Not Downloaded:**
Visual Studio will prompt the use to download the appropriate API Level and then on completion it will prompt the user to download the appropriate Runtime.

7) **BlackBerrySimulator Configuration - API Level selected does NOT have downloaded simulator:**
Visual Studio will prompt the use to download the appropriate simulator.

NOTE: If the user selects to NOT install any of the API Levels or Runtimes when prompted the debug session is cancelled as the appropriate environment will not be able to be set up.

**Comment by mattcostanzo** [comment]
@dbrgss to break down into tasks

**Comment by zadmarbella** [comment]
@dbrgss 
Ok to my understanding this is what's the user story is supposed to do. 
Please correct me if I'm wrong.

Auto-detect and download the device(simulator) target files:
Downloads supported api levels and runtimes if user tries to launch a project for debugging to the connected device/simulator. 

It does this by checking the device and simulator os runtime and api level and then proceeds to:
1. download supported api level if it doesn't exist.
2. download supported runtime if doesn't exist.

The behaviour is the same on both simulator and device configuration.
The once appropriate api level and runtime is installed users project will launch for debugging.
Any attempt to debug with unsupported api level or runtime will have errors.
Cancelling the downloads will halt the debugging process.

**Comment by dbrgss** [comment]
That's correct as far as the device side of things in concerned. As I stated on Friday I was still a bit fuzzy on how the Simulator downloads should work. As you know we currently have an issue with it in that it tries to download a simulator even if you already have the latest and greatest installed. For this I have been in touch with Doug Schaefer to see how Momentics is doing this. I will update the notes when I have a better understanding.  

So to reiterate your above description for the device is absolutely accurate.
