### ISSUE TITLE
Attach To Process

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#26]
Parent Category: #1  - Debugging Functionality

Summary
As a developer we need the ability to attach to and debug an already running application running on either the simulator or a device.

Description
Using the Attach to Process window we need to be able to list the currently running applications on either a blackberry device or the simulator and then allow the user to connect to and start debugging those applications.

Procedure:
1.) Begin debug process in [Platform]
2.) Click menu “Debug-->Attach to process” 
3.) Select device from qualifier and selected process want to be debugged. And source code has been loaded in vs2010 with designated breakpoints.
4.) Click menu “DebugTerminate all/stop debugging.”
Expected Results:
2 Attach window shows.
3 Process attached, stop at breakpoint as well.
4 All VS normal features should be restored.

Related Subtasks:
issue #68 add a port to the attach to process screen

**Comment by mattcostanzo** [comment]
allee commented 6 months ago 
Rough est. 4 days

 allee commented 2 months ago 
Moving to Backlog

 allee commented 2 months ago 
Work with someone on Sean Paul Taylor's team to get fresh insight.

**Comment by guarnold** [comment]
Things to do: 
- Instantiate the debug engine when starting VS, i.e. in the Connect() method from AddIn.cs, and not after hitting the play button.
- The debug engine constructor must create an instance of PortSupplier, that will instantiate Ports. (see http://social.msdn.microsoft.com/Forums/en-US/vsx/thread/bae822ef-4b8d-4772-8bd2-015b6607ac58)
- If that works, try building other kind of projects (win32 for example) just to verify if VS is working as expected and not using our debug engine to debug other projects.

**Comment by guarnold** [comment]
There are 2 new tasks associated to this user story. The first one must be completed before merging the latest code into Next, while the second one can be done later.
- Update install scripts. (#180)
- Merge 2 ProgramNode classes into one. (#179)

**Comment by zadmarbella** [comment]
https://github.com/blackberry/VSPlugin/issues/190 Testing task creaated
