### ISSUE TITLE
Implement an internal web browser for the new Signing methodology

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#265]
The current implementation of the new signing methodology uses the default browser.

We should use an internal browser for that.

Related to user story #228

**Comment by guarnold** [comment]
Started implementing using the WebBrowser component. Getting two issues at this moment:
- The internal browser is not working properly with HTTPS. It works well with HTTP but not with HTTPS. Current behavior:
  1 - It doesn't open the web page and presents a option to "refresh".
  2- After refreshing, it shows a security warning, asking if you want to continue navigating or not.
  3 - If chose to continue navigating, it finally opens the expected web page.
- The internal browser is blocking downloads.

**Comment by mattcostanzo** [comment]
2 days estimate

**Comment by dbrgss** [comment]
Contained in 1.01.0022
