### ISSUE TITLE
Create Tests for Update Manager - Remove a device target

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#267]
Ref Dev Task https://github.com/blackberry/VSPlugin/issues/226

**Comment by dbrgss** [comment]
Developers Build - \\CI0000002338503\Visual_Studio_Plugin_DevBuilds\BlackBerry Native Plug-in for Microsoft Visual Studio_NEXT224.exe

**Comment by zadmarbella** [comment]
tests created for update manager uninstallation of api levels
