### ISSUE TITLE
Create Tests for Update Manager - Add a new target to project

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#268]
Ref Dev task: https://github.com/blackberry/VSPlugin/issues/225

**Comment by dbrgss** [comment]
Included in Developers Build: \CI0000002338503\Visual_Studio_Plugin_DevBuilds\BlackBerry Native Plug-in for Microsoft Visual Studio_NEXT224.exe

**Comment by zadmarbella** [comment]
Filed issue doesn't on work on NEXT224  https://github.com/blackberry/VSPlugin/issues/278 
waiting for next build

**Comment by zadmarbella** [comment]
Added test case to update manager to install api levels
