### ISSUE TITLE
Create Tests for Update Manager - Retrieve list of available targets

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#269]
Dev Ref: https://github.com/blackberry/VSPlugin/issues/224

**Comment by dbrgss** [comment]
Included in Developers Build: \CI0000002338503\Visual_Studio_Plugin_DevBuilds\BlackBerry Native Plug-in for Microsoft Visual Studio_NEXT224.exe

**Comment by zadmarbella** [comment]
Added test cases to view api level list in Update Manager
