### ISSUE TITLE
[1.01.0019] unable to access settings window

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#281]
1. installed plugin BlackBerry Native Plug-in for Microsoft Visual Studio_v1_01_0019.exe
2. Tried to access Settings Dialog 

Behaviour:
unable to access settings dialog.
![unabletoaccesssettings](https://f.cloud.github.com/assets/1478549/962599/bcf60eb2-04f2-11e3-88f9-bc5d55a315ec.png)

Note:
used uninstall script to remove the plugin after installing using the next branch.

**Comment by dbrgss** [comment]
Where do you have the command line tool installed??  Sorry I should have mentioned it earlier that the directory should be bbndk_vs now.    My fault.

Dave

**Comment by zadmarbella** [comment]
@dbrgss should we be expecting the command line tool to be part of the installer or is this step necessary every time?

**Comment by zadmarbella** [comment]
closing adding the command line tools in the correct location resolves the issue.

**Comment by dbrgss** [comment]
This will be bundled with the installer yes.  As of right now I don't have the final version of the utility... which is why it's not part of the installer.
