### ISSUE TITLE
[1.01.0019] able to spam the install button from the update manager

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#282]
1. from the update manager select an Available Api Level andclick Install.
2. Acknowledge the dialog box.
3. Wait for a bit and click install again.

Behaviour:
Dialog from step 2 pops up again

Expected:
user is not able to launch the same api level install again

**Comment by zadmarbella** [comment]
v. 1.01.0022
it looks to spawn multiple instances of eclipsec.exe and has the potential of crashing the visual studio instance.

related issue:
#301

**Comment by dbrgss** [comment]
Version v1.01.0024

**Comment by zadmarbella** [comment]
verified 1.01.042 win 7 2010 win 8 2012
