### ISSUE TITLE
[1.01.0019] unable to install other available versions from update manager than 10.0

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#283]
1. from the update manager select an Available 10.2 Api Level and click Install.
2. Acknowledge the dialog box.

Expected:
selected available api level is installed

Current Behaviour:
The same 10.0 is installed even if 10.1 or 10.2 is selected.

**Comment by dbrgss** [comment]
Fixed: 1.01.0022

**Comment by zadmarbella** [comment]
Verified on 1.01.0022
user is able to install selected api levels
