### ISSUE TITLE
[1.01.0019] update manager dialog looks to vanish when moving application focus away from visual studio and going back 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#284]
win 7 vs2010
1. From Blackberry > Setting > Click Get more to access Update Manager dialog
2. Switch to a different application
3. Switch back to Visual studio

Behaviour:
Update manager window looks to be gone and user is unable to interact with VS

Workaround:
Alt+Tab to Update Manager Dialog

**Comment by dbrgss** [comment]
Version 1.01.0024

**Comment by zadmarbella** [comment]
verified 1.01.0042 
win 7 2010
win 8 2012
