### ISSUE TITLE
New Signing Methodology - Test to make sure qnxtools are included in build

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#297]
Task: #287 

After install there should be a folder containing the qnxtooling at the following location.

C:\Program Files (x86)\BlackBerry\VSPlugin-NDK\qnxtools

**Comment by zadmarbella** [comment]
created test to check for files in the folder C:\Program Files (x86)\BlackBerry\VSPlugin-NDK\qnxtools
