### ISSUE TITLE
[1.01.0022] clicking on install on an unselected item installs the selected item from update manager

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#300]
1 From Blackberry > Setting > Click Get more
2 Select a api level from list of Available 
3 Click install of another Available api level item 

Behaviour:
installs selected item even though user clicks on button 

Expected:
The api level that install is clicked is installed. 
consider possibly removing the ability to select altogether.

**Comment by dbrgss** [comment]
1.01.0026

**Comment by zadmarbella** [comment]
verified on 1.01.0026
the available and installed list isn't select-able. user just clicks on install 

Filed issue #366, #367, #368

@dbrgss is there a why the close button is unclickable and the close window is clickable when you install/uninstall an api level?
