### ISSUE TITLE
[1.01.0022] interacting with install/uninstall button provides user with inadequate message from update manager

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#301]
From Blackberry > Setting > Click Get more
Select a list of Available/Installed 
Click Install/Uninstall

Behaviour:
messages appears at the bottom of the update manager of status
then mentions its 'Complete' but it isn't.

![uninstallmessage](https://f.cloud.github.com/assets/1478549/1003034/03c3804c-0a87-11e3-88ad-0c5f0e9a43c4.png)

**Comment by allee** [comment]
issue #305 should cover this.
