### ISSUE TITLE
[1.01.0022] clicking unregister keys prompts an invalid message from signing unregister window

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#302]
1. from Blackberry > Signing
2. Click unregister

Current behaviour:
window prompt with invalid message
![unregisterwindowvalidity](https://f.cloud.github.com/assets/1478549/1004007/598a2a1e-0a99-11e3-8d9f-18d7984a1d9c.png)

Expected:
The user should just register using the new signing methodology

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verified 1.01.0042
win 7 2010
win 8 2012
