### ISSUE TITLE
[1.01.0022] adding bar-descriptor app permission doesn't have complete list of supported permissions

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#303]
1. open bar descriptor.
2. view Permissions list

Current behaviour:
It looks like we are missing a bunch of them.

expected:
We match the list of available Application Permissions
https://developer.blackberry.com/native/documentation/core/com.qnx.doc.native_sdk.devguide/com.qnx.doc.native_sdk.devguide/topic/c_appfund_accessing_restricted_functionality.html

Workaround: 
add it manually

Note: it is unclear on how we are going to support different api levels.
ie. if 10.1 is selected only the list of supported permissions appears for that and not 10.2 supported permissions. Also it is unclear on if the applications with 10.2 permissions are expected to build using 10.1 api level. Further investigation is needed.

**Comment by dbrgss** [comment]
Version 1.01.0026

**Comment by zadmarbella** [comment]
verified on 1.01.0027
List matches target api level.
Filed #371, #372
