### ISSUE TITLE
[1.01.0022] user is unable to build for release

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#304]
using the FallingBlocks project
1. Select Release from Drop down menu
2. Build project

Current Behaviour:
2>BBSIGNER : error : Failed to decrypt keystore, invalid store password or store password not supplied.
2>  Exception in thread "main" java.lang.RuntimeException: Failed to decrypt keystore, invalid store password or store password not supplied.
2>      at net.rim.device.codesigning.barsigner.BarSigner.for(Unknown Source)
2>      at net.rim.device.codesigning.barsigner.BarSigner.if(Unknown Source)
2>      at net.rim.device.codesigning.barsigner.BarSigner.main(Unknown Source)
2>  The command exited with code 1.

Expected:
Application is compiled and packaged

**Comment by mattcostanzo** [comment]
Version 1.01.0024

**Comment by zadmarbella** [comment]
Version 1.01.0025 
able to build for release.
