### ISSUE TITLE
[1.01.0022] registration window dialog looks to vanish when moving application focus away from visual studio and going back

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#308]
preq: blackberry ID
1. from main menu navigate Blackberry>Signing
2. Click Register button
3. Signin from the Sign-in to create and dowload your BlackBerry ID Token window
4. input valid password and
5. click Get token
6. From Registration Window input Author name and csk password from step 4
7. Switch to a different Application
8. Switch back to visual Studio

Current behaviour:
Registration Window looks to be gone and user is unable to interact with VS

Workaround 
Alt+Tab to Registration Window

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verification failed
reproducible v1.01.0027

**Comment by allee** [comment]
Closing as there is a task for this.
