### ISSUE TITLE
[1.01.0022] user is notified that api level doesn't support attach to process

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#310]
preq: a device build that doesn't support attach to process 
anything before 10.2 Beta 1 (need to verify)
1. Attempt to attach to process

Current Behaviour:
it fails to with no notification

Expected:
user is notified that they cannot attach to process.

**Comment by allee** [comment]
est. 1 day

**Comment by hkopparru** [comment]
Verified in [3.0.0017] VS 2013, 10.2 OS and we are able to attach the process and no error found.

closing this issue.
