### ISSUE TITLE
[1.01.0022] Register Window with blank Author and password notifies with incorrect message for password input

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#312]
Preq: blackberry ID
1. from main menu navigate Blackberry>Signing
2. Click Register button
3. Signin from the Sign-in to create and dowload your BlackBerry ID Token window
4. input valid password and
5. click Get token
6. From Registration Window leave blank Author name and csk password
   7 Click Ok

Current Behaviour: incorrect notification about password entry.
![invaliderrorpassword](https://f.cloud.github.com/assets/1478549/1004873/1fc54c52-0aab-11e3-96cb-5a1097e6fc73.png)

Expected:
Notification has to ask user to input their Blackberry Token ID password

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
v1.01.0027
now mentions blackberry id token password
