### ISSUE TITLE
[1.01.0022] able to complete signing registration with incorrect password input from Registration Window

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#313]
Preq: blackberry ID
1. from main menu navigate Blackberry>Signing
2. Click Register button
3. Signin from the Sign-in to create and dowload your BlackBerry ID Token window
4. input valid password and
5. click Get token
6. From Registration Window input Author name and incorrect csk password 
   7 Click Ok

Current Behaviour:
Registration completes and signing is set to true

Expected:
notification of password mis-match.

Note:
Notification appear of invalid csk password when trying to do anything with Debug tokens. 

Workaround:
Unregister and re-register

**Comment by guarnold** [comment]
The command responsible for registering the certificate (blackberry-keytool) does not verify if the password used to download the bbidtoken.csk file is the same. So, the user can register a different password but he will not be able to request a debug token. 

When that happens (user request a debug token and it fails), a message window is presented, explaining that he has two options:
- if he remember the bbidtoken password, he can register again, reentering the author name and the password (the registration window is presented if he clicks "ok" button). Then, the debug token process is restarted automatically;
- if he does not remember the password, he might close this window (or click "cancel" button), and then go to the BlackBerry -> Signing menu to unregister and then to register, which will start the process that will download the bbidtoken.csk file.

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verified 1.01.0027
user is queried for correct password upon debug token creation on device.
Filed #373, #374
