### ISSUE TITLE
[1.01.0022] able to install 10.2 beta 1 when beta 10.2 gold is installed from update manager

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#314]
preq: have a 10.2 sdk installed

1 From Update Manager try to install 10.2 Beta

Current Behaviour:
it tries to install and message "Completed" appears 

Expected:
user is prevented from installing lower versions of 10.2 api levels

**Comment by allee** [comment]
est .5 days.

**Comment by guarnold** [comment]
Beta versions are not considered by the update manager anymore. You will not see any Beta version available to install.

**Comment by pvallabhaneni** [comment]
Verified VS2012 / VS2013 using 2.0.0018 plugin on Win 7 / Win 8.1 and found that beta version API levels are not available to download.
