### ISSUE TITLE
[1.01.0022] signing registration web view doesn't fit resize to fit the content within 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#315]
Going through the signing registration prompts the user with a cut off view.
workaround is to resize it manually to fit. 
![signingdoesntresizetofitcontent](https://f.cloud.github.com/assets/1478549/1005214/fab2ee70-0ab3-11e3-9794-8c8cb8c9caf6.png)

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
Expected: allow to resize and maximize

**Comment by zadmarbella** [comment]
verified 
1.01.0027
