### ISSUE TITLE
[1.01.0022] unable to access Blackberry Settings window if there is no network connection(internet connection)

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#318]
1. unplug/remove network connection
2. Access blackberry Settings window From Blackberry > Settings

Current Behaviour:
A series of notifications appears one after another rendering Visual Studio unusable.

Expected Behaviour:
able to access Settings Window

**Comment by dbrgss** [comment]
Fixed 1.01.0027

**Comment by zadmarbella** [comment]
verified 1.01.0027
user is not inundated with messages.

Filed issues against this fix #369
