### ISSUE TITLE
[1.01.0022] installer EULA has character artifacts

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#319]
Looks to be at the last lines of it. 
Possible encoding issue. 
It looks fine in other machines.

![possiblelicenseencodingissue](https://f.cloud.github.com/assets/1478549/1009955/39e98ac6-0b41-11e3-85ca-56fa9ad6a5ff.png)

**Comment by allee** [comment]
est .5 days to convert to text file.

Alisha is getting a new EULA

**Comment by guarnold** [comment]
A new EULA was added to the build (#164) and it doesn't seem to have character artifacts. Please verify.

Available in build 2.0.0018

**Comment by srinivas4912** [comment]
Verification successful, Verified EULA using VS2012/13 plugin from build 2.0.0018.
