### ISSUE TITLE
[1.01.0022] Tablet OS is available to download on if user installs Tablet SDK 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#320]
1. install https://developer.blackberry.com/playbook/
2. Access Update Manager Blackberry>Settings>Get More

Current Behaviour:
![updatemanageravailabletablet](https://f.cloud.github.com/assets/1478549/1010178/7787e3e2-0b45-11e3-9235-4ba9d329bc6f.png)

Expected:
Tablet OS is not included. 

Workaround:
remove qconfig from 
C:\Users<username>\AppData\Local\Research In Motion\BlackBerry Native SDK\qconfig\qnx_blackberry_native_development_kit_2.1.0.xml

**Comment by dbrgss** [comment]
Fixed 1.01.0027

**Comment by zadmarbella** [comment]
1.01.0027 is blocked by #369

**Comment by zadmarbella** [comment]
reassigned to @dbrgss unclear on behaviour on list generation. 
v1.01.0041 looks to not include previously installed IDEs like Playbook

**Comment by dbrgss** [comment]
So talked to Doug.   The Command Line tool no longer picks up the other NDK's.   The behavior will be the following.

NDK's including the 2.1 Tablet NDK will appear in the drop down list on the Settings screen available for selection by the user.  Those NDK's will NOT appear in the Installed list on the Update Manager.    

Dave

**Comment by zadmarbella** [comment]
closing
updated api level view list test case to verify that no IDE installed outside the vsplugin like Playbook or Momentics appears in the list of available API Levels
