### ISSUE TITLE
Signing Key - Cannot use BlackBerry as your Author ID

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#322]
It turns out that you cannot use the name BlackBerry as your author ID when registering a signing key.  When you try to create a debug token with this author ID you will get an error.   BlackBerry is a reserved name.

We need to put some validation in our dialog to catch this and warn the user to pick something else.

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verified v.1.01.0027
user is not allowed to use "Blackberry" as an author name
Filed #377, #376
