### ISSUE TITLE
[1.01.0022] able to complete signing registration with no error checking for Native SDK installation

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#323]
Preq: blackberry ID, no api level installed/NDK

1 from main menu navigate Blackberry>Signing
2 Click Register button
3 Signin from the Sign-in to create and dowload your BlackBerry ID Token window
4 input valid password and
5 click Get token
6 From Registration Window input Author name and incorrect csk password 
7 Click Ok

Current Behaviour:
Errors window appears preventing user from continuing

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verified 1.01.0027
user is able to get bbid tokens
note that Java needs to be installed first #321 
filed #380

**Comment by zadmarbella** [comment]
looks to have regressed 1.01.0031

**Comment by zadmarbella** [comment]
wrong issue reclosing
