### ISSUE TITLE
[1.01.0022] windows are resizable [minor]

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#328]
We could use some consistency on what type(s) of windows content should appear in.

Code Signing Properties
Settings
Debug Tokens

**Comment by allee** [comment]
est .5 days

**Comment by srinivas4912** [comment]
Windows are not resizable and consistency is maintained.
Verified using VS2013/12 from build 2.0.0022 on Win8.1 and Win7 64 bit.
