### ISSUE TITLE
[1.01.0022] able to view debug token dialog when the only interaction is to close

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#329]
Currently, if there is an issue that prevents a user from adding/renewing debug tokens a notification appears. The user closes the notification and then the Debug Token dialog appears only to have the user close it again.

**Comment by guarnold** [comment]
VS 1.01.0025

**Comment by zadmarbella** [comment]
verified v1.01.0027
debug token window doesn't open if an error/notification occurs that prevents user from adding debug tokens
