### ISSUE TITLE
[1.01.0023] vs2012 fails to install plugin

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#334]
Win8
1. installed plugin
2. turn on vs2012 

Current Behaviour:
![errorwin8install](https://f.cloud.github.com/assets/1478549/1013357/a690625a-0b85-11e3-91f2-9cc064b315b9.png)

Tried on Win 7 and it didn't look like it installed.

**Comment by dbrgss** [comment]
For Windows 7 please go to the Tools Menu and check in the Addin Manager to see if you can see our Addin... also check the extension manager to see if you can see our extension.

**Comment by zadmarbella** [comment]
@dbrgss where should the Blackberry Menu Item appear?
This is what we are seeing on Win 7
![missingmenuitem](https://f.cloud.github.com/assets/1478549/1013383/c877c556-0b86-11e3-9866-a2064738fda0.png)

**Comment by dbrgss** [comment]
There is two issues here.
- Installation for VS2012 on Windows 7 
- Installation for VS2012 on WIndows 8

**Comment by dbrgss** [comment]
Installation for VS2012 on Windows 7 should be fixed in 1.01.0024.  NOTE: This one might take a bit of back and forth as the issue lies in a refresh command being run at end of install.  Gustavo and my machines have already been updated and so I am having trouble verifying the fix for this.

**Comment by dbrgss** [comment]
Fixed in 1.01.0025

**Comment by zadmarbella** [comment]
verified on 1.02.0025
plugin looks to install on win7 and win8
