### ISSUE TITLE
[1.01.0024] vs stops responding when attaching to process while debugging 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#342]
preq: have 2 different projects and one loaded on the device
1. debug the project not loaded on the device
2. attempt to attach to process. Debug > Attach To Process
3. Select Transport BlackBerry
4. Open attached project to run that process on device/simulator
5. Select Qualifier Device/Simulator: <IP Address>

Behaviour:
Attach to process stops responding and user has to force close

Expected:
notified/stopped from performing this action

**Comment by guarnold** [comment]
If VS is already debugging a BlackBerry app, the user won't be able to use the BlackBerry Transport. He will see a message that he has to select a different Transport or close the BB debugging session.

**Comment by guarnold** [comment]
Available in build 1.01.0026

**Comment by zadmarbella** [comment]
verified 1.01.0041 win 8 vs 2012, win 7 vs2010
