### ISSUE TITLE
[1.01.0024] unable to view notification when device disconnects while attaching to a process

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#343]
Preq: have a application loaded on the device.

```
1. Debug > Attach To Process
2. Select Transport BlackBerry
3. Open attached project to run that process on device/simulator
4. Select Qualifier Device/Simulator: <IP Address>
5. Select opened attached project process
6. Click Attach
7. Detach Device
```

Current Behaviour:
VS looks to stop responding and eventually a message of failing to connect appears.

expected: able to view unable to connect notification

**Comment by guarnold** [comment]
The current behavior is the expected one. After disconnecting the device while attaching to a process in that device may cause VS and GDB to hang for a while (around 7 to 8 seconds). After that time, a timeout error happens and VS presents the message "Unable to attach to process".

I also believe that, if the user do that, he knows that he may cause some unexpected behavior. In such case, VS just spend sometime trying to attach, presents a message box after that time and end the attach to process task nicely.

**Comment by zadmarbella** [comment]
closing not an issue.
