### ISSUE TITLE
[1.01.0025] vs2012 plugin dialog do not match the same colour scheme as 2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#347]
Dialog boxes like Signing, Settings, and Debug Token. Please review all dialog boxes for this.

**Comment by allee** [comment]
est .5 days

**Comment by pvallabhaneni** [comment]
verified the issue using 2.0.0018 plugin on Win 7 64bit/32bit. All the dialogs are asper the color schema of VS2012
