### ISSUE TITLE
[1.01.0025] unable to view bar-descriptor Editor 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#348]
doesn't open with this error message.

![objrefnotset](https://f.cloud.github.com/assets/1478549/1028366/6c0809ce-0e84-11e3-9215-311af8d12cde.png)

Workaround: edit the code manually

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
reproducible on build 1.01.0031

**Comment by zadmarbella** [comment]
verified 1.01.0041 win 8 vs 2012
