### ISSUE TITLE
[1.01.0025] attach to process device misconfiguration message implies device is not connected

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#360]
preq: setup device with wrong ip/password
1. Debug > Attach To Process
2. Select Transport BlackBerry
3. Open attached project to run that process on device/simulator
4. Select Qualifier Device/Simulator: <IP Address>

Current Message:
![attachtoprocessmisconfigureddevicesetting](https://f.cloud.github.com/assets/1478549/1036471/970a8444-0f3d-11e3-9d03-e47b4de13ca8.png)

Expected:
failure to connect due to mis-configured device in settings.

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042
win 7 2010
win 8 2012
Message includes both not connected device and mis-configured device
