### ISSUE TITLE
[1.01.0026] attach to process dialog stops responding before user is notified of a failure to connect

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#361]
build 123 ver 1.0.1.0018 Q5 10.2.0.435
Prerequisite: Device/Simulator with incorrect IP Blackberry VS Plugin Settings
1. Debug > Attach To Process
2. Select Transport Blackberry
3. Select Qualifier Device:

Current Behaviour:
VS stops responding for a while and VS looks to hang and a notification message appears of device inability to connect.

**Comment by allee** [comment]
est .5 days

**Comment by guarnold** [comment]
Unable to reproduce in Win 7, VS 2013.

The plugin takes sometime to identify a connection failure. Maybe that's why it looks to be unresponsive for around 7 seconds, before presenting the notification message. This is the expected behavior (wait for 7 seconds).

**Comment by srinivas4912** [comment]
This issue is verified using VS2013/12 plugin from build 2.0.0022 on Win8.1 and Win7 64 bit.
As per the comments, it is working as expected behavior.
