### ISSUE TITLE
[1.01.0026] unable to add debug token on device

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#362]
win8 vs2012
preq: setup device for debug token

Blackberry > Debug Token
Click Add

current behaviour:
no debug token is added on the device.

**Comment by guarnold** [comment]
Had to change some references to DLLs to fix this issue.
Some references belong to VS2010 DLLs and were not available in VS2012.

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified on 1.01.0040
closing able to add debug token on vs2012 win 8
