### ISSUE TITLE
[1.01.0026] user should not be able to debug if no device runtime exists

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#365]
preq: device with os version higher than current runtime
1. Attempt to debug

Current Behaviour:
user is able to debug on projects with no associated runtime

Expected:
user is prevented from debugging with incorrect runtime and is asked to download the correct one.

**Comment by dbrgss** [comment]
Fixed in 1.01.0029

**Comment by zadmarbella** [comment]
verified 1.01.0042 
win 7 2010
win 8 2012
simulator 10.2.1725
prompts user to download proper runtime
