### ISSUE TITLE
[1.01.0026] update manager clicking uninstall gives the user the same message as install

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#366]
preq; have a api level installed

From Update manager Blackberry > Settings > Get More
Click Uninstall on an API level

Current behaviour:
![notificationsamebothinstalluninstall](https://f.cloud.github.com/assets/1478549/1037376/5597e05e-0f4e-11e3-97c5-a14b4e4e281d.png)

**Comment by dbrgss** [comment]
1.01.0030

**Comment by zadmarbella** [comment]
When the user clicks install while uninstalling the user still gets the message above.

**Comment by zadmarbella** [comment]
Reopening not verified in a build

**Comment by zadmarbella** [comment]
verified 1.01.0042
win 8 2012 
win 7 2010
message covers both uninstall/install
