### ISSUE TITLE
[1.01.0026] update manager list can potentially get cut off

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#367]
We can't scroll down.

![availablelistcouldcutoff](https://f.cloud.github.com/assets/1478549/1037402/c89aba0e-0f4e-11e3-9ab6-d7f6a5cf5943.png)

**Comment by dbrgss** [comment]
Fixed in 1.01.0030

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 for Windows 7-64 VS2010.

I was not able to verify in Windows 8-64 VS2012 because there is not enough API levels to present in the "Installed" and "Available" lists.

**Comment by zadmarbella** [comment]
Closing update test case
