### ISSUE TITLE
[1.01.0026] update manager list can intermittently vanish

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#368]
was clicking in the update manager dialog clicking install/uninstall and list items and list vanished. unclear on the cause. unable to consistently reproduce.

screenshot below was from an earlier version of the plugin but ran into it again in version 1.01.0026
![updatemanagerlistvanishesintermittently](https://f.cloud.github.com/assets/1478549/1037479/6f9d8fe2-0f50-11e3-8f3f-6516b44e8014.png)

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 in these platforms:
a.  Windows 7-64 VS2010
d.  Windows 8-64 VS2012

**Comment by zadmarbella** [comment]
Closing updated test case
