### ISSUE TITLE
[1.01.0027] unable to access update manager after network connection is restored

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#369]
1. unplug/remove network connection
2. Access blackberry Settings window From Blackberry > Settings
3. Click Get more
4. click Ok on Settings notificition warning user of internet connection issues
5. plug/restore network connection
6. Click Get more

Behaviour:
Settings notification warning in step 4 appears and cannot be resolved even after closing and opening vs.

No workaround exists currently blocking update manager. uninstalled and installed the plug-in and clicking Get More... stops vs from responding.

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 in these platforms:
a. Windows 7-64 VS2010
d. Windows 8-64 VS2012

**Comment by zadmarbella** [comment]
1.01.0035 it looks to have shifted here #443 the user receives notification of no network connection if they lose it while the tool is running. If they try using visual studio after their network connection is out they get the behaviour from #443.

**Comment by zadmarbella** [comment]
1.01.0041 verified win 7 2010 win 8 2012
filed #453
