### ISSUE TITLE
A way to have a clean machine

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#37]
Parent Category: #7  - Open Source

Summary
As a user we need a script to fully uninstall the plug - in from a machine.

Description
We need to be able to have our open source users be able to install and uninstall the visual studio plugin without InstallShield. To this end we need to create a batch file to add and remove the plugin.

**Comment by mattcostanzo** [comment]
allee commented a month ago 

I think this was already completed.

Dave can you confirm and close if it is.

**Comment by mattcostanzo** [comment]
dburgess commented a month ago 

This is a User Story and I think Russell needs to close those.. no??

Yes the work is completed

**Comment by allee** [comment]
Closing this as it's not reeeeeeeally requested by Product but was work required for Open Sourcing

**Comment by allee** [comment]
Talking to Zad this currently does not exist reopening
