### ISSUE TITLE
[1.01.0026] update manager close button is unclickable but window can still be closed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#370]
unclear on user interaction. what is the impact when closing the window while install is happening?
1. From the Blackberry > Settings > Click Get More
2. Select and install a api level

Current behaviour:
Close button is unclickable but window can still be closed

![closebuttonunclickablewindowiscloseable](https://f.cloud.github.com/assets/1478549/1043017/94a5e658-0ff6-11e3-84c8-a7d824cbed5f.png)

possible expected behaviour: user is unable to close the dialog using [x] when update manager is running an install/uninstall process 

Note: the same issue occurs when user is installing run time

unexpected behaviour occurs when user cancels these processes midway through. 

Workaround is unknown if user gets their machine in this state. possibly delete everything and try again.

**Comment by dbrgss** [comment]
Included in v1.01.0036

**Comment by zadmarbella** [comment]
verified 1.01.0042 win 7 2010, win 8 2012
reference #450
