### ISSUE TITLE
[1.01.0027] reauthorization of bb id token from debug token dialog looks unresponsive when correct authentication is provided

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#373]
1. create a bb id token with incorrect password inputted from Signing Registration Window
2. attempt to create a debug token
3. click ok on the error notifying of incorrect password.
4. from Registration Window input correct password
5. Click Ok

Current Behaviour:
Debug Token window looks unresponsive and eventually user gains control with debug token on device.

Expected:
some sort of indicator of process progress

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042 
win 7 2010
win 8 2012
notified of incorrect signing password is used when generating a debug token
Once the user inputs correct password they need to go to  Blackberry > Debug Tokens dialog and try to add debug tokens again.

**Comment by srinivas4912** [comment]
This issue is reproduced on Win 8.1 VS2013 with bundle187[build 2.0.0012]

**Comment by hkopparru** [comment]
tested with 3.0.0001 plugin and issue is not reproducible
1. when you enter wrong password its showing the error
2. when you enter correct password in the registration window then debug generated and showing the result "created BlackBerry ID token" in Developer Registration window.

closing this issue.
