### ISSUE TITLE
[1.01.0027] user receives 2 different dialogs for notifying invalid  bb token password if device doesn't have bb token or not

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#374]
With no bb id token already on the device.
![errorcskpassword](https://f.cloud.github.com/assets/1478549/1044235/c2121456-100d-11e3-983d-814885aa1613.png)

With with bb id token on the device
![errorcskpassworddevicewithdebugtoken](https://f.cloud.github.com/assets/1478549/1044236/c3d09204-100d-11e3-9f3e-9f1f55a67763.png)

Note: Error window title specifies for incorrect csk password

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042 
win 8 2012
win 7 2010
uses the same Error window in 
#459
