### ISSUE TITLE
[1.01.0027] Signing Registration Window allows BlackBerry with trailing spaces to be inputted as Author

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#376]
Refer to #322 
It is a reserved name in the Author Name Field what needs to be verified before being able to continue.

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0041 win 7 2010, win 8 2012
