### ISSUE TITLE
[1.01.0027] Signing Registration Window author Blackbery error use cannot not can not

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#377]
can not (v)
Use "cannot" or "can't" instead.
You cannot file email messages.

![cannoterrormessage](https://f.cloud.github.com/assets/1478549/1044765/b24b71c0-1017-11e3-951f-1b49a021273b.png)

Refer: BlackBerry Style Guide for Product Information

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042 
Win 7 2010
Win 8 2012
