### ISSUE TITLE
[1.01.0027] able to unregister BB token with no api level installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#380]
preq: have no api level installed, have a bb id token
1. from Blackberry > Signing click Unregister 

Expected:
able to unregister bb id token.

Current behaviour:
![bbtokenunregisternoapilevel](https://f.cloud.github.com/assets/1478549/1050320/bb540160-10b7-11e3-8c77-66d518d274b0.png)

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042
win 7 2010
win 8 2012
user is able to unregister bbid tokens with no error
