### ISSUE TITLE
[1.01.0027] able to crash vs if attach to process is setup with no api level

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#381]
prequisite: no api levels, setup device in BlackBerry Settings
1. Debug > Attach to process
2. Select Blackberry Transport and Device Ip qualifier

Current Behaviour:
Error occurs VS crashes

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
reproducible on 1.01.0041 win 8 vs 2012

**Comment by zadmarbella** [comment]
Linking to issue #452

**Comment by guarnold** [comment]
Updated fix available in build v1.01.0042.

**Comment by zadmarbella** [comment]
reproducible 1.01.0042 on win 7 vs 2010

**Comment by guarnold** [comment]
The following entry in the Windows Registry is not been cleaned when user uninstalls all of the API levels:

key name - HKEY_CURRENT_USER\Software\BlackBerry\BlackBerryVSPlugin
Entry - NDKHostPath

As a consequence, the plugin thinks that there is an API level and try to connect to the device/simulator, causing the crash.

The workaround would be to uninstall the plugin too, if the user wants to uninstall all the API levels.

**Comment by guarnold** [comment]
As this issue only happens when the user uninstall all the API levels and them he tries to attach to a process without any new API level installed, I recommend closing this issue as I opened another one that is more specific: #460
