### ISSUE TITLE
BlackBerry Settings and Debug Token dialog boxes should both get the device IP from Registry.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#383]
The debug token gets the IP address from the Registry (169.254.0.1 is set as default during plug-in installation). So, if the user didn't update the BB settings and tries to add a debug token, the message "Missing Device Password" is presented.

However, if he opens the BlackBerry Settings menu, there is no Device IP set, causing the idea that the previous message was wrong. This issue happens because the BB Settings dialog gets the Device IP from an internal variable (that was not already set) and not from the Registry.

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verification failed 1.01.042
win 7 2010
win 8 2012
this workflow might need to be revisited. Do we want a default value for IP address for debug token generation?

**Comment by allee** [comment]
est 1day.

**Comment by guarnold** [comment]
The device IP has as the default value 169.254.0.1
However, it was not being presented in the Settings window after installing the plug-in. After this fix, it is presented.

**Comment by pvallabhaneni** [comment]
Verified in Win 7 32/64 bit using 2.0.0018 plugin. when debug token dialog is opened without  settings set by user after installing the plugin, "Missing device password" dialog is shown.When settings dialog is opened IP address is set to 169.254.0.1 and password field set to empty.
