### ISSUE TITLE
[1.01.0027] unable to access debug token if there is no api level

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#384]
preq; no api level installed, set blackberry device in settings
1. Access Blackberry > Debug Tokens

Current behaviour:
user gets unclear error notification 
![noapilevelinstalledadddebugtoken](https://f.cloud.github.com/assets/1478549/1051248/a5fee4e6-10c7-11e3-8864-76e64659cf3b.png)

**Comment by guarnold** [comment]
Fix available in build 1.01.0029-3

**Comment by zadmarbella** [comment]
verified 1.01.0042 
win 7 2010
win 8 2012
user is able to access debug token window with no notification
