### ISSUE TITLE
[1.01.0031] project properties fails to open if there is no api level installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#400]
vs2012 win8

using fallingblocks attempt to access project properties.

Current Behaviour:
![cantaccessprojectproperties](https://f.cloud.github.com/assets/1478549/1081909/adfda842-157e-11e3-9d48-9d505e4081de.png)

workaround: install api level

**Comment by dbrgss** [comment]
Fixed in 1.01.0032

**Comment by zadmarbella** [comment]
This issue hasn't been verified reopening.

**Comment by zadmarbella** [comment]
1.01.0041 
reproducible win 8 vs2012 
win 7 2010 property page only contains empty framework reference. 
Also intermittent issues with opening projects seems to occur.

**Comment by srinivas4912** [comment]
The issue has fixed and verified without installing VS plugin as well as API level on Win8.1 and Win7 64.
