### ISSUE TITLE
[1.01.0031] installing or uninstalling plugin doesn't update API level drop down list

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#401]
preq:  add jre path in environment variables see #321
1. install/uninstall api level from Update Manager

Current Behaviour:
Drop down menu doesn't update once install/uninstall completes

Workaround:
close the Settings and open the settings again

**Comment by dbrgss** [comment]
Fixed in 1.01.0032

**Comment by zadmarbella** [comment]
verified 1.01.0042  win 8 vs 2012 win 7 vs2010
