### ISSUE TITLE
Continuing debug (F5, play button) causes VS to interrupt the debug process and to rebuild/redeploy the app

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#402]
Continue debug does not work in both vs2010 and vs2012.
Steps:
1.Launch one project for debugging on Simulator or device.
2.Add a breakpoint in the project and debug and start debugging
3. It hits the breakpoint
4.Continue to debug by clicking menu(continue) or pressing "F5".
Expected results:
1. It will continue the debug process.
Actual results:
In vs2010, it will start the "build and deploy" process again in the debug session. There are output show in the "output" window suggests another build session started.
In VS2012 it will raise a message box and ask if you want to stop debugging.

**Comment by guarnold** [comment]
Fixed.

**Comment by guarnold** [comment]
Fix available in build 1.01.0032-3

**Comment by zadmarbella** [comment]
verified 1.01.0041 win 7 vs 2010 win 8 vs 2012
