### ISSUE TITLE
[1.01.0031] update manager can sometimes throw error notifications

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#403]
preq: add jre path in environment variables see #321 
1. from Blackberry > Settings > click Get More...
2. Select click install on an API level
3. Close the window
4. Click Get More...
5. Attempt to install
6. Select Click another install Api level

current behaviour: an error can appear 
![unknownupdatemanagererror](https://f.cloud.github.com/assets/1478549/1082555/d0af08fc-158a-11e3-9a51-90340402f8db.png)

Note: it is unclear on how the user should resolve these kinds of errors that come from the eclipsec

Root Cause: Looks to be caused by trying to install Beta 1 with the update manager.

**Comment by allee** [comment]
est .5 days
