### ISSUE TITLE
[1.01.0032] Runtime Update Manager dialog has typos

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#411]
Making p2 for visibility. This is the first thing the user sees when debugging to device with missing runtime.

![runtimeupdatemanagernotification](https://f.cloud.github.com/assets/1478549/1089816/c30a420a-164a-11e3-93ff-672dd63ec44e.png)

**Comment by dbrgss** [comment]
This is how it was designed and it's how it works in Momentics.

**Comment by zadmarbella** [comment]
device is spelled deice

**Comment by AndrewKnox** [comment]
Is this message generated by the VS plug-in or by the update manager tool?

**Comment by dbrgss** [comment]
Fixed 1.01.0033

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 in these platforms:
a.  Windows 7-64 VS2010
d.  Windows 8-64 VS2012

**Comment by zadmarbella** [comment]
Closing - updated tes case

**Comment by zadmarbella** [comment]
regressed 1.01.0035

**Comment by zadmarbella** [comment]
https://github.com/blackberry/VSPlugin/blob/next/src/VSNDK.Package/UpdateManager/Model/UpdateManagerData.cs#L348

It's still in the code and in the 1.01.0042 and it regressed.
Last time it was modified was 9 days ago for a Simulator Fix.

**Comment by guarnold** [comment]
Fixed in latest update

**Comment by allee** [comment]
.5 days
