### ISSUE TITLE
[1.01.0031] debug token creation can fail quietly if user doesn't navigate to a website 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#412]
possible network issue with machine that can cause it. 
but debug token creation fails with no messages or indicator what is to be done.

Workaround: looks to be to navigate to a website with the browser.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by guarnold** [comment]
Can you still reproduce this issue? I know that it is not easy to reproduce it...
Maybe we should KIL this one.

**Comment by dbrgss** [comment]
No I haven't seen it for a while.   We should maybe look to verify a debug creation on return from the command.   IE when we get a exit event from the process we should check to make sure that a debug was created.. An display an error if it wasn't.

**Comment by srinivas4912** [comment]
Pre-req: Unregister the signing keys

Steps to Reproduce:
1. Go to BlackBerry > Signing 
2. Click on Register and Unplug the network cable 

Actual Result: It is prompted to "Sign in to create and download your BlackBerry ID token" dialog and it is  an empty window.
![image](https://f.cloud.github.com/assets/5992406/2109605/44e04564-8ff3-11e3-8577-2cc66a17f71d.png)
Debug token creation fails with no error message.

Workaround using VS2013 plugin from 2.0.0018 on Win8.1 .

**Comment by hkopparru** [comment]
Tested with 3.0.0001 plugin, issue is not reproducible.

if you unplug the network cable then Click on create Token button its showing the error message " Failed to obtain the BlackBerry ID token. Please check your internet connection".

![capture2](https://cloud.githubusercontent.com/assets/5992379/5836404/48845470-a19b-11e4-9622-812d594cb1a0.JPG)

closing this issue.
