### ISSUE TITLE
[1.01.0032] Runtime Update Manager dialog downloads api level simulator when it should launch to running simulator

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#413]
preq: get a simulator with a api level from the dev site https://developer.blackberry.com/devzone/develop/simulator/simulator_installing.html
and install it. (as of 2013-09-05 it is 10.2.0x.1443)
1. run the simulator 
2. attempt to launch a project for debugging on the simulator

Current Behaviour:
It will prompt the user to download the api level simulator and the user can not proceed. unable to launch project to simulator

**Comment by dbrgss** [comment]
Included in v1.01.0036

**Comment by zadmarbella** [comment]
verified 1.01.0041 
win 8 2012 
win 7 2010 
simulator 10.2.0.1725
