### ISSUE TITLE
[1.01.0032] bar-descriptor editor icon and splash screen thumbnail image is missing

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#414]
1. open bar-descriptor in bar-descriptor editor
2. add an icon or splash image. 

Current behaviour:
thumbnail is missing 

note: this is a regression. labeling p2 for visibility

**Comment by dbrgss** [comment]
Fixed in 1.01.0033

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 in these platforms:
a.  Windows 7-64 VS2010
d.  Windows 8-64 VS2012

**Comment by zadmarbella** [comment]
closing
