### ISSUE TITLE
[1.01.0032] Project properties Configuration for Simulator is missing Exclude Directories

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#415]
Preq: have a project open
1. Access project properties
2. From the Drop down switch Platform to BlackberrySimulator
3. Navigate to Configuration Properties > VC++ Directories

Current Behaviour:
Exclude Directories option is missing from the list of available options

**Comment by guarnold** [comment]
Verified in bundle 152 – v1.01.0033 in these platforms:
a.  Windows 7-64 VS2010
d.  Windows 8-64 VS2012

**Comment by zadmarbella** [comment]
closing test case added

**Comment by pvallabhaneni** [comment]
Verified on Win 7 64bit using 2.0.0022 plugin / VS2012 following above steps. 

Exclude Directories option is missing from the list of available options, when configuration manager platform is changed to simulator.

Re-opening the issue. Removing "Completed" and "Verification Passed" tags. Re-assigning to "triage"

**Comment by dbrgss** [comment]
Please re-verify...  Tried it hear and the Exclude Directories do appear.

**Comment by pvallabhaneni** [comment]
As per the discussoin with Zad, Value of the option is not visible which is platform dependent. The VC++ Directories option is visible. It seems working fine as per the functionality.
