### ISSUE TITLE
[1.01.0032] no notification of building/deploying for debugging if output window is not visible

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#416]
preq: have the output window not visible.

1 click start button on toolbar

current behaviour:
VS is not responding since it is building in the background.

expected:
notification that visual studio is busy.

workaround:
have output window visible

**Comment by dbrgss** [comment]
Estimate: 1 days

**Comment by dbrgss** [comment]
There is a build indicator in the bottom tray of Visual Studio...
