### ISSUE TITLE
[1.01.0032] Accessing Modules Window while debugging crashes visual studio

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#417]
Steps to reproduce:

1, Launch a project to debug.

2, Hit a breakpoint.

3, Open the “Debug”-->”Windows”-->"Modules".

Expected result:

Modules will show on in "modules" window.

Actual result:

Visual Studio crashed.

**Comment by guarnold** [comment]
Fixed for both VS2010 and VS2012

**Comment by guarnold** [comment]
Available in build v1.01.0033-2

**Comment by zadmarbella** [comment]
verified on 1.01.0041 win 7 2010 and win8 64 2012
