### ISSUE TITLE
[1.01.0032] user is able to deploy project from the menu and project context menu

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#418]
preq; have a project, and device setup.
Step to reproduce:
1. deploy to device from the project menu or project context menu
Build > Deploy
Project context menu > Deploy 

Current Behaviour: project fails to deploy.

**Comment by guarnold** [comment]
Fix available in build v1.01.0035.

**Comment by zadmarbella** [comment]
verified on 1.01.0041 win 7 vs 2010 win 8 vs 2012
