### ISSUE TITLE
[1.01.0032] able to start without debugging

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#419]
It is unclear what the support for this functionality is. Further investigation is needed.

**Comment by zadmarbella** [comment]
[1.01.0043] win 8 2012 throws an error when Debug > Start without debugging

![failedtodebugfromprojectcontext](https://f.cloud.github.com/assets/1478549/1255058/9f4a779c-2b7e-11e3-9924-786a9cc622ef.png)

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by hkopparru** [comment]
tested with [3.0.0005] plugin and the issue is not reproducing and closing this issue now.
