### ISSUE TITLE
[1.01.0033] API level of the same version installed not using the vsplugin can cause double entries in API Levels

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#424]
Install Cascades Momentics 10.2 api level
Install VSPlugin 10.2 api level

From Blackberry > Settings > Api Level Drop down

Current behaviour:
installing the same version from other BB IDEs can cause double entry.
Note: that 10.2 doesn't include version numbers.

Workaround:
rename the vsplugin one in the qconfig folder to be able to tell them apart.

![apileveldoubleentry](https://f.cloud.github.com/assets/1478549/1109975/e730baae-198a-11e3-8bc4-e782e8914ef0.png)

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by dbrgss** [comment]
Can no longer see API Levels installed by Momentics..
