### ISSUE TITLE
[1.01.0033] unable to uninstall if user installs the same api levels one from cascades and the other using vsplugin

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#426]
preq: install 10.2 api level from cascades, install 10.2 using the plugin 
or the same api level on both tools
1. from Blackberry > Settings > Get More..
2. Click Uninstall on the  Available 10.2 api level

Current Behaviour:
User is notified to uninstall api level through Windows Add /Remove programs utility.
Note: this doesn't work. deleting the cascades IDE doesn't still gives the same error.
The error might be relevant to a Playbook SDK install but not to a Cascades install.
![wontresolveifinstalledapilevelfromcascades](https://f.cloud.github.com/assets/1478549/1110959/b23fd358-199d-11e3-8f90-3dbd8edd324f.png)

Workaround: uninstall the api level from momentics.
then the user can uninstall the vsplugin api level.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by dbrgss** [comment]
No longer can see API Levels installed by Momentics...
