### ISSUE TITLE
[1.01.0033] api levels installed not using the update manager can intermittently vanish from the available list

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#431]
win7 2010 and win8 2012.

preq: have a playbook sdk or api level from momentics installed
1. From Blackberry > Setting > Click Get More..

Current Behaviour:
the api level vanishes from the list of Available.

Expected:
List item appears

Workaround seems to be to close and open the Settings Dialog? or close the vs and open it again. it is not clear.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by dbrgss** [comment]
Plugin no longer accesses API levels from momentics.
