### ISSUE TITLE
Change the focus of error messages from Update Manager.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#432]
In case it happens an error while installing a new API level, that error message is displayed behind the Update Manager window. When that happens, the user will see that message only after closing the Update Manager window, or moving it to a different location.
That error window should be focused.

To reproduce an error, try to install the BlackBerry Native SDK 10.2 Beta 1.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by pvallabhaneni** [comment]
Verified in the following scenario.
1. Installed VS 2012 and v2.0.0022 plugin.
2. Open Blackberry->Get More->Get Simulators
3. Install a simulator.
4. Click close when the simulator is being installed.
5. "Cancel Installation?" dialog appears.Click "Yes"

Simulators dialog is closed and Error message from Update Manager is shown above all the existing dialogs (Settings,API level).
