### ISSUE TITLE
[1.01.0033] removing a when hit condition while debugging stops visual studio 2010 from responding

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#434]
1. Launch project for debuggint 
2. Set a When Hit condition 
3. Remove it

Current Behaviour:
VS2010 stops responding

**Comment by guarnold** [comment]
This feature is not currently supported for both VS 2010 and 2012. However, it does not stop/crash VS 2012. The same should happen in VS 2010. Investigating...

**Comment by guarnold** [comment]
Fix available in build v1.01.0035.

**Comment by zadmarbella** [comment]
verified on win 8 2012 win 7 2010
updated behaviour for 2010 https://github.com/blackberry/VSPlugin/issues/441#issuecomment-25012268
2012 looks to be ok
