### ISSUE TITLE
[1.01.0033] attach to process on vs2012 pops up a dialog for Remote Debugger Connections

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#435]
1 Debug > Attach to process
2 Select transport Blackberry Qualifier Device: < IP >
3. Click Find

Current behaviour a Remote Debugger Connections dialog appears

![remodebeguggerconnection](https://f.cloud.github.com/assets/1478549/1125649/4722a1c6-1b15-11e3-95c7-d12006fba07d.png)

Workaround: Closing the window doesn't seem to harm the attach to process
Looks to be a feature added to vs2012 it is not used by vsplugin attach to process.

**Comment by guarnold** [comment]
This feature "Find" is available only in VS2012 and is not supported at this moment.

We could create a task to:
1 - present the Device and Simulator options, if they are set;
2 - or disable the buttons that have no functionality in our plugin.

**Comment by allee** [comment]
new task created see issue #512
