### ISSUE TITLE
[1.01.0033] No transport "Blackberry" in "Attach process" dialog on 32bit OS

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#437]
1. Debug -> Attach To Process
2. Open Transport Dropdown
   Expected Result:
3. Transport Blackberry exists
   Actual Result:
4. Transport Blackberry does not exist.
   VS2010 32bit:   cannot see BlackBerry Transport

**Comment by dbrgss** [comment]
Included in v1.01.0040

**Comment by zadmarbella** [comment]
verified on 1.01.0042 win 32 looks to attach to process fine.
