### ISSUE TITLE
"Missing Device IP" window is presented when deploying an app into the Simulator, without a device set.

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#440]

**Comment by zadmarbella** [comment]
blocked #535

**Comment by guarnold** [comment]
Issue 535 is not reproducible. Please verify.

**Comment by pvallabhaneni** [comment]
Unable to debug a project on simulator with device IP and password not set i  Blackberry->Settings dialog.

**Comment by zadmarbella** [comment]
@pvallabhaneni unclear what version or os this issue failed on. please clarify.

**Comment by pvallabhaneni** [comment]
Able to reproduce in [2.0.0015]. No device is connected and simulator is running in the system. No device IP is set in settings and Simulator IP address is given in settings. Issue is reproducing. 

Similar issue is seen when debug token dialog is opened.

**Comment by guarnold** [comment]
Could not reproduce this issue using VS2013 in Win 7 64 bits environment. Could you provide more details about the environment?

Make sure that the BlackBerrySimulator configuration is selected.

About the debug token dialog, this behavior is expected because we use debug tokens only in devices, not in simulators. So, when you open the debug token dialog, the first thing the plugin does is to check for the device settings.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 64 bit using 2.0.0018 plugin with 10.2.1.1925 simulator and "Missing Device IP" dialog is not shown.
