### ISSUE TITLE
"When Hit" feature does not work as expected

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#441]
After creating a breakpoint and right-clicking over the breakpoint symbol, there is a feature called "When Hit", that is supposed to print messages or run macros everytime this breakpoint is hit. The user can also select if he wants the program to break or not in this breakpoint.

This feature was not implemented in the VS plugin yet. However, It does not cause any issue in case the user decides to use it, but it will not work as expected. Some things can happen, like:
- Variables cannot be printed or evaluated;
- The program can break in this breakpoint even if the "Continue execution" is selected;

Related to issue #434

**Comment by zadmarbella** [comment]
Current behaviou on vs2010: adding and removing when hit breakpoint becomes inconsistent

**Comment by allee** [comment]
Closing as there is now a task for this see #511
