### ISSUE TITLE
[1.01.0035] turning on vs with no internet connection floods the user with error messages

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#443]
1. Unplug network connection
2. Turn on VS

Current Behaviour:
user is flooded with these messages 
![nointernetonvsstartup](https://f.cloud.github.com/assets/1478549/1181150/b87358d0-2203-11e3-8ee4-5b7189a84849.png)

Workaround:
Click ok through all of them

Note: the API level dialog doesn't

**Comment by dbrgss** [comment]
Included in 1.01.0040

**Comment by zadmarbella** [comment]
verified 1.01.0042 win 7 vs2010 win 8 vs2012
