### ISSUE TITLE
[1.01.0040] project fails to launch when deploying in Release Configuration and with Platform set to Blackberry

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#446]
1 set Solution Configuration to Release
2 set Platform to Blackberry 
3. Click Play

Current Behaviour:
project fails to fully launch on device 

Workaround: Close the app on device and reopen it. 

Notes:
Looks like debugger is trying to attach.
Possible issue could also extend to simulator deploys using the same setting.

**Comment by guarnold** [comment]
Fix available in build v1.01.0041

**Comment by zadmarbella** [comment]
verified on 1.01.0041 win 7 vs 2010 win 8 2012
