### ISSUE TITLE
[1.01.0040] unable to save modification bar-descriptor editor on win 7 32 vs2010 using for the first time

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#447]
1. open bar-descriptor in editor
2. attempt to edit values

current behaviour:
unable to save modifications

workaround:
looks like editing the file by accessing the bar-descritor view code menu and saving gets it to work again.
doesn't look to completely resolve the issue having saving issues with the editor afterwards.

**Comment by zadmarbella** [comment]
[1.01.0043] it looks to have been reproduced on a win 8 with vs2012. unable to reproduce it on other machines. The issue could be intermittent.

**Comment by guarnold** [comment]
Please, verify if this issue is reproducible in VS 2012 / 2013.

**Comment by zadmarbella** [comment]
blocked by #525

**Comment by guarnold** [comment]
Issue 525 was fixed.

**Comment by srinivas4912** [comment]
The issue has fixed and verified using VS2012/VS2013 plugin from build 2.0.0018 on Win8.1 and Win7 (64&32).
