### ISSUE TITLE
b113 - user needs to be able to exclude folders from their build

### ISSUE THREAD

**Issue by mattcostanzo** [blackberry/VSPlugin#45]
Limitation discovered when attempting to build cocos2d from the vs2010 Solution.
One needs to be able to exclude the win32 folder and add in the blackberry build configuration. Then verify that the blackberry folder is excluded in their win32 build.

![efa01ed2-ab80-11e2-87ee-5275946b0db4](https://f.cloud.github.com/assets/4265822/450873/8ccef57a-b29d-11e2-9090-3f3f4e4fc179.png)

**Comment by zadmarbella** [comment]
reopened https://github.com/blackberry/VSPlugin/issues/11#issuecomment-19350425 it doesn't seem to work as expected.

**Comment by mattcostanzo** [comment]
Est 1 day

**Comment by guarnold** [comment]
It might be completed after fixing issue #219. To be available in the next build.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 64 bit using VS2012 and v2.0.0022 plugin. The properties set in "Blackberry" configuration is not visible in Win32 environment and viceversa.

Verification passed.
