### ISSUE TITLE
[1.01.0041] downloading api level/runtime/simulator may become slow and user is unable to resume at a later time

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#450]
The current update manager implementation prevents the user from cancelling the download as it is happening. This was done due to unknown behaviour if downloads are cancelled mid-way through an installation and (at the time) no indication of download status. However, in some cases if internet connection can becomes slow/unstable. Being able to pause and resume at a later time when the connection is more stable might resolve the issue.

**Comment by dbrgss** [comment]
Estimate: 2 days

**Comment by allee** [comment]
need to be able to cancel and recover.
Maybe able to do this using the command utility, will need help from the Tooling team (David Cummings)

**Comment by guarnold** [comment]
User is able to cancel the download process and restart it later. However, he won't be able to debug without completing the download and installation tasks.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 and Win 8.1 using 2.0.0018 plugin. User is able to cancel the download of API level, Simulator and Runtime. User can restart it again and download. User Can debug only after completing the downloading of API level and Runtime.
