### ISSUE TITLE
[1.01.0041] Stepping through code and adding a breakpoint while in Break All debugging hangs 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#451]
have no breakpoints in the project
1. launch for debugging
2. break all 
3. attempt to step through the code step in/out/over
4. Add a breakpoint

Current Behaviour:
environment hangs

**Comment by guarnold** [comment]
Fix available in build v1.01.0042.

**Comment by zadmarbella** [comment]
verified 1.01.0042 win 7 vs 2010 win 8 vs 2012
