### ISSUE TITLE
[1.01.0041] Attach to process can intermittently get to a state where it consistently hangs environment

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#452]
Note: unclear how to reproduce. Appeared on vs2010 on win 7 64bit

Preq: with an open project
1. Debug > Attach To Process

Current behaviour:
unable to access attach to process dialog and it hangs the environment.

Workaround: uninstall and reinstall the plugin

**Comment by guarnold** [comment]
Could not reproduce this issue. If you cannot open the Transport to select BlackBerry, it is probably an error in the registry entry related to Port Suppliers. That's why uninstalling and re-installing the plugin solves it.

**Comment by guarnold** [comment]
It might be related to issue #460, as the workaround is to uninstall and reinstall the plugin (which updates the registry correctly).

I would recommend lowering it to P3 to keep an eye in the future, after fixing issue 460.

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by guarnold** [comment]
Could not reproduce it in VS 2013.

**Comment by srinivas4912** [comment]
This issue is not reproduced, verified using VS2013/12 plugin from build 2.0.0022 on Win8.1 and Win7 64 bit.
