### ISSUE TITLE
[1.01.0041] accessing Settings Get More API levels with inconsistent internet connection can crash

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#453]
Note: looks to only happen when user gets this error
![inconsistentinternetplugin](https://f.cloud.github.com/assets/1478549/1201100/fc99c628-252f-11e3-8fe6-20528317522f.png)

And trying to click close button or cancel the settings window can crash visual studio

It looks to be reproducible using [2.0.0001] :

unplug network connection
turn on vs (used vs2012)
plug in network connection wait for it to be available
go to Blackberry > Settings > Click Get More

Behaviour: the window appears from above and environment will crash

Note:
Doing the same steps but instead of accessing Get More try to deploy the project
will always ask the user to build again and the debugger fails to attach. but doesn't crash.

workaround is to make sure user has internet connection before they turn on VS.

**Comment by zadmarbella** [comment]
1.01.0042 looks to be more reproducible when restoring connection while in visual studio and accessing Blackberry > Settings > Get More

**Comment by dbrgss** [comment]
Need to know the scenario that this occurs.   If you try to access the Get More screen without an internet connection it shouldn't allow you to enter the screen... It will give you a internet connection not available error.

Dave

**Comment by dbrgss** [comment]
Check to see what happens when you click Get More when the machine is in the process of reconnecting.

**Comment by russellandrade** [comment]
Lets document

**Comment by PamC** [comment]
I have it in my release notes spreadsheet now.
Do we want this in the documentation as well? If so, suggest that a comment go on this page along with the sentence that starts ‘Before you can start….”

Suggest:
Before you can start developing for BlackBerry 10 OS, there are a few things that you need to do. You must have a stable internet connection or some functions may not work as expected or may crash.

I think I can put it in a green box or a pink box. Any preference?

Cheers,
Pam

---

Pam Colquhoun

Technical Writer
Developer Documentation

Office: (613) 595-3845 x13845

BlackBerry: (613) 290-5049

PIN: 2FFFAEF5

[cid:image003.jpg@01CECF2E.BD2559F0]

**Comment by allee** [comment]
Refer to #489

**Comment by dbrgss** [comment]
Should be retested as the logic behind this screen has been refactored..  This issue should not occur.

**Comment by srinivas4912** [comment]
Preq: Install VS2013/VS2012 plug-in from Bundle 195[2.0.0018] on Win7 64 and 32 bit using 10.2

Steps to reproduce:
1. From Blackberry > Settings > Get More.
2. Select api level to install from "Available" list.
3. Installation is in progress.
4. Unplug Network cable.
5. Observed that After 5 min.
![image](https://f.cloud.github.com/assets/5992406/2052697/b7a6c7c0-8a9a-11e3-98fe-df069ddc0cf8.png)

Actual Result: When clicked on "close" button
![image](https://f.cloud.github.com/assets/5992406/2052745/507bd8fa-8a9b-11e3-8faa-59d2a69a38b0.png)

**Comment by guarnold** [comment]
Fix will be available in the next build.

**Comment by pvallabhaneni** [comment]
Visual Studio is crashing in the following scenario.
1. Unplug network connection
2. Turn on vs (used vs2012) on Win 7 64 bit using v2.0.0021
3. Select Blackberry->Settings->GetMore.
Following error message is shown.

![internet connection error](https://f.cloud.github.com/assets/5992422/2124590/f0f1a79e-9241-11e3-8331-7684b52231fe.png)
1. click OK button. Error message from visual studio is shown.
2. Click OK. Observe that settings dialog is shown behind visual studio.
3. Go to settings dialog
4. Click on Get More... Above error message is shown 
5. Close the error message.

Visual Studio is crashing.

![crash](https://f.cloud.github.com/assets/5992422/2124827/6457feaa-9246-11e3-8232-089774e043e4.png)

**Comment by guarnold** [comment]
Fix available in build version 2.0.0022.

**Comment by srinivas4912** [comment]
Verified and found as fixed using VS2013/12 from build 2.0.0022 on Win8.1/7 64 bit.
