### ISSUE TITLE
[1.01.0041] Escape key shortcut doesn't work to close the API Level and Get Simulator Dialog from Settings Get More

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#455]
Opening the Settings > Get More > Get Simulators Dialog
attempt to close using Escape Key 

Get Simulators, Simulator window won't close
Get More API level window won't close

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by srinivas4912** [comment]
Issue is still reproduced while using plugin VS2012/VS2013 from bundle 195[2.0.0018] on Win7/8.1

**Comment by dbrgss** [comment]
This is not an issue as this feature was never implemented.   Creating new Task to cover this.   Recommend closing of this issue.

**Comment by guarnold** [comment]
Task created: #624
