### ISSUE TITLE
[1.01.0042] update manager and simulator download window is always on top of the desktop

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#458]
see #284 
Try to use other applications while the update manager window and simulator download windows are open 
Blackberry > Settting > Get More > Get Simulators

Current Behaviour
Other applications are obstructed by the windows

Workaround:
hide it from the desktop while it is downloading

**Comment by guarnold** [comment]
This issue is related to issue #432, that was already fixed.

Fix will be available in the next build.

**Comment by pvallabhaneni** [comment]
Verified the issue in Win 7 64bit using VS2012 and v2.0.0022 plugin.
Other application are not obstructed by Simulator and Update Manger windows.
Verification Passed. Closing the issue.
