### ISSUE TITLE
[1.01.0042] incorrect bbid token password debug token prompt still mentions csk password

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#459]
see #374 
We still use CSK password.
![errorcskexpectedbbidtoken](https://f.cloud.github.com/assets/1478549/1205632/32adf1a0-2588-11e3-9d63-58b1159f9ce0.png)

**Comment by guarnold** [comment]
CSK password is correct too. The token filename is bbidtoken.csk. It is a CSK file.

**Comment by zadmarbella** [comment]
closing based on comment.
