### ISSUE TITLE
[1.01.0042] able to crash vs if attach to process is setup after uninstalling all of the api levels

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#460]
prequisite: uninstall all of the api levels, setup device in BlackBerry Settings 
This issue only happens after uninstalling all of the api levels. It does not happen if you installed a new version of the VS plugin and have no api level installed. You have to uninstall the api levels.

Debug > Attach to process
Select Blackberry Transport and Device Ip qualifier

Current Behaviour:
Error occurs VS crashes

**Comment by guarnold** [comment]
The following entry in the Windows Registry is not been cleaned when user uninstalls all of the API levels:

key name - HKEY_CURRENT_USER\Software\BlackBerry\BlackBerryVSPlugin
Entry - NDKHostPath

As a consequence, the plugin thinks that there is an API level and try to connect to the device/simulator, causing the crash.

The workaround would be to uninstall the plugin too, if the user wants to uninstall all the API levels.

**Comment by guarnold** [comment]
This issue only happens when the user uninstall all the API levels and them he tries to attach to a process without any new API level installed
That is not a common behavior. No one would uninstall all the API levels and keep the plug-in.

**Comment by allee** [comment]
Refer #489

**Comment by srinivas4912** [comment]
It is fixed and not reproduced because the blackberry plug-in for VS requires at least one API target to function correctly and last API level target is prohibited to uninstall.
