### ISSUE TITLE
[1.01.0042] able to create blackberry configuration with no api levels installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#461]
If there is no api level one can still create a Blackberry Configuration.

This leads to behaviour like projects not having bar-descriptor files and possibly other unknown settings issues. It's unclear what happens to the project after one installs an api level.

**Comment by dbrgss** [comment]
This is not an issue.   It's true it won't create a bar-descriptor.xml without an API Level... but as soon as you create the API Level it DOES create the bar-descriptor.xml.. and works fine.   Adding API Levels does not affect the project in any way.  If there is a bug here its the fact that the bar-descriptor.xml is not being added in spite of no API Level.  That really shouldn't matter.   I would suggest wither modifying this issue to reflect this... or close and re-open a new issue.  That being said this not adding bar-descriptor bug is only a P3.

**Comment by dbrgss** [comment]
Need to look into methods to prevent the user from NOT having at least one API level.  (New Feature)

**Comment by dbrgss** [comment]
User Story #506 
Task #507

**Comment by allee** [comment]
#489 See

**Comment by dbrgss** [comment]
Feature to have at least one API finished.

**Comment by pvallabhaneni** [comment]
As per #506, atleas one API level need to be downloaded to open a project. So by the time of creating the blackberry configuration, atleast one API level will be present. So, unable to create blackberry configuration with no API level installed. Verified using 2.0.0022 on win7 64 bit and found as fixed.
