### ISSUE TITLE
[1.01.0042] user is able to go through uninstall process while simulator is on

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#463]
preq: have simulator on installed by the simulators dialog on
1 from Blackberry > Settings > Get More > Get Simulators
2 view the Installed section 
3 Click uninstall on a simulator

Current Behaviour:
user is able to go through uninstall process

Note: unclear on impact of debugging on the sim afterwards

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by guarnold** [comment]
Available in build 2.0.0018 (bundle195).

**Comment by srinivas4912** [comment]
It is verified using VS2013/12 plugin from 2.0.0018 on win 8.1 and Win7 64 bit and found as fixed.
user is not able to go through uninstall process while simulator is on.
