### ISSUE TITLE
[1.01.0042] user sometimes gets random errors

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#465]
Over the course of using the plugin one can sometimes get various errors that appear randomly. Unable to reproduce consistently and unknown impact. Some looks to be Update Manager Related.

![unknownerror001](https://f.cloud.github.com/assets/1478549/1219944/a790a368-26d3-11e3-97f9-b1d1fba3b503.png)
![unknownerror002](https://f.cloud.github.com/assets/1478549/1219945/a8ea699c-26d3-11e3-86ac-25bc19efd6a1.png)
![unknownerror003](https://f.cloud.github.com/assets/1478549/1219946/aa50a8e6-26d3-11e3-86bc-ef38a014e556.png)
![unknownerror](https://f.cloud.github.com/assets/1478549/1219949/ac3ac984-26d3-11e3-8c45-ce307be44b12.png)

**Comment by zadmarbella** [comment]
[1.01.0044] ran into more 
![unknownerror005](https://f.cloud.github.com/assets/1478549/1263406/4520ca70-2c4e-11e3-88f3-5394e6bce172.png)

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by hkopparru** [comment]
tested with all latest 3.0 plugins on VS 2013 and as of now we haven't encountered issues like this. we will wait for some more time to reproduce these issues.

**Comment by hkopparru** [comment]
issue is not reproducing. closing this issue now.
