### ISSUE TITLE
[1.01.0043] unable to input spaces at the end of the Description text area in the bar-descriptor editor in vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#468]
1. Go open the bar descriptor editor for a project
2. to tot he end of the line
3. attempt to add a space

Current Behaviour:
unable to input spaces

workaround:
go one character back and start typing

**Comment by pvallabhaneni** [comment]
Verified the issue using 2.0.0022 plugin on Win 7 64 bit and found that spaces are added to description text and saved.Verified by closing the bar-descriptor.xml files and opening it again(spaces persist).
