### ISSUE TITLE
[1.01.0043] environment stops responding when hovering data tips vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#469]
1. launch project for debugging
2. hit a breakpoint
3. find variable(s) ie. function with pointer arguments
4. hover over them.

Current Behaviour:
environment stops responding and user has to close and restart

Note:
we are noticing errors in the gdb-ouput.logs not just around this issue.

**Comment by guarnold** [comment]
Fixed for both VS 2012 and 2010. It used to happen when the mouse pass over '{'.

**Comment by guarnold** [comment]
Available in build version 1.01.0044.

**Comment by zadmarbella** [comment]
verified 1.01.0044
hovering over data tips doesn't hang the environment
