### ISSUE TITLE
[1.01.0043] unable to debug from project context menu

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#471]
1. Right click project
2. Debug > Start new instance
3. Click yes to build project out of date dialog

Current Behaviour:
user is unable to debug.
![failedtodebugfromprojectcontext](https://f.cloud.github.com/assets/1478549/1255031/3784e980-2b7e-11e3-94b9-0df675c5a79b.png)

**Comment by guarnold** [comment]
This issue also happens in VS2010. However, the behavior is different:

VS opens a window stating that "this project is out of date", asking him to build it.
If he choose "yes" or "no", VS builds and deploys the app, but does not attach it to the debugger, i.e., the app is launched but it does not start the debugging session.

**Comment by zadmarbella** [comment]
[2.0.0004] verified fixed win 8.1 vs 2012
