### ISSUE TITLE
[1.01.0044] API Levels download dialog should not include 10.2 Beta 1

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#473]
Intalling the beta 1 will fail and will have an error.

![beta1available](https://f.cloud.github.com/assets/1478549/1262329/72ff8e56-2c3d-11e3-8e57-bcca34739972.png)

**Comment by zadmarbella** [comment]
[1.2.0001] win7 and win8 still reproducible

**Comment by pvallabhaneni** [comment]
Verified in Win 7 64 bit and Win 8 64 bit using 2.0.0018 plugin , 10.2.1.1925 runtime and 10.2.0.1155 API level and found as fixed.
