### ISSUE TITLE
[1.01.0044] environment stops responding when adding variables to parallel watch window 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#475]
1. debug a project
2. hit a breakpoint
3. add variable to parallel watch window
4. hit continue 

Current Behaviour:
environment stops responding user has to end task and restart

**Comment by guarnold** [comment]
Fix available in build v1.01.0045

**Comment by zadmarbella** [comment]
verified [1.01.0045] 
able to add variable in parallel watch doesn't look to hang vs2012 on win 8
