### ISSUE TITLE
[1.01.0044] project importing is able to import a project on top of another project 

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#476]
prerequisite a Blackberry Core Native Project
1. File > Add > New Project...
2. add a New Visual C++ > Empty Project in a solution
3. Provide a relevant name
4. click OK
5. from project contextual menu right click
6. Import BlackBerry Core Native Project
7. Browse for .project or .cproject and click Ok
8. Review Conversion log for errors
9. Click Ok
10. Do this again with another project (or the same project both yield the same behaviour)

Current behaviour:
An error window appears and the import summary dialog appears indicating that conversion is starting.

![importsameprojecttwice001](https://f.cloud.github.com/assets/1478549/1265172/b95eb2dc-2c6a-11e3-840c-f67b2307d5d9.png)

![importsameprojecttwice](https://f.cloud.github.com/assets/1478549/1265170/b64b8c8c-2c6a-11e3-9eee-bbfb4189785a.png)

**Comment by dbrgss** [comment]
Estimate: 0.5 days

**Comment by pvallabhaneni** [comment]
Verified the issue using 3.0.0015 plugin and no error message is shown. Closing the issue.
