### ISSUE TITLE
[1.01.0045] unable to open project properties if plugin is not installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#478]
win7 vs2010

using fallingblocks project and have no plugin installed
1. attempt to access project properties

Current behaviour:
user is unable to access project properties

possibly linked with:
#400

**Comment by dbrgss** [comment]
Need to force a default API Level.   

Estimate: 3 Days

**Comment by allee** [comment]
See #489

**Comment by guarnold** [comment]
Please, verify this issue happens in VS 2012 and 2013.

**Comment by zadmarbella** [comment]
[2.0.0004] verified vs 2012 on windows 8.1 and vs 2013 on windows 7
