### ISSUE TITLE
[1.01.0045] user is unable to edit project properties linker output file

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#479]
win 8 vs2012

Preq: vs plugin project   
1. from the project context menu access project Properties
2. Access General Output File from Configuration Properties > Linker > General
3. Modify output file
ie. $(OutDir)$(ProjectName)_$(Platform)_$(Configuration)$(targetExt) < using macros or user input
4. Attempt to build project

Current Behaviour:
if the linker output file is changed from $(LocalDebuggerCommand) project will have issues building

**Comment by guarnold** [comment]
Fix available in build v1.2.0001

**Comment by zadmarbella** [comment]
verified on 2.0.0001
