### ISSUE TITLE
[1.01.0045] unable to view thumbnails for icons and splash images on vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#480]
Note: in 2010 it looks to images automatically in the Project Resources folder and it adds an entry to the Assets Configuration in the bar descriptor.
1. Add icon or splash image to project

Current behaviour:
no thumbnail appears. user has to manually add new resource in project.

Marking as P2 due to behaviour differs from vs2010 and vs2012

**Comment by srinivas4912** [comment]
Verified using VS2013/VS2012 from Product version 2.0.0018 on Win8.1, Win7 (64&32) and found as fixed.
