### ISSUE TITLE
[1.01.0045] able to crash environment when alt+tabbing form the Debugger to launch with no item selected in vs2012

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#481]
1. from project properties
2. Configuration Properties > Debugging 
3. From the Debugger to launch keep on the empty selection
4. alt+tab

Current Behaviour:
the environment crashes

![debuggerlaunchnoitemselection](https://f.cloud.github.com/assets/1478549/1289993/f468d688-3029-11e3-8bfb-00917d34c223.png)

**Comment by allee** [comment]
Verified as fixed by Zad
