### ISSUE TITLE
[1.01.0045] unable to restore an empty debugging option in project properties

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#482]
1. from Project Properties Configuration Properties > Debugging 
2. Select an option
3. Click Apply
4. Try to select an empty option.

Current Behaviour:
There is no way to go back to an empty entry

Note: it is unclear what plugin supports in terms of debugger to launch
unclear what Configuration Debugging Properties impact on project.
A GDB option might be required with command options.

**Comment by dbrgss** [comment]
This was fixed earlier with the addition of the BlackBerry NDK Debugger default.

**Comment by zadmarbella** [comment]
[2.0.0001]  verified - Added a BlackBerry NDK Debugger option that projects will use
