### ISSUE TITLE
[1.01.0045] remove solution configuration for Simulator and Simulator-Release

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#483]
Projects should only launch on these Configuration Solutions
Debug - BlackBerry / BlackBerrySimulator
Release -  Blackberry / BlackberrySimulator

Options that are not needed/supported and will produced unexpected behaviour:
Simulator
Simulator-Debug

**Comment by guarnold** [comment]
The only available solution configurations for new projects are Debug and Release.

Probably you are using an old project that still contains those other ones. To remove then, you have to manually edit the project solution file (for example, FallingBlocks_001.sln), and remove the lines that contains the ones you don't need, like these ones:

```
    Simulator|BlackBerry = Simulator|BlackBerry
    Simulator|BlackBerrySimulator = Simulator|BlackBerrySimulator
    Simulator|Win32 = Simulator|Win32
    Simulator-Debug|BlackBerry = Simulator-Debug|BlackBerry
    Simulator-Debug|BlackBerrySimulator = Simulator-Debug|BlackBerrySimulator
    Simulator-Debug|Win32 = Simulator-Debug|Win32
```

**Comment by zadmarbella** [comment]
[1.2.0001] closing not an issue
