### ISSUE TITLE
b101 - unable to debug on playbook 1 and 2 R036

### ISSUE THREAD

**Issue by allee** [blackberry/VSPlugin#484]
Milestone: Sprint #36 - Marc...  
evillaricomarbella is assigned

Playbook 2.1.0.1526 - BBNDK 2.1.0.1032
it's on both playbooks

```
launch a playbook app for debugging
try to hit a breakpoint
```

Current Behaviour:
It fails to hit the breakpoint

2 participants
guarnold commented 7 months ago

The problem is that the GDB version of PlayBook 1 does not accept the full path when setting breakpoints, as you can see below:

15:56:14 - 6-break-insert --thread-group i1 -f C:\ZAD_MO~1\FALLIN~3\FALLIN~1\src\main.c:151
15:56:14 - &"No source file named C.\n"

It is an easy fix, however, I don’t know yet how this version of GDB will handle the other issue #592, that is, when there are more than one file with the same name in the project, but in different locations.

I would fix that in this way:

```
Send the break insert command with the full path + file name;
If GDB returns an error o Send the break insert command with only file name.
```

guarnold referenced this issue from a commit 7 months ago
    guarnold    Fixed issue #603    d937b99
guarnold referenced this issue from a commit 7 months ago
    guarnold    Merge pull request #604 from blackberry-vsplugin/next_603 …   dc135fc
guarnold commented 7 months ago

I couldn’t fix the way I expected because it is a GDB bug.

Setting breakpoints using NDK 2.1.0 could not work as expected and we have to KIL it:

GDB needs short path names instead of full path names. One example: C:\GamePlay\GAMEPL~4\SAB79F~1\src\PARTIC~1.CPP

In a large project, like Gameplay, there are two distinct files in different directories that have the same short name:

```
one in the GamePlay library - C:/GamePlay/gameplay/src/PARTIC~1.CPP
another one in the project being debugged - C:\GamePlay\gamepl~6\sample~5\src\ PARTIC~1.CPP
```

When we set a breakpoint in line 547 of file C:\GamePlay\gamepl~6\sample~5\src\ PARTIC~1.CPP, it works nice in other NDKs but the 2.1.0 doesn't like it and returns the following response:

18:37:11 - 6-break-insert --thread-group i1 -f C:\GamePlay\GAMEPL~4\SAB79F~1\src\PARTIC~1.CPP:547
18:37:11 - &"No source file named C.\n"
18:37:11 - 6^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="",pending="C:\GamePlay\GAMEPL~4\SAB79F~1\src\PARTIC~1.CPP:547",times="0",original-location="C:\GamePlay\GAMEPL~4\SAB79F~1\src\PARTIC~1.CPP:547"}
(gdb)

To fix this issue, when that happens, it is sent another GDB command, now with only the file name.

18:37:14 - 6-break-insert --thread-group i1 -f PARTIC~1.CPP:547
18:37:14 - 6^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x001a9f64",func="gameplay::ParticleEmitter::setTextureBlending(gameplay::ParticleEmitter::TextureBlending)",file="C:/GamePlay/gameplay/src/PARTIC~1.CPP",fullname="C:/GamePlay/gameplay/src/PARTIC~1.CPP",line="547",times="0",original-location="PARTIC~1.CPP:547"}
(gdb)

It seems that it worked fine but it didn't work as expected. The problem is that the GDB from NDK 2.1.0 created the breakpoint only in the first file it found with that name. In this case, it created the breakpoint in C:/GamePlay/gameplay/src/PARTIC~1.CPP instead of creating in C:\GamePlay\gamepl~6\sample~5\src\ PARTIC~1.CPP.

As you can see, we have to document that. When using NDK 2.1.0, if there are more than one file in the project with the same short name, a breakpoint can be set in the wrong file. To avoid that, the file must be renamed or they should use NDK for BlackBerry 10 (and, of course, use the Z10 and not the PlayBook).
Closed

evillaricomarbella closed the issue 7 months ago
evillaricomarbella commented 7 months ago

the workaround:
Files need to be of different prefix in order to be able to debug correctly.
ie. ParticlesGame.cpp and ParticlesPhysics.cpp will have to be named differently in order for adding breakpoints to resolve. due to this issue. This solution is not ideal.

**Comment by allee** [comment]
Moved this over for RN/KIL purposes now closing.

**Comment by PamC** [comment]
Release note:
Debug breakpoints aren't hit on the BlackBerry PlayBook.
Workaround: Since short path names are used by GDB (e.g., /src/PARTIC~1.CPP), ensure source files are named differently to avoid conflicts.
