### ISSUE TITLE
[2.0.001] uninstalling and re-installing the plug-in can get the get the plug-in into a state where it can stop deploying

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#495]
preq: uninstalled the plugin and kept all the api level, runtime and simulator from the previous installation.
Note: this issue looks to be intermittent
1. uninstall and reinstall the plugin
2. attempt to deploy

Current behaviour:
project does build but does but doesn't deploy with no error message

workaround:
uninstall the plugin and install it again.

**Comment by dbrgss** [comment]
Estimate: 1 Day

**Comment by dbrgss** [comment]
Moving to sprint 72

**Comment by guarnold** [comment]
Not reproducible in VS 2013. Do you have more details?

**Comment by srinivas4912** [comment]
It is not reproduced in VS2013 plugin from build 2.0.0018 on Win8.1 and found as fixed.
