### ISSUE TITLE
[2.0.0001] projects with spaces in their path will fail to debug

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#499]
folder path like C:/BB10 Native SDK/ will fail to debug
workaround remove spaces

**Comment by dbrgss** [comment]
Not sure if this is fixable as the debugging session is failing in GDB and not in Visual Studio.

**Comment by hkopparru** [comment]
Tested with [3.0.0015] VS2013, When there is a space in the project path, in Visual studio its a showing a warning message (please move the project to the one with out spaces and non-ASCII characters) immediately after loading the project from the IDE. so its giving indication to the user not to keep the project names/path with spaces and it might lead to problems in underlying make file system.

**Comment by hkopparru** [comment]
i would like to close this issue, please suggest

**Comment by dbrgss** [comment]
I agree... this can be closed.

**Comment by hkopparru** [comment]
closing this issue now
