### ISSUE TITLE
[2.0.0001] Adding xml files to project throws bar-descriptor editor error

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#514]
Creating xml files and opening xml files throws this error.

![openingxmlfiles](https://f.cloud.github.com/assets/1478549/1525031/4d35a500-4bcf-11e3-8c0b-903baf85cf75.png)

It looks to set bar-descriptor template as default for the whole project so that any xml file opened is expected to fit the bar-descriptor editor template.

**Comment by srinivas4912** [comment]
Steps to Reproduce:
1. Go to File > New > File... > XML File
We met followed error on Win8.1 using VS2013 plugin from 2.0.0018.
![image](https://f.cloud.github.com/assets/5992406/2108095/9fd9d6de-8fd9-11e3-9ba5-f97bab129e1a.png)
![image](https://f.cloud.github.com/assets/5992406/2108096/af74ee58-8fd9-11e3-8031-3cea612dc050.png)
We met followed error on Win7 32 using VS2012 plugin from 2.0.0018.
![image](https://f.cloud.github.com/assets/5992406/2108152/c952f38c-8fda-11e3-9003-d0ff4c1cb0b1.png)

**Comment by srinivas4912** [comment]
The issue has verified in Windows 8.1 64-bit with [3.0.0005] and found that it is fixed.
