### ISSUE TITLE
VS2013: Build Process not working.

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#523]
Summary: When building a project the following error are returned.  

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.Redirect.10.props(23,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.default.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Default.props (105,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\dburgess\VSPlugin\samples\FallingBlocks\FallingBlocks\FallingBlocks.vcxproj]

**Comment by dbrgss** [comment]
In the end this was not an issue.  Above error was caused by corrupt project.

**Comment by dbrgss** [comment]
Looking into other issues.   It appears that a project using the BlackBerry or BlackBerrySimulator profiles are not looking into the right folder for the necessary MSBuil libraries.   If a user has both VS2012 and VS2013 installed concurrently then all works... but a lone install of VS2013 does not.

**Comment by zadmarbella** [comment]
#524 are these related?

**Comment by srinivas4912** [comment]
Built multiple projects successfully using VS2013 plugin from version 2.0.0018 on Win8.1 and VS2012 on Win7 64 bit.
