### ISSUE TITLE
[2.0.0002] unable to build on vs2013

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#524]
using goodcitizen project
build project  on visual studio 2013 

Current Behaviour: 
Build fails with error:

Error      1             error MSB8006: The Platform for project 'GoodCitizen_001.vcxproj' is invalid.  Platform='BlackBerrySimulator'. 
This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project 
has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent 
Platform.             C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.InvalidPlatform.Targets    21           7  
GoodCitizen_001

**Comment by pvallabhaneni** [comment]
Able to build GoodCitizen project and also other projects successfully on VS2013 on Win 8.1,  VS2012 on Win 7 (32 & 64 bit) using 2.0.0018 version plugin.
