### ISSUE TITLE
[2.0.0002] unable to access bar-descriptor editor on vs2013

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#525]
from a bbndk_vs solution (ie. goodcitizen)

open bar-descriptor in editor.

Current Behaviour:
Fails to open with this error:
![vs2013bar-descriptoreditorwontopen](https://f.cloud.github.com/assets/1478549/1623749/fb50a5d4-56b7-11e3-8945-27c4c73e1d40.png)

Workaround:
open through xml editor.

**Comment by zadmarbella** [comment]
Looks to occur in vs2012 also it looks to affect device deploy.

**Comment by srinivas4912** [comment]
Verified using VS2013/VS2012 from 2.0.0018 on Win8.1 and Win7 (64 & 32)bit.
User is able to save the modifications, able to open bar-descriptor.xml file in editor and found as fixed.
