### ISSUE TITLE
[2.0.0001] unable to set debug token using bar-descriptor set from debug token button

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#527]
open bar-descriptor in editor
modify Author information so that it is different from the debug token information
Click Set from Debug token button

current behaviour:
it does nothing. 

expected:
get information from debug token dialogue

Workaround:
copy paste the informaiton

**Comment by guarnold** [comment]
Not reproducible in VS 2013.

**Comment by srinivas4912** [comment]
able to get the Information and updated author information  from "set from debug token" button in bar-descriptor.xml file and found as fixed.
