### ISSUE TITLE
[2.0.0004] user is able to install/uninstall api level and simulator at the same time

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#533]
1. install/uninstall api level
2. click Get Simulators
3. attempt to install/uninstall while api level is installing

Current Behaviour:
user gets Error message and is unable to close Get Simulator window

Workaround:
it seems like once this error has occurred one has to uninstall the plugin and remove the folder contents.

**Comment by srinivas4912** [comment]
Verified and found as fixed using VS2013/VS2012 from product version 2.0.0018 on Win8.1, Win7(64&32) bit.
The button "Get Simulators" is disabled While installing the new API level.
