### ISSUE TITLE
[2.0.0004] unable to deploy to simulator

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#535]
Attempt to deploy/debug project to simulator

Current behaviour in vs2012 win 8.1 vmplayer 6.x
user gets this error:

![failedtoconnectosimulator](https://f.cloud.github.com/assets/1478549/1646273/2946ae06-5916-11e3-8087-462745c5ba0a.png)

**Comment by srinivas4912** [comment]
The issue is not reproduced in all the environments. checked with VS2012/VS2013 plugin from bundle 2.0.0018 and found as fixed.
