### ISSUE TITLE
[2.0.0004] Blackberry Plugin related properties vanish if one saves the project when the plugin is not installed

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#536]
Related to #478 
Open project properties then save the project upon closing visual studio.
Install the plugin open the same project.

Curent Behaviour:
your project properties from the plugin will vanish

![projectpropertiesvanish](https://f.cloud.github.com/assets/1478549/1646394/94c485ec-5919-11e3-984c-32eda47dfc54.png)

Workaround:
Don't save project changes until the plugin is installed

**Comment by hkopparru** [comment]
tested with [3.0.0015] VS 2013 issue is not reproducible, where i am able to see the saved project properties after installing the plugin.
closing this issue now.
