### ISSUE TITLE
Unable to deploy for 10.2.1 devices/simulator

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#538]
The plug-in doesn't give any error message. It just doesn't deploy.

**Comment by guarnold** [comment]
Workaround:
1 - Make sure you have downloaded and installed the 10.2 API level.
2 - Go to folder C:\qconfig
3 - Make a copy of the qnx_blackberry_native_development_kit_10.2.0.1155.xml file and name it with the right API level version (for example, qnx_blackberry_native_development_kit_10.2.1.1055.xml) 
4 - Open this new file
5 - Update the "version" and "detailedVersion" fields with the correct API level version, like 10.2.1.1055
6 - Update the "name" field with a name that will remind you about this workaround, to be able to select it later and to know that this is a fake version (for example, BlackBerry Native SDK 10.2.1_mine).
7 - Save and close this file
8 - When using the VS-plugin, make sure you select the right API level from BlackBerry -> Settings menu (in this case, BlackBerry Native SDK 10.2.1_mine).

**Comment by guarnold** [comment]
Fixed and already merged (#537) for VS 2010 and 2012.

**Comment by zadmarbella** [comment]
verified this workaround on 2.0.0001 able to debug project on simulator 10.2.1.1055

**Comment by pvallabhaneni** [comment]
Verified without any workaround. Able to deploy an application using 10.2 (10.2.0.1155) API level on to a device 10.2.1.1925 OS  and  10.2.1.1925 Simulator containing on Win 7 64 bit system.
