### ISSUE TITLE
API Level selection

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#539]
Currently, the user has to select the right API level in BlackBerry -> Settings menu.

However, after implementing the update manager, the right API level can be selected automatically. So, we have to choose the right way to select the API level and implement it (it is not properly implemented at this moment):

1 - Keep using the current way, i.e., the user selects it. In case he selects the wrong one, a message must be presented to him, indicating that.
2 - Let update manager do this selection automatically. In this case, we should remove the BlackBerry API Levels option in the BlackBerry -> Settings menu and keep only the Get More button.

The current behavior in case the wrong API level is selected: the plug-in uses this wrong one. It verifies if the right one is installed, but does not update the registry (so the right one could be used) and does not present a message to the user (so he could select the correct one)

**Comment by dbrgss** [comment]
v2.0.0015

**Comment by pvallabhaneni** [comment]
Verified using 2.0.0018 plugin on Win 7 and Win 8.2 with VS2012 and VS2013. No message is shown if wrong API level is selected.

**Comment by dbrgss** [comment]
This was a task that was completed.   Closing..
