### ISSUE TITLE
[2.0.0009] Unable to open the bar-descriptor.xml file from the Solution Explorer

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#546]
preq: install VS 2013 plugin from Bundle 184 on Win8.1

Steps to Reproduce: 
1. File --> Open --> Project/Solution
2. Select the project 
3. In Solution Explorer view select the bar-descriptor.xml
4. Try to open(Double click on xml file)

Actual result:
It doesn't open the bar file and prompting to "Microsoft Visual Studio" - bar-descriptor Designer dialog (the vstemplate file you are attempting to load is missing)
Expected result:
It should open the bar file fields in the source code window (UI) properly

**Comment by srinivas4912** [comment]
It's working fine on Win8.1 VS2013 with bundle 187[build 2.0.0012]

**Comment by pvallabhaneni** [comment]
I am able to reproduce the issue on Win7 64bit and 32bit using VS2012 with bundle 187

**Comment by pvallabhaneni** [comment]
Verified on Win 7 32bit using VSNDK Bundle 193 [2.0.0016] and found to as fixed.
