### ISSUE TITLE
Convert Box2D Physics - github.com/blackberry/Box2D

### ISSUE THREAD

**Issue by allee** [blackberry/VSPlugin#55]
Convert Box2D using the Visual Studio Plugin for NDK to find as many issues as possible

**Comment by dbrgss** [comment]
Converted: 
Box2D - Library built and deployed
HelloWorld - Build and deployed.   Needed to modify Intermediate and Output directories.
Testbed - Built and deployed.  Needed to modify intermediate and output directories
