### ISSUE TITLE
Unable to deploy debug token on to the Simulator.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#553]
Preq: Install Visual Studio 2012 on Win7 64 bit system. Install VSNDK plugin

1.Open visual Studio and open a project.
2.Enter simulator IP and Password in Blackberry -> Settings dialog. Leave device IP address and password empty.
3.Select "Blackberry -> Debug Tokens" menu.

Actual Result: Error message is shown as "Missing Device IP".

Expected Result: User should be able to open the "Debug Tokens" dialog and should be able add debug token to the simulator.

**Comment by guarnold** [comment]
Debug Tokens are only needed for devices. Simulator does not support debug tokens.
