### ISSUE TITLE
Deployed application is not found in simulator.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#554]
Preq: Install Visual Studio 2012 on Win7 64 bit system. Install VSNDK plugin

1.Open visual Studio and open a project.
2.Enter IP address and password for simulator in Blackberry -> Settings
3.Build the project and deploy the application on to the simulator.

Actual Result: Application is shown as deployed successfully on to the simulator in the "Output" console. But the application is not found in the simulator.

Expected result:User should be able to deploy the application on to the simulator successfully and should be able to open it.

**Comment by guarnold** [comment]
I could not reproduce this issue in Win8 64 bit system, using VS 2012.

I don't have a Win7 machine anymore. Will have to verify this issue later.

**Comment by hkopparru** [comment]
I could not reproduce this issue in Win7 64 bit system, using VS 2012.
