### ISSUE TITLE
[2.0.0012] Unable to close the Debug Tokens window when clicked on "close button"

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#565]
preq: install VS 2013 plugin from Bundle 187 on Win8.1

Stepts to Reproduce: 
1. BlackBerry --> Debug Tokens
2. Click on Add button --> Enter registration details --> Ok (if not deployed debug token on device)
3. Click on Close button

Actual result:
The Close button not functioned and debug tokens window not closed.
Expected result:
The Debug Tokens window should be close when click on "close" button.

**Comment by srinivas4912** [comment]
The same behaviour observed using [2.0.0012] on win7 64 VS2013 using 10.2.1.1927(SDK OS)

**Comment by dbrgss** [comment]
Fixed in the next version

**Comment by srinivas4912** [comment]
Verified in VS2013 plugin from bundle 192 on Win8.1
