### ISSUE TITLE
[2.0.0012]Unable to Uninstall 10.1.0.4828 API Level with or without Environmental variable (INSTALL_DESCRIPTOR_LOCATION).

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#567]
Steps to reproduce:
1. Install VS2012 on Win7 (32bit) and install NDK plugin (Bundle 187).
2. Install API level from Blackberry->Settings->GetMore.
3. 10.2.1.1155 API level will get installed.
4. Connect the device with 10.1.0.4828 OS.
5. Try to debug the project on the device.
6. It asks for the supporting API level to be installed. Install it.
7. 10.1.0.4828 API level get installed.
8. Go to Blackberry->Settings->GetMore and uninstall the API level.
9. 10.2.1.1055 API level will get uninstalled first.
10. Go to Blackberry->Settings->GetMore and uninstall the API level.

Actual result: 10.1.0.4828 API level is not uninstalling.
Expected Result: 10.1.0.4828 API level need to be uninstalled successfully.

Note: Tried with and without setting the environment variable (INSTALL_DESCRIPTO_LOCATION).

Also tried setting the variable to http://bbndkupdate.rim.net/update/10.1_10.2_testing_install_descriptor.xml  & http://bbndkupdate.rim.net/update/install_descriptor_external.xml.

Issue is reproducible in all the cases.

**Comment by dbrgss** [comment]
This environment variable doesn't work with our project..  

INSTALL_DESCRIPTOR_LOCATION

**Comment by pvallabhaneni** [comment]
I tried uninstalling the API Level 10.1.0.4828 without setting the environmental variable, still I am unable to uninstall it.

**Comment by dbrgss** [comment]
Fixed in latest version

**Comment by pvallabhaneni** [comment]
Verified the issue using bundle 195 [2.0.0018] and found as fixed.
