### ISSUE TITLE
[2.0.0012] Accepting input "BlackBerry" as Author name in Registration Window.

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#568]
Preq: install VS 2013 plugin from Bundle 187 on Win8.1

Steps to Reproduce: 
1. BlackBerry --> Signing 
2. Click registration button --> Sign in to create and download your BlackBerry ID token
3. Input valid Username and Password --> Sign In
4. Input password and click on "Get Token"
5. Input Author name as "BlackBerry" and provide valid password in Registration Window

Actual result:
It is accepting "BlackBerry" as author name, created debug token and registered successfully
Expected result:
It shouldn't accept and dialog should be display as "Blackberry is a reserved word user can't use it as author name"

**Comment by srinivas4912** [comment]
[2.0.0014] I have encountered the same issue while using VS2013 on Win8.1 with Bundle 191 plugin using Trunk Build OS

**Comment by guarnold** [comment]
Available in the next build.

**Comment by srinivas4912** [comment]
Verified and fixed in VS2013 plugin from Bundle 192[2.0.0015] on Win8.1

**Comment by pvallabhaneni** [comment]
"Blackberry" followed by numbers are not accepted as Author name.
![author name](https://f.cloud.github.com/assets/5992422/2008526/a720624a-874c-11e3-875d-9ca742bef0be.PNG)

**Comment by pvallabhaneni** [comment]
Verified in Win 7 64 bit using bundle 195 [2.0.0018] plugin and found the above bug,

**Comment by guarnold** [comment]
I believe that the behavior is correct, by refusing author names that contains "BlackBerry". However, I will keep this issue in Triage until I get the confirmation about that.

**Comment by guarnold** [comment]
Confirmed. VS plugin must not allow any author name that contains the word "BlackBerry".

Recommend to close.

**Comment by pvallabhaneni** [comment]
Verified on win7 64 bit using bundle 195 [2.0.0018]. Author name containing "Blackberry" is not accepted as Author name.
