### ISSUE TITLE
[2.0.0012]"Add" button is disabled when debug token is not added.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#570]
Steps to reproduce:
1. Install VS2012 on Win7 (32bit and 64bit) and NDK plugin Bundle 187.
2. Register the Code signing properties.
3. Go to "Blackberry->Debug Tokens"
4. Click "Add"
5. Registration window opens.
6. Click Cancel.

Actuall Result: "Add" button is disabled.
Expected Result: "Add" button should be enabled again as Registration window is closed without adding debug token to the device.

**Comment by srinivas4912** [comment]
This issue is reproduced on Win 8.1 VS2013 with Bundle 187[Build 2.0.0012].

**Comment by dbrgss** [comment]
Fixed in next release

**Comment by pvallabhaneni** [comment]
Verified in Win 7 32bit and Win8.1 using Bundle 193[2.0.0016]. Found that Registration Window does not open when "Add" button is clicked and debug token is added.
