### ISSUE TITLE
Install Run time is not prompted while debugging

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#573]
preq: don't have run time for device OS, 
device used:London
OS used: 10.1.0.4828
NDK Plugin: Bundle 187
1. Debug a project.
2. Application should prompt to download run time as it is not present.

Actual result: No prompt is shown to download the run time. Project is continuing to build.

**Comment by guarnold** [comment]
There are no runtimes for 10,0 and 10.1 OS versions.
This runtime feature was included only on OS version 10.2.

The described behavior is the expected one for 10.0 and 10.1.
