### ISSUE TITLE
[2.0.0012] Unable to select required API Level from the API Levels window

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#575]
Preq: install VS 2013 plugin from Bundle 187 on Win8.1 using 10.2.1.1927(SDK OS)

Steps to Reproduce: 
Don't have the API Level for the device OS
1. DEBUG --> Start Debugging 
2. API Levels window opened and list out the SDK OS

![image](https://f.cloud.github.com/assets/5992406/1877980/a530090e-7932-11e3-99ac-677cd72318af.png)

Actual result:
The API Levels window, Didn't have the scrollbar to select required API Levels.
Expected result:
The required API Level should be able to select and install button should be available to install from the API levels window.

**Comment by pvallabhaneni** [comment]
I have encountered the same bug while using VS 2012 on Win 7 (32bit) with Bundle 187 plugin using 10.1.0.4828 OS

**Comment by srinivas4912** [comment]
Observed the same behaviour using [2.0.0012] on win7 64 VS2013 using 10.2.1.1927(SDK OS)

**Comment by dbrgss** [comment]
You should not be seeing the list as it is displayed.   You should only have 3 entries...  one for 10.0, 10.1 and 10.2...   Has the computer you are testing on ever been used for Momentics testing??   Do you have other NDK's installed on the PC??

Dave

**Comment by dbrgss** [comment]
Just to let you know... that this dialog will disappear and not display once you download and install one of the API levels.. you do not necessarily have to pick the exact version that  you are going to use.

**Comment by pvallabhaneni** [comment]
Issue is reproducible with VSNDK Plugin Bundle 191 [2.0.0014] on Win 7 64 bit.

**Comment by dbrgss** [comment]
Fixed in the next available version

**Comment by srinivas4912** [comment]
Verified in VS2013 plugin from bundle 192[2.0.0015] on Win8.1
