### ISSUE TITLE
[2.0.0014] unable to connect to device while debugging

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#577]
Win 8.1 VS2013.
1. Launch project for debugging

Current Behaviour:

The connection looks to time out on gdb side.

Errorlogs:
gdb) 
10:42:35 - =thread-group-added,id="i1"

10:42:35 - ~"GNU gdb (GDB) 7.5 qnx (rev. 791)\n"

~"Copyright (C) 2012 Free Software Foundation, Inc.\n"

~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law. Type \"show copying\"\nand \"show warranty\" for details.\n"

~"This GDB was configured as \"--host=i386-mingw32msvc --target=arm-unknown-nto-qnx8.0.0\".\n"

(gdb) 

10:42:35 - 1-gdb-set breakpoint pending on

10:42:35 - 1^done

(gdb) 

10:42:35 - 4-target-select qnx 169.254.0.1:8000

10:43:20 - 4^error,msg="169.254.0.1:8000: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

(gdb)

**Comment by guarnold** [comment]
Available in the next build.

**Comment by srinivas4912** [comment]
Verified and fixed in win8.1 and win7 64 bit using VS2013/VS2012 from bundle 2.0.0018 on 10.2 device OS
