### ISSUE TITLE
[2.0.0012] User is unable to add debug token if entered wrong CSK password once.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#578]
Preq:
1.Install VS2012 in Win7(32bit).
2.Download CSK file from Blackberry->Signing

Steps to Reproduce:
1.Go to Blackberry->Debugtokens dialog.
2. Add debug token
3. Registration window prompts for Author name and BBID token password.
4. Enter a Author name and wrong BBID Token password.
5. "The specified CSK password" error dialog appears and "debug tokens" dialog is still visible in the back of error dialog.
6. Press OK.

Actual Result: Registration window is appearing and "debug tokens" dialog is disappearing. When user enters valid password now and select "OK" the registration windows closes. User is unable to know if the debug token is added or not. Again Go to Blackberry->Debug tokens dialog. It is observed that the debug token is not added.

Expected result: "Debug tokens" dialog should not disappear when user selects OK in error dialog and Registration windows should appear for the user to enter correct password and user should be able to add the debug token after entering correct password.

**Comment by dbrgss** [comment]
Issue Fixed... will be included in the next build.

**Comment by pvallabhaneni** [comment]
Verified on Win 7 32bit using VSNDK plugin 193 [2.0.0016] and found as fixed.
