### ISSUE TITLE
[2.0.0012] Unable to take Backup for Signing Key.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#579]
Preq:
1. Install VS2012 on Win7 (32bit).
2. Install VSNDK plugin - Bundle 187

Steps to Reproduce:
1. Complete the signing process and make sure that the signing keys are present.
2. Go to Blackberry -> Signing and click "Backup"
3. Browse to a location and save.

Actual Result: Following error message is shown.
![signing backup](https://f.cloud.github.com/assets/5992422/1858263/d46d7aae-7788-11e3-851d-5654a1723168.png)

Expected Result:
Zip file is created and contains all the necessary signing information.

**Comment by dbrgss** [comment]
Mark Completed: Fix to be included in the next available build.

**Comment by pvallabhaneni** [comment]
Verified the issue on Win 7 32bit using VSNDK plugin bundle 193 [2.0.0016] and found as fixed.
