### ISSUE TITLE
b113 - able to set Asset Configuration Assets Source Path using a relative path

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#58]
1 Open bar-descriptor editor
2 Select Device/Simulator-$(Configuration)
3 Navigate to Asset Configuration Assets Source Path
4. Attempt to add an Entry Point that is Relative

Current behaviour: is it uses absolute paths.

Workaround: manually edit the bar-descriptor.xml file to be a relative path

**Comment by mattcostanzo** [comment]
Est. 1 day

**Comment by guarnold** [comment]
It allows using relative path, however, the asset must be included in the project's folder.

If the asset is in the project folder, it is used its relative path, otherwise absolute.

**Comment by zadmarbella** [comment]
For a project like Bullet where it builds outside the project folder we want it to be able to set the path relative.

**Comment by guarnold** [comment]
Now it is always being used relative paths, except when the asset is located in a different drive.

**Comment by zadmarbella** [comment]
this fix is not in build 1.01.0015

**Comment by zadmarbella** [comment]
verified 1.01.0018 
the path is relative to where the bar-descriptor is located when adding Asset Configuration files
