### ISSUE TITLE
[2.0.0014] unable to uninstall multiple simulators consecutively without closing Simulator download dialog

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#580]
Win8.1 vs2013/2012

Install more than 1 simulator
uninstall one 
do not close Simulator Dialog
uninstall the other

Current behaviour:
Info dialog appears indicating simulator is are already installing/uninstalling.
When Dialog message says it's Complete.

![uninstallmorethanonesim](https://f.cloud.github.com/assets/1478549/1859139/661e24d0-779d-11e3-9633-4b5953755106.png)

Workaround:
Close simulator dialog and open it again

**Comment by dbrgss** [comment]
Marked Complete.   Change will be included in the next build.

**Comment by srinivas4912** [comment]
It is not reproduced and found as fixed using plugin VS2012 from build 2.0.0018 on win7 64 bit.
