### ISSUE TITLE
[2.0.0014]Installed API level is not listed correctly.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#587]
Preq: Install VS 2012 and VSNDK Plugin Bundle 191[2.0.0014] on Win 7 64 bit. / Install VS 2013 and VSNDK plugin Bundle 191[2.0.0014] on Win 8.1.

Steps to reproduce:
1. Goto Blackberry->Settings->GetMore
2. Observed that Blackberry Native SDK (10.0,10.1,10.2) are shown in "Available" list.
3. Click "install" beside Blackberry Native SDK 10.2
4. After completing the installation close the API Level dialog and select "GetMore" again.

Actual result:  Blackberry Native SDK 10.2 is still shown in available list and "installed" list blank.But  Blackberry Native SDK 10.2 is listed in API Level dropdown box in Settings dialog.This behaviour is observedeven after closing both API Level and Setting dialog and opening again.
![api levels](https://f.cloud.github.com/assets/5992422/1877462/59af3dac-7927-11e3-945b-7810ff616556.PNG)

Expected resut:  Blackberry Native SDK 10.2 should be shown in "installed" list on "API Level" dialog.

Note : Blackberry Native SDK 10.2 is shown in "Installed" list if Visual studio is closed completely and opened again.

**Comment by dbrgss** [comment]
Fixed in the next available version

**Comment by pvallabhaneni** [comment]
Verified the issue using bundle 195[2.0.0018] and found as fixed.
