### ISSUE TITLE
[2.0.0014]UnInstalled API level is not listed correctly.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#588]
Preq: Install VS 2012 and VSNDK Plugin Bundle 191[2.0.0014] on Win 7 64 bit. / Install VS 2013 and VSNDK plugin Bundle 191[2.0.0014] on Win 8.1 and Install 2.1.0.115 API Level.

Steps to reproduce:
1. Goto Blackberry->Settings->GetMore
2. Observe that Blackberry Native SDK 10.2 is listed in API Level drop down box in Settings dialog.
3. Observe that Blackberry Native SDK 10.2 is listed under "Installed" section.
4. Click "Uninstall" for Blackberry Native SDK 10.2.

![uninstall](https://f.cloud.github.com/assets/5992422/1877532/d577868c-7928-11e3-85b9-3ebfcc9fb3e0.PNG)

Actual Result: After completion of un-installation Blackberry Native SDK 10.2 is not listed in API Level drop down box in Settings dialog, but still listed in "Installed" section of API Level dialog. This behavior is observed even after closing both the dialog and opening again.

Expected Result: Un-installed API level should not listed under "Installed" section of API Level dialog.

Note: Uninstalled API level is removed from "Installed" section only after closing Visual studio completely and opening again.

**Comment by dbrgss** [comment]
This should be fixed as part of other fixes to the Upgrade Manager... please re-verify.

**Comment by pvallabhaneni** [comment]
Verified the issue on Win 7 64 bit using Bundle 195 [2.0.0018] and found as fixed.
