### ISSUE TITLE
[2.0.0014] Device IP Address is set by default in Settings dialog.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#592]
Preq: No device is connected to the system.

Steps to Reproduce:
1. Install VS2012 on Win 7 64bit.
2. Install VSNDK Plugin Bundle 191[2.0.0014].
3. Goto Blackberry->Settings.

Actual Result: Device IP Address is set to 169.254.0.1 by default.

Expected Result: Device IP Address text box need to be empty and user has to add the IP Address.

**Comment by guarnold** [comment]
It works as expected. 169.254.0.1 is the default IP for devices and it is set during the plug-in installation.
