### ISSUE TITLE
[2.0.0015] Debug token dialog is opening when signing is not done.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#597]
Steps to Reproduce:
1.Install VS2012 on Win 7 32bit / VS2013 on Win 8.1 and related VSNDK Plugin.
2.Do not register signing keys.
3.Goto Blackberry->Debug Tokens

Actual Result: Error message is shown that signing keys are missing .
![missing](https://f.cloud.github.com/assets/5992422/1930060/3017f124-7ea3-11e3-86fc-607073152c4f.png)

when user selects OK, Error message box is shown wihout any error message on it as follows.
![error](https://f.cloud.github.com/assets/5992422/1930065/363b134c-7ea3-11e3-9fea-6a4fbbcd46a6.png)

When User select "OK" in Error message box nothing is happening.

Again Goto Blackberry->Debug Tokens. Then Error message is shown that signing keys are missing and when user closes the missing signing keys dialog box, debug toekn dialog is opened.

**Comment by dbrgss** [comment]
Fixed as of v2.0.0016

**Comment by srinivas4912** [comment]
Preq: Install VS2013 plugin from bundle 193[2.0.0016] on Win8.1

Steps to Reproduce:
1. Do not register signing keys.
2. Go to Blackberry->Debug Tokens
3. Signing keys not registered dialog is opened.
4. Click on "OK"

Actual Result: 
Debug Tokens dialog is opened.
![image](https://f.cloud.github.com/assets/5992406/1938537/d34695ae-7f4c-11e3-9270-7560636c0227.png)

**Comment by pvallabhaneni** [comment]
Verified in Win 7 32bit using VSNDK bundle 193 [2.0.0016]. Debug token dialog is still opening after closing the "missing signing key" dialog.

**Comment by guarnold** [comment]
Available in build 2.0.0018 (bundle195).

**Comment by pvallabhaneni** [comment]
Verified in build 2.0.0018 (bundle195) and found as fixed.

**Comment by srinivas4912** [comment]
Verified and found as fixed from build 2.0.0018 on Win8.1 and Win7 (64&32) bit.
