### ISSUE TITLE
[2.0.0015] Able to register completely when wrong password is given in Registration Window

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#598]
Steps to Reproduce:
1.Install VS2012 on Win7 32bit and install VSNDK plugin Bundle 192[2.0.0015],
2.Goto Blackberry->Signing.
3.Login and download CSK password.
4.Registration window opens.
5.Enter an Author name and wrong BBID Token password.

Actual Result: After closing the Registration Window by selecting OK button, Code Signing Properties dialog is shown as Registered ("Register" button is disabled and "Unregister" button is enabled).

**Comment by srinivas4912** [comment]
Reproduced in VS2013 plugin from Bundle 192[2.0.0015] on Win8.1

**Comment by dbrgss** [comment]
This is as designed.   Registration/Generation of the signing keys doesn't do any sort of validation of the User Name or Password being entered in.  This doesn't happen until you attempt to create a DebugToken which then calls out the the Server using the Signing Keys and is validated at that time.   If you try to create a DebugToken with an invalid password you will receive an Error and then an opportunity to re-enter this information correctly.
