### ISSUE TITLE
[2.0.0015] Debug token dialog is opening when missing device IP address.

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#599]
Preq: 1. Install VS2013 plugin from Bundle 192[2.0.0015] on Win8.1 

Steps to reproduce:
1. Go to BlackBerry --> Settings.
2. Clear IP Address and Device Password fields.
![image](https://f.cloud.github.com/assets/5992406/1930279/58776e42-7ea8-11e3-8d38-886b7e86e461.png)
3. Go to BlackBerry --> Debug Tokens.

Actual Result:
Missing Device IP dialog is opened.
![image](https://f.cloud.github.com/assets/5992406/1930315/4a879efa-7ea9-11e3-92bb-da312f183a3d.png)
When clicked on "OK" , it is opening Debug tokens dialog.
![image](https://f.cloud.github.com/assets/5992406/1930349/e8eef4d0-7ea9-11e3-9d1b-d50f1ac8ae1c.png)

**Comment by dbrgss** [comment]
Fixed as of 2.0.0016

**Comment by srinivas4912** [comment]
Verified in VS2013 plugin from bundle 193[2.0.0016] on Win8.1 and fixed.
