### ISSUE TITLE
[2.0.0016] In Permissions, Found some of the check boxes unchecked when scrolling up and down. 

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#608]
Preq: Install VS2013 plugin from Bundle 193[2.0.0016] on Win8.1

Steps to reproduce:
1. Open bar-descriptor.xml file in editor.
2. Modify permissions[Check all the check boxes].
![image](https://f.cloud.github.com/assets/5992406/1954581/f21c9386-81d9-11e3-93d6-57717a94a552.png)
3. Scroll up and down using mouse/scroll bar.

Actual result: 
1. When scrolling up observed that, top of the check boxes are unchecked.
![image](https://f.cloud.github.com/assets/5992406/1954594/30f4dc76-81da-11e3-80d6-037caeed3cad.png)
2. When scrolling down, bottom of the check boxes are unchecked.
![image](https://f.cloud.github.com/assets/5992406/1954652/538efaea-81db-11e3-95d0-9fc2c9e042d7.png)

Note: Changes persists and no errors occurred when save, close and reopen  bar-descriptor.xml file.

**Comment by pvallabhaneni** [comment]
Same issue is observed on Win 7 32bit using VS2012

**Comment by guarnold** [comment]
Available in build 2.0.0018 (bundle195).

**Comment by pvallabhaneni** [comment]
Verified the issue using Bundle 195 [2.0.0018] and found as fixed in Win 7 32bit system.
