### ISSUE TITLE
Failed to launch debugger on 10.1 and 10.0 device/simulator

### ISSUE THREAD

**Issue by guarnold** [blackberry/VSPlugin#609]
We met error "Failed to launch debugger" is on 10.1.0.4828 device/simulator
But it works on 10.2.0 and 10.2.1 device/simulator

Related to issue #310

**Comment by guarnold** [comment]
Available in build 2.0.0018 (bundle195).

**Comment by srinivas4912** [comment]
It has not fixed and reproduced on Win7 64 using VS2013/VS2012 plugin from bundle 2.0.0018.
Preq: Installed API level 10.1.0.4828
When we are debugging on device using 10.1.0.4828 OS, we met error "Failed to launch debugger".

**Comment by guarnold** [comment]
The verbosity cannot be set to Quiet. Please check: 
Tools -> Options -> "Projects and Solutions" -> "Build and Run" -> "MSBuild project build output verbosity"
Tools -> Options -> "Projects and Solutions" -> "Build and Run" -> "MSBuild project build log file verbosity"
This issue is always reproducible when using 10.0 and 10.1 devices/simulators with the verbosity set to Quiet.

If the verbosity is not Quiet, please send us the following information:
- the entire build text messages from the Output window -> Build
- the gdb-output.log file (located in this folder: ($AppData)\Roaming\BlackBerry)

**Comment by pvallabhaneni** [comment]
Installed VS2012and VSNDK plugin - 2.0.00.18  on Win 7 32bit fresh machine and downloaded 10.1 API level and found that 10.1.0.1020 API level is downloaded. Target and host folders present in bbndk_vs folder are related to 10.1.0.1020 and no other target,host folders are found.

In the settings dialog API level is set to 10.1.0.1020 as follows.
![apilevel](https://f.cloud.github.com/assets/5992422/2064440/95af1792-8ccc-11e3-95d1-987ddf7ea918.png)

When I tried to debug the project with the above settings, following dialog is shown.
![deveice os](https://f.cloud.github.com/assets/5992422/2064438/90eb7eee-8ccc-11e3-8a7b-b72f407e90bd.png)

Tools -> Options -> "Projects and Solutions" -> "Build and Run" -> "MSBuild project build log file verbosity" is set to "minimal"

Tools -> Options -> "Projects and Solutions" -> "Build and Run" -> "MSBuild project build log file verbosity" is set to "minimal"

Below if the entire build text messages from the Output window -> Build
1>------ Rebuild All started: Project: FallingBlocks_001, Configuration: Debug BlackBerrySimulator ------
1>  rm -rf  ./main.o ./main.d C:/FOR_SA~2/FALLIN~2/FALLIN~1/SIMULA~1/FallingBlocks_001 C:/FOR_SA~2/FALLIN~2/FALLIN~1/SIMULA~1/FallingBlocks_001.bar
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(343,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number.
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1138,5): warning MSB8012: TargetExt(.exe) does not match the Linker's OutputFile property value (). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppBuild.targets(1139,5): warning MSB8012: TargetName(FallingBlocks_001) does not match the Linker's OutputFile property value (Simulator-Debug). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>  qcc -o main.o C:/Users/pvallabhaneni/Desktop/Fresh Samples/FallingBlocks_001/FallingBlocks_001/main.c -V"4.6.3,gcc_ntox86" -c -Wp,-MMD,main.d -Wp,-MT,main.o -g -w3 -lang-c -fexceptions -fstack-protector-all -I"C:/bbndk_vs/target_10_1_0_1020/qnx6\usr\include" -I"C:/bbndk_vs/target_10_1_0_1020/qnx6\usr\include\freetype2" -I"C:/bbndk_vs/target_10_1_0_1020/qnx6..\target-override\usr\include" -DQCC -D__QCC__ -D__QNX__ -UWIN32 -U_WINDOWS 
1>  qcc -o C:/Users/pvallabhaneni/Desktop/Fresh Samples/FallingBlocks_001/FallingBlocks_001/Simulator-Debug/FallingBlocks_001  ./main.o   -V"4.6.3,gcc_ntox86" -lang-c++ -g -Wl,-z,relro,-z,now -lbps -lscreen -lpng -lglview -lGLESv1_CM -L"C:/bbndk_vs/target_10_1_0_1020/qnx6\x86\lib" -L"C:/bbndk_vs/target_10_1_0_1020/qnx6..\target-override\x86\lib" -L"C:/bbndk_vs/target_10_1_0_1020/qnx6..\target-override\x86\usr\lib" 
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Note: Could not find gdboutput.log file in the ($AppData)\Roaming\BlackBerry folder.
Observed that gdboutput.log and wrapper.log files are found only after debugging.

**Comment by pvallabhaneni** [comment]
Unexpectedly closed the issue.Reopening it.

**Comment by guarnold** [comment]
Did you try to debug the app after rebuilding it? 
We need to get the generated build messages that you receive while you try to debug the app. If it fails to debug, after rebuilding using the correct api level, you should have the build log (from debugging) as well as the gdb-output.log file.

**Comment by guarnold** [comment]
The build messages from debugging should be something like this one, which includes the process ID on it (1>  result::9887882). Then, the GDB output log might exist and should have important information about why the debugger was not able to be launch.

1>Build started 1/31/2014 12:54:34 PM.
1>BuildBar:
1>  App Installed
1>  FallingBlocks_001.vcxproj -> 
1>OptimizedDeploy:
1>  Info: Sending request: Get File
1>  Info: Action: Get File
1>  Info: Package com.example.FallingBlocks_001.testDev_gBlocks_0015bf3c0e_
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_001.testDev_gBlocks_0015bf3c0e_/META-INF/MANIFEST.MF
1>  Info: Sending File: 1546
1>  Info: File saved: targetManifest.mf
1>  PackageId: testDev_gBlocks_0015bf3c0e_
1>  Modified [1]: [localManifest.mf] => [META-INF/MANIFEST.MF]
1>  Deleted [0]: []
1>  Info: Sending request: Put File
1>  Info: Action: Put File
1>  Info: File size: 1546
1>  Info: Package com.example.FallingBlocks_001.testDev_gBlocks_0015bf3c0e_
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_001.testDev_gBlocks_0015bf3c0e_/META-INF/MANIFEST.MF
1>  result::success
1>  Info: Sending request: Launch
1>  Info: Action: Launch
1>  Info: Debug native: on
1>  Info: Launching com.example.FallingBlocks_001.testDev_gBlocks_0015bf3c0e_...
1>  result::9887882
1>  Info: done

**Comment by guarnold** [comment]
Try the following steps:
1 - Use a 10.0 or 10.1 simulator or device. For this issue, it is being used the 10.1.0.4828.

2 - Select an API level to build the app that is compatible with the device/simulator. Compatible means: the same version or older than the device/simulator OS version (in this case, 10.1.0.4828). It can be 10.1.0.1020 that was used before but it cannot be 10.2. 
  --   Observation 1 - If the API level used to build the app is not compatible with the device/simulator OS version ((i.e. the API level is newer than the device/simulator OS), the window message "API Level not supported by the device's/simulator's OS version" is presented, showing the device/simulator OS version and the API level that was used to build the app. The debug session is canceled after closing this window.
  --  Observation 2 - If you get the message presented in Observation 1, you have two options: a) Select a device/simulator that has a OS version that supports the API level used to build the app and then try to debug again; b) Select an API level that is supported by the device/simulator, clean the project, build the project, and then try to debug again. Remember that, for this issue, you have to verify using API levels and device/simulator OS version 10.0 or 10.1, so you cannot choose Option a) and switch to a 10.2 device/simulator.
  --  Observation 3 - if you select the API level but do not clean/build the app after selecting this new one, you are just using the old API level that was used before to build the app. The "Selected API level" is used by the plugin to build the app, not to debug it. To debug it is used the one that corresponds to the device/simulator OS version. Normally, we ask for the API level because we consider that you cleaned/built the app after that.

3 - Clean the project.

4 - Build the project.

5 - If the device/simulator OS version is 10.0 or 10.1, and it is for this issue, make sure that the verbosity IS NOT set to "Quiet". It will fail to launch the debugger if it is set to "Quiet" when using 10.0 or 10.1 OS.

6 - Debug the app.

From this point on, it is expected that you must be able to debug the app.

If you cannot debug the app and you see a "Failed to launch the debugger" window message (this issue), please send us the following items:

I) The output messages from the Output window. You have to select "Build" from the "Show output from:" in the Output Window. Do this only after trying to debug the app and not after building the app.
II) The gdb-output.log file  (located in this folder: ($AppData)\Roaming\BlackBerry). Those files are generated only after debugging an app. Please verify if this one is based on the latest attempt to debug or from another attempt. Check the time that this file was modified to ensure that this log file corresponds to the last attempt to debug the app

**Comment by pvallabhaneni** [comment]
I have installed VS2012 and 2.0.0018 version plugin. Connected a device having  10.1.0.4828 OS.

Downloaded 10.1.0.1020 API level. Rebuilt the project and tried to debug the project. 
While debugging it asked to install 10.1.0.4828. I have installed it. Then I am unable to debug the project and following is the ouput log.

1>------ Deploy started: Project: FallingBlocks_MltThrd_001, Configuration: Debug BlackBerry ------
1>BBNATIVEPACKAGER : warning : Using default icon: C:\bbndk_vs\host_10_1_0_132\win32\x86\usr\samples\icons\blackberry-tablet-default-icon.png
1>  Info: Package created: Device-Debug\FallingBlocks_MltThrd_001.bar
1>  FallingBlocks_MltThrd_001.vcxproj -> Device-Debug\FallingBlocks_MltThrd_001.bar
1>  Info: Sending request: Install and Launch
1>  Info: Action: Install and Launch
1>  Info: Debug native: on
1>  Info: File size: 19981
1>  Info: Installing com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa...
1>  Info: Processing 19981 bytes
1>  Info: Progress 100%...
1>  actual_dname::com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  actual_id::testDev_MltThrd_001452978aa
1>  actual_version::1.0.0.1
1>  result::success
1>  Info: Launching com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa...
1>  result::66785495
1>  Info: done
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
Gdb-oupt.log has the following content.

04:14:43 - =thread-group-added,id="i1" 
04:14:43 - ~"GNU gdb (GDB) 7.5 qnx (rev. 750)\n" 
~"Copyright (C) 2012 Free Software Foundation, Inc.\n" 
~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n" 
~"This GDB was configured as \"--host=i386-mingw32msvc --target=arm-unknown-nto-qnx8.0.0\".\nFor bug reporting instructions, please see:\n" 
04:14:43 - ~"http://www.gnu.org/software/gdb/bugs/.\n" 
(gdb)  
04:14:43 - 1-gdb-set breakpoint pending on 
04:14:43 - 1^done 
(gdb)  
04:14:43 - 4-target-select qnx 169.254.0.1:8000 
04:14:53 - ~"MsgNak received - resending\n" 
04:14:53 - ~"Remote target is little-endian\n" 
04:14:53 - 4^connected 
(gdb)  
04:14:53 - 5-file-exec-and-symbols C:/Users/pvallabhaneni/Desktop/Fresh Samples/FallingBlocks_001/FallingBlocks_001/Device-Debug/FallingBlocks_001 
04:14:53 - ~"No executable file now.\n" 
04:14:53 - 5^error,msg="C:/Users/pvallabhaneni/Desktop/Fresh: No such file or directory." 
(gdb)  

Wrapper.log file has the following content.
Starting 
args: C:\Program Files\BlackBerry\VSPlugin-NDK\GDBWrapper.exe C:/bbndk_vs/host_10_1_0_132/win32/x86\usr\bin\ntoarm-gdb.exe --interpreter=mi2 Ctrl-C-4664 Terminate-4664 

Ctrl-C handler: name: Ctrl-C-4664 handle: 000001E4 

Terminate handler: name: Terminate-4664 handle: 000001E8 

WaitForMultipleObjects 
WAIT_OBJECT_0 + 1 (Terminate) 
+shutdown 
-shutdown 

Then I have set the API level to 10.1.0.4828. Rebuilt the same project and tried to debug it.

Following error message is shown.

![4828](https://f.cloud.github.com/assets/5992422/2074943/bda2deb6-8d83-11e3-951e-df8288610810.png)

Output dialog messages are as follows:
1>------ Deploy started: Project: FallingBlocks_MltThrd_001, Configuration: Debug BlackBerry ------
1>BBNATIVEPACKAGER : warning : Using default icon: C:\bbndk_vs\host_10_1_0_238\win32\x86\usr\samples\icons\blackberry-tablet-default-icon.png
1>  FallingBlocks_MltThrd_001.vcxproj -> 
1>  Info: Sending request: Get File
1>  Info: Action: Get File
1>  Info: Package com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa/META-INF/MANIFEST.MF
1>  Info: Sending File: 1548
1>  Info: File saved: targetManifest.mf
1>  Info: Sending request: Put File
1>  Info: Action: Put File
1>  Info: File size: 32455
1>  Info: Package com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa/native/FallingBlocks_MltThrd_001
1>BBDEPLOY : error : Cannot write to file ../../../../apps/com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa/native/FallingBlocks_MltThrd_001: Resource busy
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
Gdb-output.log file ha sthe following content.
04:59:09 - =thread-group-added,id="i1" 
04:59:09 - ~"GNU gdb (GDB) 7.5 qnx (rev. 781)\n" 
~"Copyright (C) 2012 Free Software Foundation, Inc.\n" 
~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n" 
04:59:09 - ~"This GDB was configured as \"--host=i386-mingw32msvc --target=arm-unknown-nto-qnx8.0.0\".\n" 
04:59:09 - (gdb)  
04:59:09 - 1-target-select qnx 169.254.0.1:8000 
04:59:10 - ~"MsgNak received - resending\n" 
04:59:10 - ~"Remote target is little-endian\n" 
04:59:10 - 1^connected 
(gdb)  
04:59:10 - info pidlist 
04:59:10 - &"info pidlist\n" 
04:59:10 - ^done 
(gdb)  
Wrapper.log file has the following content.
Starting 
args: C:\Program Files\BlackBerry\VSPlugin-NDK\GDBWrapper.exe C:/bbndk_vs/host_10_1_0_238/win32/x86\usr\bin\ntoarm-gdb.exe --interpreter=mi2 Ctrl-C-4664 Terminate-4664 

Ctrl-C handler: name: Ctrl-C-4664 handle: 000001E8 

Terminate handler: name: Terminate-4664 handle: 000001EC 

WaitForMultipleObjects 
WAIT_OBJECT_0 + 1 (Terminate) 
+shutdown 
-shutdown 

Then I have set back the API level to 10.1.0.1020. Rebuilt the same project and tried to debug it.
Following error is shown.

![4828](https://f.cloud.github.com/assets/5992422/2074944/ca02cd06-8d83-11e3-8166-596ce67c89b4.png)

Following is the Output window messages.
1>------ Deploy started: Project: FallingBlocks_MltThrd_001, Configuration: Debug BlackBerry ------
1>BBNATIVEPACKAGER : warning : Using default icon: C:\bbndk_vs\host_10_1_0_132\win32\x86\usr\samples\icons\blackberry-tablet-default-icon.png
1>  FallingBlocks_MltThrd_001.vcxproj -> 
1>  Info: Sending request: Get File
1>  Info: Action: Get File
1>  Info: Package com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa/META-INF/MANIFEST.MF
1>  Info: Sending File: 1652
1>  Info: File saved: targetManifest.mf
1>  Info: Sending request: Put File
1>  Info: Action: Put File
1>  Info: File size: 1652
1>  Info: Package com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa
1>  Info: Asset Path ../../../../apps/com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa/META-INF/MANIFEST.MF
1>  result::success
1>  Info: Sending request: Launch
1>  Info: Action: Launch
1>  Info: Debug native: on
1>  Info: Launching com.example.FallingBlocks_MltThrd_001.testDev_MltThrd_001452978aa...
1>BBDEPLOY : error : application is opening
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

Gdb-output.log file has the following contents.

04:28:53 - =thread-group-added,id="i1" 
04:28:53 - ~"GNU gdb (GDB) 7.5 qnx (rev. 750)\n" 
~"Copyright (C) 2012 Free Software Foundation, Inc.\n" 
~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n" 
04:28:53 - ~"This GDB was configured as \"--host=i386-mingw32msvc --target=arm-unknown-nto-qnx8.0.0\".\nFor bug reporting instructions, please see:\n" 
~"http://www.gnu.org/software/gdb/bugs/.\n" 
(gdb)  
04:28:53 - 1-target-select qnx 169.254.0.1:8000 
04:28:54 - ~"MsgNak received - resending\n" 
04:28:54 - ~"Remote target is little-endian\n" 
04:28:54 - 1^connected 
(gdb)  
04:28:54 - info pidlist 
04:28:54 - &"info pidlist\n" 
04:28:54 - ^done 
(gdb)  
Wrapper.log file has the following contents.

Starting 
args: C:\Program Files\BlackBerry\VSPlugin-NDK\GDBWrapper.exe C:/bbndk_vs/host_10_1_0_132/win32/x86\usr\bin\ntoarm-gdb.exe --interpreter=mi2 Ctrl-C-4664 Terminate-4664 

Ctrl-C handler: name: Ctrl-C-4664 handle: 000001E8 

Terminate handler: name: Terminate-4664 handle: 000001EC 

WaitForMultipleObjects 
WAIT_OBJECT_0 + 1 (Terminate) 
+shutdown 
-shutdown

**Comment by guarnold** [comment]
You cannot have spaces in the path. That's why it failed to launch in the first attempt. There is a space between " fresh sample " in: C:/Users/pvallabhaneni/Desktop/Fresh Samples/FallingBlocks_001/FallingBlocks_001/Device-Debug/FallingBlocks_001 

About the other two attempts, did you close the app that was running in the device / simulator? You should have seen a black screen in the device / simulator, that's because the app was deployed , launched and entered in break mode while waiting for the debugger to attach to it.

It seems to me that the app was not closed because the other two attempts failed because the file could not be updated, probably because the file was being used.

**Comment by guarnold** [comment]
1 - remove the spaces in the path of the project folder. 
2 - follow the same steps you did before, but always check if the app is running in the device / simulator before you start debugging. If it is running, close it.

**Comment by pvallabhaneni** [comment]
Able to debug the project successfully using 10.1.0.1020 API level on Win 7 32bit on a device containing 10.1.0.4828 OS
