### ISSUE TITLE
[2.0.0016] Target Name  is not updated correctly in Intermediate Directory.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#610]
Preq: Install VS2012 on Win 7 32 bit.
Step to Reproduce:
1.Access the project properties from the contextual menu and modify Project name.
2.Build the project.

Actual Result: Output Directory is updating the output file name correctly with the new name given in the project properties. But Intermediate directory is created with the same old name.

![bug](https://f.cloud.github.com/assets/5992422/1961013/d4354c52-8263-11e3-8581-d2d0ae68bae7.PNG)

**Comment by guarnold** [comment]
That's expected. The target name property corresponds to the application name that will be created in the output directory, as you can see in the pictures. 

However, the files that are stored in the Intermediate folder use the name of the project and not the target name. The behavior in Win32 projects is the same.
