### ISSUE TITLE
[2.0.0016] Unable to switch from one platform to another after navigate to "Configuration Properties"

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#612]
Preq: Install VS2013 plugin from Bundle 193[2.0.0016] on Win8.1

Steps to reproduce:
1. Access project properties from the project context menu
2. From the drop down switch platform to "BlackBerrySimulator"
3. Navigate to Configuration Properties

Actual Result:
1. Overlaps configuration and platform drop down menus when navigating to common properties and configuration properties
![image](https://f.cloud.github.com/assets/5992406/1962156/d25fe288-8282-11e3-8bdd-52890f5938a1.png)
2. When navigate to common properties
![image](https://f.cloud.github.com/assets/5992406/1962170/0326b68a-8283-11e3-9f00-03cc855369e5.png)
3. and Unable to switch from "BlackBerrySimulator" to "BlackBerry" from platform drop down menu, After navigating to Configuration properties. 

Expected Result:
From platform window, it should able to switch from "BlackBerrySimulator" to "BlackBerry" or else.

**Comment by guarnold** [comment]
This is a Visual Studio issue / behavior, not the plug-in one.

The results 1 and 2 also happens with the default VS configuration. To verify that, create a new C++ console project. Then, create a new configuration. Choose the x64 one, as it is not related to BlackBerry and open its properties. Navigate the same way and you will get the same results / issues.

About the 3rd result, it is the current Visual Studio behavior. After selecting a different configuration and navigating to Common Properties, the configuration always returns to the active one. If you want to keep the selected one while navigating between the Configuration and Common properties, you have to make it the active one.

**Comment by srinivas4912** [comment]
As for the comments, it is not plugin issue.
