### ISSUE TITLE
[2.0.0016] Unable to uninstall API levels that is installed from other than VS plug-in.

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#615]
Preq: 1. Install VS2013 plug-in from Bundle 193[2.0.0016] on Win8.1
     2. Installed API level not from VS plug-in ie. Momentics
Steps to reproduce:
1. From BlackBerry > Setting > Click Get More
2. Select API level not installed from Visual Studio 
3. Click Uninstall

Actual Result:
Observed that uninstalling API level window and after some time show as "complete" but not deleted the source folders from bbndk_vs folder.
![image](https://f.cloud.github.com/assets/5992406/1996164/2e3d5df8-8510-11e3-8000-6518fe1fc80b.png)
![image](https://f.cloud.github.com/assets/5992406/1996174/5e1d256c-8510-11e3-97a5-6b274bd699fc.png)

Expected Result:
User should notify that the action is not allowed and along with a message on how to resolve the issue.

**Comment by pvallabhaneni** [comment]
This issue is observed in Win 7 32bit also using Bundle 195 [2.0.0018].

**Comment by guarnold** [comment]
Workaround to uninstall this kind of API levels: Uninstall it using the same tool that was used to install it (probably Momentics)

**Comment by hkopparru** [comment]
Verified in [3.0.0017] VS 2013, if you have installed NDKs from momentics and you can see these in Visual Studio but showing as in locked state. so the plugin is not giving permissions to uninstall the NDKs which you were installed from momentics. so this issue is invalid. 
Closing this issue now.
