### ISSUE TITLE
[2.0.0018] "Missing Device Password" dialog is shown when "Attach to Process" is selected.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#622]
Preq: Install VS2012 on Win 7 64 bit and Bundle 195[2.0.0018]. Don't set device password in settings.Set the IP Address and password correctly for Simulator in settings.

Set the Active Solution Platform to "BlackBerrySimulator"
Goto Debug->Attach to Process menu.

Actual Result: "Missing Device Password" dialog is shown. After closing "Missing Device Password" dialog, Attach to Process dialog is opening.

![mdp](https://f.cloud.github.com/assets/5992422/2008767/49be3bcc-8751-11e3-86b4-9cf2bcf1cf17.png)

Attach to Process is directly opening in Win 7 32bit using VS2012 and Win 7 64bit using VS2013 Plugin.

**Comment by guarnold** [comment]
This issue was not verified in VS 2013 probably because of issue #604. I believe that, after doing the proposed workaround and debug (and stop debugging) an app using the simulator before Attaching to Process, this issue should be also reproducible in 2013.

Labeled as a P3.

**Comment by srinivas4912** [comment]
The issue is reproduced in VS2013 from [2.0.0018] on Win7 64.
Workaround: "missing device password" dialog has opened,  before attaching to process and after selecting the Transport as "BlackBerry".

**Comment by pvallabhaneni** [comment]
Verified the issue on Win 7 64 bit using v2.0.0022 plugin and VS2012 and found as fixed. Verification passed.
