### ISSUE TITLE
[2.0.0018] Microsoft visual studio has stopped working when recreate new project

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#625]
Preq: Install VS2013 plug-in from Bundle 195[2.0.0018] on Win7 64bit

Steps to Reproduce: 
1. From Visual Studio File > New > New Project... 
2. From New Project Select New Visual C++ > Empty Project in a solution 
3. Provide a relevant name 
4. click OK 
5. from project contextual menu right click 
6. Import BlackBerry Core Native Project 
7. Browse for .project or .cproject [e.g. HelloWorldDisplay] and click Ok 
8. Import Summary window opened and click Ok [Import Summary successfully copies]
9. Again go to File > New > New Project
10. From New Project Select New Visual C++ > Empty Project in a solution 
11. Provide a relevant name 
12. click OK 

Actual Result: It is prompted to Microsoft visual studio dialog and clicked on "yes".
![image](https://f.cloud.github.com/assets/5992406/2038834/4c5b6fd0-8995-11e3-8d18-973c1ea9da4d.png)
![image](https://f.cloud.github.com/assets/5992406/2038867/cb845bfa-8995-11e3-9cef-0a6932197c81.png)

Workaround: It is not reproduced on Win7 32 bit using VS2012 plugin but intermittently observed on Win8.1 using VS2013 plugin.

**Comment by guarnold** [comment]
Could not reproduce this issue using VS 2013 in a Win7 64 bits machine.

Could you try the following:
1 - in the same machine that you can reproduce this issue, verify if you can reproduce the same issue. if yes, it is a Visual Studio issue and not a plugin one:
     a - Follow steps 1 to 4
     b - in the Configuration Manager, add a new one: (x64 or ARM) an select this one for the project
     c - create a source program (right click over Source Files -> Add -> New Item -> C++ file) and write a simple c++ program.
     d - Follow the steps 9 till the end

2 - Verify if you have another similar machine and try to reproduce the same issue. If not, it could be an environment issue.

**Comment by guarnold** [comment]
Also, try in the same machine the following workaround between steps 8 and 9: Close the current solution. If you are not able to reproduce the issue after closing the solution, it might be a possible workaround.

**Comment by srinivas4912** [comment]
Workaround while setting configuration manager (x64 or ARM or Win32) and after closing current solution also, the same issue reproduced with VS2013 plugin from bundle 2.0.0018 on Win7 64bit.

**Comment by guarnold** [comment]
Okay. As you were able to reproduce the same issue with other configurations, please uninstall the plugin and do the same you did before, using x64, arm and Win32 configurations. If the error persists, it is an environment issue (I wouldn't say VS issue because I could not reproduce it here).

**Comment by zadmarbella** [comment]
The issue looks to be reproducible with adding projects to the same solution.

**Comment by srinivas4912** [comment]
Uninstalled the plugin VS2013 from bundle 2.0.0018 on Win7 64 bit. 
Repeated the steps to create new project and found that it is not reproduced, so it is not visual studio issue.

**Comment by dbrgss** [comment]
I couldnt reproduce this either...  on Windows 7.0 running VS2012

**Comment by guarnold** [comment]
Fixed, but the fix is not available yet. I'll update this issue with the build version that will contain this fix.

**Comment by srinivas4912** [comment]
Verification successful using VS2012/13 plugin from build 2.0.0021 on Win 7 64 and Win 8.1
