### ISSUE TITLE
[2.0.0018] Able to close "API Level" dialog without closing "Update Manager" dialog.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#626]
Pre-requisite:
System OS: Win 7 64bit/Win 8.1
API Level: 10.2.1.1155
Plugin Version: 2.0.0018
VS version : VS2012/VS2013

Steps to Reproduce:
1. Install VS2012/VS2013 and NDK plugin on win 7 64 bit.
2. Go to Blackberry->Settings->Get More->Get Simulators
3. Install a simulator.
4. Clcik "Close" while installation is in progress.
5."Cancel Installation?" dialog appears.Click "Yes"

Actual  Result: "Update Manager" dialog is appearing behind the "API level" dialog and user is able to access "API level" dialog without closing "Update Manager" dialog.User is able to close any of these dialogs.

Expected Result: After closing "Cancel Installation?" dialog by selecting "Yes" user needs to close "Update Manager" dialog, then user need to able to close "API level" dialog, then user could be able to close "Settings" dialog.

**Comment by guarnold** [comment]
It might be fixed after fixing issue #432. Please, verify using the next available build.

**Comment by pvallabhaneni** [comment]
As per the description in  #432, the issue is about the focus on update manager(update manager message box used to hide behind API level/Simulator dialog, now it is  shown on top of them)  which is fixed.

This issue (#626) is that the user is able to close the API level without closing update manager message box (which is above API level dialog).

verified using 2.0.0022 plugin on Win 7 64bit and found that the issue is still reproducing.

**Comment by dbrgss** [comment]
For better clarification.. can you please attach screen shots of the dialogs in question??

**Comment by pvallabhaneni** [comment]
Following behavior is observed in v2.0.0018 plugin.
1. Install VS2012/VS2013 and NDK plugin on win 7 64 bit.
2. Go to Blackberry->Settings->Get More->Get Simulators
3. Install a simulator.
4. Clcik "Close" while installation is in progress.
   5."Cancel Installation?" dialog appears.Click "Yes"

Update Manager dialog is shown behind the API level dialog as shown below. 

![1](https://f.cloud.github.com/assets/5992422/2204034/88653d88-9932-11e3-9bb5-ac9d1663e0fe.PNG)

User is able to close API level dialog without closing Update Manager dialog.

![2](https://f.cloud.github.com/assets/5992422/2204056/4b208f1c-9933-11e3-851b-fee31067a503.PNG)

Also able to close Settings dialog without closing Update Manager dialog.

![3](https://f.cloud.github.com/assets/5992422/2204059/59c8ab58-9933-11e3-9823-95ebf9ad399f.PNG)

Following behavior is observed in v2.0.0022 plugin.
1. Install VS2012/VS2013 and NDK plugin on win 7 64 bit.
2. Go to Blackberry->Settings->Get More->Get Simulators
3. Install a simulator.
4. Clcik "Close" while installation is in progress.
   5."Cancel Installation?" dialog appears.Click "Yes"

Update Manager dialog is shown above the API level dialog.

![1](https://f.cloud.github.com/assets/5992422/2204106/cb309b60-9934-11e3-8b8f-498cd184293c.PNG)

But still user is able to close API level dialog without closing the Update Manager dialog.

![2](https://f.cloud.github.com/assets/5992422/2204107/d277792a-9934-11e3-8e75-3c9c8f0f55c0.PNG)

Also Able to close Settings dialog without closing Update Manager dialog.

**Comment by pvallabhaneni** [comment]
[3.0.0005] VS 2013 Windows 7, the API level window UI got changed, where we can see the status of current and pending installations. so there is no effect if you close the API level dialog here.

**Comment by pvallabhaneni** [comment]
Closing the issue.
