### ISSUE TITLE
[2.0.0021] Simulator is shown as installing without internet connection.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#635]
Steps to Reproduce:

1.Have internet connection enabled on the system.
2.Go to Blackberry->Settings->Get More.
3. API levels dialog is opened with the correct list of API levels in the available section.
4. Remove internet connection for the system.
5. Click on "Get Simulators" button.
6. "Simulators" dialog is opened with correct list of simulators available for downloading.
7. Select a simulator and click "Install".

"Installing 10.1.0.4828 simulator" is shown and "Complete" is shown immediately.

Note: No folder is found related to simulator in bbndk_vs folder.

**Comment by guarnold** [comment]
Fix available in build version 2.0.0022.

**Comment by pvallabhaneni** [comment]
verified on Win 7 64 bit using v2.0.0022 plugin and settings message is shown with the following message: 
"You are currently experiencing internet connection issue and cannot access the Update Manager server. Please check your connection or try again later."

Found as fixed.
