### ISSUE TITLE
[2.0.0022] Values in Add Watch window are not updating until a new variable is added.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#638]
Preq: 
System OS: Win 7 64 bit
VS Version: VS2012
Device OS: 10.2.0.1809
API level : 10.2.0.1155
Runtime: 10.2.0.1809
Plugin: v2.0.0022

Steps to Reproduce:
1. Set a break-point at 2 places just before the variables are initialized and after initialization as follows. 
   ![1](https://f.cloud.github.com/assets/5992422/2170534/285de6b8-956f-11e3-8742-aa6297020069.PNG)
2. Press Shift+F9 or open Quick watch dialog.
3. Add the variables present in the statements at the breakpoints.
   Observe that the values are shown correctly as shown below.
   ![2](https://f.cloud.github.com/assets/5992422/2170537/34cb4558-956f-11e3-9755-9091bc5739f4.PNG)
4. Press F10.
   Observe that the values are shown as "No symbol <variable name> in current context" as shown below.
   ![3](https://f.cloud.github.com/assets/5992422/2170541/3e5f3232-956f-11e3-9722-fe80f6f0de5e.PNG)
5. Even the value in the tips box is showing the same as shown below.
   ![4](https://f.cloud.github.com/assets/5992422/2170543/449bbe0e-956f-11e3-84f6-fb28d4e89b44.png)
6. Insert one more variable to add watch. Then the values for the above variables are refreshed with correct values as shown below.
   ![5](https://f.cloud.github.com/assets/5992422/2170545/50129c12-956f-11e3-8bdd-c6ce41e2de2b.PNG)

Note: this behaviour is observed even if continue to debug. Values in the added variables are updated only after adding a new variable on to the Watch window.

**Comment by srinivas4912** [comment]
Encountered the same issue in  Win8.1/OS 10.2.1.1925/VS2013/2.0.0022  on Astro device.

Adding VS 2013 label.

**Comment by hkopparru** [comment]
Tested with [3.0.0005] VS 2013, issue is not reproducible. variables values are updating properly in watch window.
Observed that i could not find "No symbol in current context" in value field from watch window.

closing this issue now
