### ISSUE TITLE
[2.0.0022] Nothing is happening when debug token dialog is opened without device IP set.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#639]
OS - Win 7 64 bit
Plugin version - 2.0.0022

Steps to Reproduce:
1. Install the plugin 
2. Goto Blackberry->Settings
3. Remove the device IP address (which is set by default during plugin installation)
4. Goto Blackberry->Debug token

Actual Result: Nothing is happening. Neither an error is shown nor the debug toke n dialog is opened. Even processing is not shown in the cursor as per #487

**Comment by srinivas4912** [comment]
In VS2013 on Win8.1 system, above issue is reproducible using 2.0.0022 plugin.

I continued the below steps after the 4th steps in above scenario.
1. Go to Blackberry->Settings
2. Add IP address and password for the device
3. Go to Blackberry->Debug token

Actual Result: Below error message is shown.
![bug](https://f.cloud.github.com/assets/5992406/2184285/156275c4-97bd-11e3-8a03-f83cdf4eea23.png)

**Comment by hkopparru** [comment]
in 3.0 plugin the UI got changed for this.
1. without the ip address you can add the device
2. if the ip address is correct then it will upload the debug token otherwise it will prompt the message "missing device"

so closing this issue now.

**Comment by hkopparru** [comment]
first comment correction: without the ip address you can't add the device
