### ISSUE TITLE
[2.0.0022] Adding same image multiple times is not saved in bar-descriptor.xml

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#641]
OS: Win 7 64 bit / Win 8.1 64bit
Plugin : 2.0.0022
VS version : VS2012 / VS2013

Steps to Reproduce:
1. Install the plugin and open a project in visual Stiudio.
2. Open bar-descriptor.xml file
3. Add an image to Icon and Splash Screen in Appearance Section.
4. Add the same image multiple times to both Icon and Splash Screen in Appearance Section.
5. Save the file (CTRL + S)
6. Observe that the file is saved.
7. Close bar-descriptor.xml file.
8. Open bar-descriptor.xml file again.

Actual Result: image file is shown multiple times (number of time that we have added) in the Splash Screen section. But only once in Icon section.

**Comment by dbrgss** [comment]
Sorry closed accidentally.. re-opening.

**Comment by hkopparru** [comment]
in 3.0 plugin issue got resolved, where you can see the images multiple times in both icon and splash screen sections
