### ISSUE TITLE
[2.0.0022] installer detects if java is installed on the machine to and notify user if not

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#643]
Preq:
System OS - Win 7 64 bit
VS Version :VS2012
Plugin Version : 2.0.0022

Scenario 1:
1. Install Visual Studio and NDK plugin on fresh machine.
2. Open Blackberry->Signing.

Actual Result: Error message (Eclipsec) is shown. This is happening only once and if error message is closed and open the settings again nor error message is shown.
Note: Environmental Variables are not modified at any of the above instances.

capture

Scenario 2:
1. Uninstall the plugin installed from the above steps.
2. Restart the system.
3. Install the plugin again.
4. Select Blackberry->Signing.

Actual Result: 
Bug1 : Above dialog(Eclipsec) is shown. Only after closing the dialog fr 3 times, signing dialog is shown.
Bug 2 : Observe that the path shown on the dialog is "C:\bbndk_vs\jre\bin\javaw.exe". 
Where as path set in te environment variable is: "C:\bbndk_vs\features\com.qnx.tools.jre.win32_1.6.0.43\jre\bin;"

**Comment by dbrgss** [comment]
Please to do the following..  

1) Uninstall the plugin... restart Windows
2) Install the plugin... Do not restart Visual Studio right away... Check the Environment Variables for the Path. (Paste into issue as a comment)
3) Restart Windows
4) Start Visual Studio and the Signing Dialog.

**Comment by pvallabhaneni** [comment]
1. Un-installed the plugin and restarted the Windows system
2. Installed the plugin. Set the Environmental Variable for the path.
   Path variable : C:\bbndk_vs\features\com.qnx.tools.jre.win32_1.6.0.43\jre\bin
3. Restarted the Windows system
4. Opened Signing Window

Error message is not shown.

**Comment by dbrgss** [comment]
Okay.. it appears that the Path variable being set in the installer is NOT being refreshed globally until a system restart.  Although annoying I don't believe this needs to be fixed in this release.  P3 Level is appropriate.

**Comment by srinivas4912** [comment]
Encountered the same issue in Win8.1/OS 10.2.1.1925/VS2013/2.0.0022 on Astro device.

Adding VS 2013 label.

**Comment by hkopparru** [comment]
tested in 3.0.0001 plugin, no issues.
closing this issue.
