### ISSUE TITLE
[2.0.0022] Unable to maximize and minimize browser window while creating debug token

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#645]
1. From BlackBerry > Signing > Register
2. Input username, password fields and click on Sign In
3. It is prompting to "sign in to create and download your Blackberry ID token"  window 

Actual Result: 1. minimize is disabled and maximize button is enabled
2. when clicked on maximize button window is not auto adjusting to the screen.
![browser1](https://f.cloud.github.com/assets/5992406/2204510/914b5106-993e-11e3-9391-b5abe02c6416.png)

**Comment by hkopparru** [comment]
not reproduced, here after clicked on maximize button then the window is adjusting to the screen. no issues here.

closing this issue
