### ISSUE TITLE
[2.0.0022] Simulators are downloaded even if user cancels downloading.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#646]
Preq: 
System OS : Win 7 64 bit
VS Version: VS2012/VS2013.

Steps to Reproduce:
1. Install VSNDK plugin and VS2012/VS2013 on a fresh machine.
2. Open Visual Studio.
3. Go to Blackberry->Settings->Get More->Get Simulators.
4. Install a simulator.
5. Click on Close on simulator dialog.
6. Prompt appears asking if user wants to cancel the installation.
7. Click "Yes"
8. Simulators dialog is closed and a warning message appears from update manager that installation is cancelled by the user.

Actual Result: After some time (about 1 hr), observe that simulator folder is downloaded to C:\bbndk_vs folder.  Also the simulator is shown in "Installed" list present in Simulators dialog.

**Comment by hkopparru** [comment]
issue not reproduced in latest 3.0 plugin. closing this issue
