### ISSUE TITLE
[2.0.0022] able to import projects that include default project build properties

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#651]
Preq: empty win32 project
1. import Blackberry Native Core Project
2. open Project Properties
3. Switch to Blackbery Configuraion

current behaviour:
expected default properties are not selected.
ie. Configuration Properties > General > Platform tool set  is not qcc
VC++ Directories do not include default executable directories.
etc.

Workaround:
user has to go through and find default properties and add them back into their imported project.

**Comment by hkopparru** [comment]
tested with [3.0.0005] plugin using VS 2013, issue is not reproducible

after changing to the BlackBerry configuration where i am able to see 
Configuration Properties > General > Platform tool set to qcc.

closing this issue now.
