### ISSUE TITLE
[2.0.0022] Able to close the API level dialog without any prompt while downloading second API level.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#653]
Preq: 
Win OS: Win 7 64 bit / Win 8.1 64 bit.
VS Version : VS2012/VS2013

Steps to Reproduce:
1. Go to Blackberry->Settings-> Get more...
2. Download an API level.
3. Once downloading is complete, install another API level without closing the API level dialog.
4. Close API level dialog while downloading is in progress.

Actual Result: API level dialog is closed without any prompt from update manager to the user that installation is in progress.

**Comment by hkopparru** [comment]
[3.0.0001] VS 2013 Windows 7, the API level window UI got changed, where we can see the status of current and pending installations. so there is no effect if you close the API level dialog here.

**Comment by phofman** [comment]
What is the code base you are using? I don't see tag 3.0.0001. Is this the latest from this repo?

**Comment by hkopparru** [comment]
i have tested this on new plugin 3.0.

**Comment by hkopparru** [comment]
that's the plugin version 3.0.0001

**Comment by phofman** [comment]
OK, I see tag, 3.0.0003 and was just wondering. In that case, download status is on API-Levels tab in Tools -> Options -> BlackBerry. But could you ask Dave, if you guys want the latest code and if he will merge them from my fork? I fixed lots of stuff being 210 commits ahead. Why to double your work...

**Comment by hkopparru** [comment]
closing this issue
