### ISSUE TITLE
[2.0.0022] VS2013 - Plugin "API Levels" window not visible on any taskbar!

### ISSUE THREAD

**Issue by MrKaktus** [blackberry/VSPlugin#655]
When opening VS2013 Solution first time after installing BB VS2013 Plugin, I see "API Levels" window popup that says:

Please choose your default API Level to be used by the Visual Studio Plug-in:
o BlackBerry Native SDK 10.0
o BlackBerry Native SDK 10.1
o BlackBerry Native SDK 10.2
[Close][Install]

This windod pop-ups during "Preparing Solution..." stage and it is not visible on any taskbar! This means that if you've switched to any other window during Preparing Solution stage, this window WON'T pop-up in fact, and you don't know that it is there, because it has no icon on taskbar. 

When in Visual Studio, after selecting BLACKBERRY > Settings > [Get More..] when "API Levels" window pops-up, it is also invisible on any taskbar, even though "Settings" window is visible.

RESULT:
User thinks Visual Studio has freezed during opening Solution.

REPRODUCTIVITY:
100% on Visual Studio 2013 Ultimate and Windows 7 64bit SP1

WORKAROUND:
For both cases open Task Manager, find window process called "API Levels", bring it up-front to interact with it.

**Comment by guarnold** [comment]
Workaround 2: You can also use Alt+Tab keys and look for the VS session. The API Level window will appear on top of the VS session after using the Alt+Tab keys.

**Comment by guarnold** [comment]
This issue is reproducible and we are going to investigate it.

**Comment by hkopparru** [comment]
in the new plugin 3.0 the API level UI window got changed. tested looks fine.

closing this issue
