### ISSUE TITLE
[2.0.0022] VS2013 - No option to select 10.2 NDK !

### ISSUE THREAD

**Issue by MrKaktus** [blackberry/VSPlugin#656]
When opening VS2013 Solution first time after installing BB VS2013 Plugin, I see "API Levels" window popup that says:

Please choose your default API Level to be used by the Visual Studio Plug-in:
o BlackBerry Native SDK 10.0
o BlackBerry Native SDK 10.1
o BlackBerry Native SDK 10.2
[Close][Install]

After selecting option 10.2, but hitting [Close] or X window button to cancel operation this time, when entering BLACKBERRY > Settings > [Get More..] I see SDK 10.2 as already installed even though I've skipped API downloading. After closing VS and opening it again, this window pop-ups again but now I can only choose options 10.0 and 10.1. 10.2 is not visible because plugin thinks it is installed even though it's not. Window will now pop-up every time I'm opening VS or trying to do Rebuild / Clean Solution ( even when working on Windows project configuration ).

I cannot uninstall this SDK, and reinstall it again because of plugin policy that you always need to have at least one SDK installed and bug #657.

Uininstalling Plugin, restarting PC, deleting it's directory and installing it again doesn't help. SDK 10.2 is still seen as installed.

REPRODUCTIVITY:
100% on Visual Studio 2013 Ultimate and Windows 7 64bit SP1

**Comment by guarnold** [comment]
As issue #657, the bbndk_vs folder might be corrupted. Maybe cancelling the initial installation may  have caused that corruption. We are going to investigate that.

A workaround to fix this problem:

I - close Visual Studio;
II - delete the bbndk_vs and qconfig folders completely.

Then you can use VS normally (don't forget to install an NDK without cancelling the initial API level installation).

Please, let us know if this workaround solves this issue for you.

**Comment by hkopparru** [comment]
in [3.0.0001] VS 2013 windows 7 i couldn't find this issue, where i am able to install,uninstall and abort successfully for 10.3 and 10.2 as well
But ndk installation for 10.0 and 10.1 is not finishing successfully and tracking this in #657.
so i am closing this issue.
