### ISSUE TITLE
[2.0.0022] VS2013 - Including files not taking into notice Additional Include Path

### ISSUE THREAD

**Issue by MrKaktus** [blackberry/VSPlugin#658]
Reproduction steps:

Solution Dir:
include
include > core
include > core > context.h
include > defines.h

In Solution's Project Properties:
Additional Include Directories: "./include/"

In context.h:
# include "./../defines.h"       // Works
# include "defines.h"            // Doesn't work, and it should by resolving to AID param

It looks like plugin is searching only in local dir.

**Comment by dbrgss** [comment]
Okay so this actually seems to be working for me.  If you try your test again.. can you please post up the qcc commands displayed in the Output window in the Link: section.

**Comment by dbrgss** [comment]
So I had one of our testers run through this.   It appears that adding the include path to the Additional Include Directories works in as far as it allows the project to build.  Our testers found though, that intellisense does not work, unless you specify the path like you stated above.. "../../defines.h"   

Is this what you were experiencing as well??

**Comment by MrKaktus** [comment]
I've restarted the PC, cleaned whole solution and now it compiles, I cannot reproduce it anymore. Bug can be closed, sorry for trouble.
