### ISSUE TITLE
[3.0.0001] not able to remove the debug tokens from the device using the "remove" button which in "Debug Token Deployment" dialog

### ISSUE THREAD

**Issue by hkopparru** [blackberry/VSPlugin#668]
Preq:
Win OS: Win 7 64 bit
VS version: VS2013

Steps to reproduce:
1. upload debug token onto the device using below
   a.  BLACKBERRY->options->Targets -> Upload Debug Token, 
       "Debug Token Deployment" dialog opens then give the Debug Token file path which you have
   Example: C:\Users\hkopparru\AppData\Local\Research In Motion\debugtoken-2015-01-16.bar

b. press upload button, upload successfully.
1. press remove button from the same "Debug Token Deployment" dialog, then press yes button to remove debug tokens from the device.
2. debug tokens are not removed and its showing the below error

Removing debug token from usb (169.254.0.1, device)...
--- DONE with failure

500 cannot determine package name

**Comment by phofman** [comment]
You can always take extra runtime logs, when visiting the 'View' -> 'Output' -> 'BlackBerry' pane. I can confirm, it fails also on my side, but seems to be related to underlying QNX-tools.

```
!! Info: Sending request: UNINSTALL
Info: Action: Uninstall
Info: Uninstalling gYABgE9Qwhm4RpkL-DyrkPDSOUw...
Info: Processing 0 bytes
actual_dname::
actual_id::
actual_version::
result::failure 500 cannot determine package name
```

While metadata from debug-token is:

```
Package-Name: debug.token
Package-Id: gYABgE9Qwhm4RpkL-DyrkPDSOUw
```

**Comment by dbrgss** [comment]
I seem to remember that this issue was caught in our previous version of the plugin.  We need to check for a duplicate.

**Comment by hkopparru** [comment]
Still this issue is persistent in [3.0.0005]

**Comment by dbrgss** [comment]
I remember a known issue that prevented us from removing debug tokens from the device remotely from the IDE.   I have been looking for it but can't seem to find it.  I think there is a JIRA for this in our internal database.

**Comment by dbrgss** [comment]
This is an issue with the NDK command line tools.   

Related JIRA83760

**Comment by dbrgss** [comment]
Removed the button...  no longer an issue.
