### ISSUE TITLE
[3.0.0005] Message is not meaningful when "Refresh" is selected without any qualifier selected.

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#679]
Environment: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. Configure a device on "Blackberry -> Options ->Blackberry -> Targets"
2. Select "debug -> Attach to Process"
3. Attach to Process dialog opens
4. Do not select the device in Qualifier.
5. Click on "refresh"
6. Meaning full message appears as "Unable to create device connection"
7. Click OK

Actual Result: Error message shown is not meaning full and complete.

![bug](https://cloud.githubusercontent.com/assets/5992422/6020193/05540b44-abcf-11e4-837b-f03428b679e3.png)

Expected Results: Error message need to complete and meaning full.

**Comment by phofman** [comment]
My opinion: won't fix / ticket invalid
Explanation: the meaningless message is displayed by VS2013 itself, can't be changed by the plugin (plugin already displayed the valid one just before). It's a result of returning E_FAIL by AD7PortSupplier::AddPort(). Returning S_OK will not cause additional message, but will populate the list with processes on current machine, what is even worse.

**Comment by dbrgss** [comment]
After investigation I agree with Pawel.  This is an internal VS issue.. that is not currently fixable.
