### ISSUE TITLE
[3.0.0005] bar-descriptor doesn't auto create when deleted on vs2013

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#687]
Environment:
System OS: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. From a project, delete bar-descriptor.xml file.

Actual Result: bar-descriptor.xml is not generated automatically.
Expected Result: bar-descriptor.xml file has to be auto-generated.

**Comment by phofman** [comment]
Any idea, why it should be added automatically? You deleted it on purpose ;) So maybe you really don't need it. Via settings you can specify the name of the bar-descriptor.xml, which should be used during the build, which might be located anywhere on your machine.

You can always restore it manually, if needed. Just right-click the project and choose: _Add -> New Item... -> BlackBerry -> BAR descriptor_ and it will place a default bar-descriptor.xml (or however you name it) back into the project.

**Comment by pvallabhaneni** [comment]
#350 is similar issue which is fixed for VS2012 and closed.

**Comment by phofman** [comment]
OK, I understand. However issue you mentioned is 2-years old and for previous version of the plugin. I guarantee I already removed that code long time ago and there is no such a feature as automatic restoration of bar-descriptor.xml. I doubt it will be back again ;) The expected approach is that developer creates new one by adding New Project Item as described earlier or restores it from the app's repository.

**Comment by dbrgss** [comment]
I view this as a modified workflow and not a bug.

**Comment by pvallabhaneni** [comment]
Not an issue. This is expected behavior.Closing the issue.
