### ISSUE TITLE
[3.0.0005] "BlackBerry Native Plug-in for Microsoft Visual Studio" is not shown in Add-In Manager

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#688]
Environment:
System OS: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. Install VS2013
2. Install "BlackBerry Native Plug-in for Microsoft Visual Studio 2013"
3. Open VS 2013
4 .Goto Tools -> Add In Manager

Actual Result: Plugin is not shown in Add-in Manager dialog.

![bug](https://cloud.githubusercontent.com/assets/5992422/6106256/c7a86ea0-b085-11e4-9e83-c7c284185684.png)

Expected Result: In the Add-In Manager BlackBerry Native Plug-in for Microsoft Visual Studio is installed and checked along with Start up. Below is the picture taken using VS2012 and 2.0 plugin.

![untitled](https://cloud.githubusercontent.com/assets/5992422/6106267/eba5bae2-b085-11e4-9314-f963c913979d.png)

**Comment by phofman** [comment]
Voting: invalid

That's great it's not listed there anymore as I ported the plugin to be full-featured VS-Package without any satellites solutions and add-in dependencies. You can find info about the package in Help->About Microsoft Visual Studio -> BlackBerry Native SDK Plugin for Visual Studio.

**Comment by dbrgss** [comment]
This is correct.   The Add-In has been removed.

**Comment by pvallabhaneni** [comment]
Not an issue. This is expected behavior.Closing the issue.
