### ISSUE TITLE
[3.0.0015] "Type" of device is not updating for USB device and Wi-Fi device

### ISSUE THREAD

**Issue by pvallabhaneni** [blackberry/VSPlugin#704]
Environment:
System OS: Win 7 64bit and Win 8.1

Steps to Reproduce:
1. Add a USB device, Wi-Fi device and a Simulator to the Targets.

Actual result:
Observe that the "type" of the device is not updated for USB device and Wi-Fi device. Simulator type is updated as "S".

![capture](https://cloud.githubusercontent.com/assets/5992422/6186775/1aad8cf4-b3a4-11e4-9c9a-a9feb5480636.PNG)

**Comment by phofman** [comment]
Yes, it's updated. Just the assmption is:
- empty string = device
- S = simulator

Edit the 'simulator' and change to 'Wi-Fi' and you will see the type column gets empty...

**Comment by pvallabhaneni** [comment]
Closing the issue as per the above comments.
