### ISSUE TITLE
[3.0.0015] USB device is able to connect with the WiFi device type and vice versa

### ISSUE THREAD

**Issue by srinivas4912** [blackberry/VSPlugin#710]
Environment:
System OS: Win 7 and 8.1 64-bit

Steps to Reproduce:
1) Go to BlackBerry > Options...
2) Select BlackBerry > Targets
3) Click on Add... button, Add New Target Device dialog appears
4) Select Type as USB device, enter the WiFi IP address and password
5) Click on Test, It is able to connect the device
6) Select Type as WiFi device, enter the USB IP address(169.254.0.1) and password
7) Click on Test, It is able to connect the device

![image](https://cloud.githubusercontent.com/assets/5992406/6227058/085835ca-b6c1-11e4-9f56-0db04250f6e0.png)

![image](https://cloud.githubusercontent.com/assets/5992406/6227077/2c941fbc-b6c1-11e4-865f-de7afa818adb.png)

**Comment by phofman** [comment]
That's nothing new. It's by design. Where is the problem then?

Suggestion: ticket invalid / reject

**Comment by phofman** [comment]
HINT: this plugin is also capable of connecting to the device from 2 running Visual Studios in parallel, along with Momentics running next to them (assuming that this soft connected as first one). That is a feature not working at all, if you have two instances of Momentics, trying to access the same device.

**Comment by dbrgss** [comment]
I agree this is not a bid deal.  The WIFI or USB is just a label to ease in identifying..  as long as the connection is tested and it succeeds or doesnt.. is all that really matters

**Comment by srinivas4912** [comment]
As per the above comments, closing the issue.
