### ISSUE TITLE
b113 - unable to deploy to device (failing Tracking command)

### ISSUE THREAD

**Issue by zadmarbella** [blackberry/VSPlugin#9]
We are seeing device deploy fail on certain environments.
OS win 7 
It is unclear the cause. There is no workaround.

Error message is below:
1>Done executing task "Message". (TaskId:13)
1>Using "BBNativePackager" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\VSNDK.Tasks.dll".
1>Task "BBNativePackager" (TaskId:14)
1>  Tracking command: (TaskId:14)
1>  c:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools\Tracker.exe /d C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll /i C:\workspace\FallingBlocks_001\Device-Debug /r "C:\WORKSPACE\FALLINGBLOCKS_001\BAR-DESCRIPTOR.XML|C:\WORKSPACE\FALLINGBLOCKS_001\BAR-DESCRIPTOR.XML|C:\WORKSPACE\FALLINGBLOCKS_001\ICON.PNG|C:\WORKSPACE\FALLINGBLOCKS_001\ICON.PNG|C:\WORKSPACE\FALLINGBLOCKS_001\LICENSE|C:\WORKSPACE\FALLINGBLOCKS_001\LICENSE|C:\WORKSPACE\FALLINGBLOCKS_001\NOTICE|C:\WORKSPACE\FALLINGBLOCKS_001\NOTICE" /b MSBuildConsole_CancelEventbdce0e94eb8549ee9a1967acfa21811a  /c C:/bbndk_10.1.0.1020/host_10_1_0_212/win32/x86\usr\bin\blackberry-nativepackager.bat  -target bar-debug -devMode "Device-Debug\FallingBlocks_001.bar" "bar-descriptor.xml" "icon.png" -e "Device-Debug/FallingBlocks_001" "FallingBlocks_001" -target bar-debug -devMode "Device-Debug\FallingBlocks_001.bar" "bar-descriptor.xml" "icon.png" -e "Device-Debug/FallingBlocks_001" "FallingBlocks_001" (TaskId:14)
1>  The system cannot execute the specified program. (TaskId:14)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.Packager.targets(110,5): error MSB6006: "blackberry-nativepackager.bat" exited with code 1.
1>Done executing task "BBNativePackager" -- FAILED. (TaskId:14)
1>Done building target "BuildBar" in project "FallingBlocks_001.vcxproj" -- FAILED.: (TargetId:6)
1>Done executing task "CallTarget" -- FAILED. (TaskId:8)
1>Done building target "Deploy" in project "FallingBlocks_001.vcxproj" -- FAILED.: (TargetId:3)

Compared the os that was deploying to the one that wasn't

Added this in the target file
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.Packager.targets

```
<Message Text="Sources: @(BuildBar)"/>
<Message Text="Platform: $(Platform)"/>
<Message Text="Configuraiton: $(Configuration)"/>
<Message Text="ApplicationDescriptorXml: %(BuildBar.ApplicationDescriptorXml)"/>
<Message Text="ProjectDir: $(ProjectDir)"/>
<Message Text="SolutionDir: $(SolutionDir)"/>
<Message Text="Device: $(Registry:HKEY_CURRENT_USER\SOFTWARE\BlackBerry\BlackBerryVSPlugin@device_IP)"/>
<Message Text="Password: $(Registry:HKEY_CURRENT_USER\SOFTWARE\BlackBerry\BlackBerryVSPlugin@device_password)"/>
<Message Text="BarDeploy: %(BuildBar.BarDeploy)"/>
<Message Text="DevMode: %(BuildBar.BarDeploy)"/>
<Message Text="PackageManifestOnly: $(IsAppInstalled)"/>
<Message Text="DebugToken: %(BuildBar.DebugToken)"/>
<Message Text="TargetFormat: %(BuildBar.TargetFormat)"/>
<Message Text="OutputFile: %(BuildBar.OutputFile)"/>
<Message Text="ToolExe: $(BuildBarToolExe)"/>
<Message Text="ToolPath: $(ToolPath)"/>
<Message Text="TrackFileAccess: $(TrackFileAccess)"/>
<Message Text="MinimalRebuildFromTracking: $(BuildBar_MinimalRebuildFromTracking)"/>
<Message Text="TrackerLogDirectory: %(BuildBar.TrackerLogDirectory)"/>
<Message Text="TLogReadFiles: @(BuildBarTLogReadFiles)"/>
<Message Text="TLogWriteFiles: @(BuildBarTLogWriteFiles)"/>
<Message Text="AcceptableNonZeroExitCodes: %(BuildBar.AcceptableNonZeroExitCodes)"/>
```

Both showed the same thing.

Attempted to Reset Environment Settings. Still gave the same issue.

**Comment by zadmarbella** [comment]
workaround looks to be setting the adding to the PATH the ndk jre resource bin folder.

**Comment by mattcostanzo** [comment]
1 day, if reproducible
