### ISSUE TITLE
On/Off Switch for Multi-Core Build Optimization Functionality

### ISSUE THREAD

**Issue by dbrgss** [blackberry/VSPlugin#93]
User Story #25

Need the ability to turn the Multi Core Build Optimization feature on or off.

Estimates 1-2 days

**Comment by zadmarbella** [comment]
Where is the switch?

**Comment by zadmarbella** [comment]
verified 1.01.0017
From Project Properties 
Configuration Properties > C/C++ > Multi Process Compilation
